### ISSUE TITLE
Download a innexistent version

### ISSUE THREAD

**Issue by Zagur** [TryGhost/Ghost-CLI#1027]
I was looking to install a version earlier than 3.0 (for some testing) and I've seen that if you add version 2.7 it seems to install that version. But the latest version is 2.37.0.

In version/package.json:

```
{
  "name": "ghost",
  "version": "2.9.0",
  "description": "The professional publishing platform",
  "author": "Ghost Foundation",
  "homepage": "https://ghost.org",
```
 
# Steps to Reproduce

1. ghost install 2.9

### Output command

```
$ ghost install 2.9
✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v2.9.0
✔ Finishing install process
? Enter your blog URL: (http://localhost:2368)
```

### Technical details

* OS: 18.04.1 LTS (Bionic Beaver
* Node Version: v10.17.0
* Ghost-CLI Version: 1.12.0
* Environment: production
* Command: ghost install 2.9

**Comment by acburdine** [comment]
@Zagur I'm not sure what you're expecting to happen? 2.37 is a newer version than 2.7, so if you manually specify 2.7 (or 2.9, as you've specified in the issue), it will happily download and install that version.

**Comment by acburdine** [comment]
Going to close this issue as this is completely expected behavior - all three versions are valid versions of Ghost.

- [v2.7.0](https://github.com/TryGhost/Ghost/releases/2.7.0)
- [v2.9.0](https://github.com/TryGhost/Ghost/releases/2.9.0)
- [v2.37.0](https://github.com/TryGhost/Ghost/releases/2.37.0)
