### ISSUE TITLE
ghost install -> process error occurred

### ISSUE THREAD

**Issue by hintermair** [TryGhost/Ghost-CLI#1066]
![image](https://user-images.githubusercontent.com/17347222/69144537-cf40f100-0acb-11ea-98a3-b6dbf85143c9.png)

Hello,
i am trying to install, but i run into this (or a similar error) every time. i found some issues via google and tried to the solutions provided by them, like https://github.com/TryGhost/Ghost-CLI/issues/696 and linked.
unfortunately i am still where i was 3 days ago. 
help is highly  appreciated, greetings

**Comment by acburdine** [comment]
@hintermair is there anything in the "additional log info" file?

**Comment by hintermair** [comment]
[ghost-cli-debug-2019-11-19T11_37_13_546Z.log](https://github.com/TryGhost/Ghost-CLI/files/3864231/ghost-cli-debug-2019-11-19T11_37_13_546Z.log)

file is attached now, but as far as i can tell it is the same info as the terminal output

**Comment by acburdine** [comment]
hmm 🤔can you try running with the `--verbose` flag? there will be a _lot_ of output but it may highlight what's actually erroring

**Comment by hintermair** [comment]
did, and it is a lot of output. :/

**Comment by hintermair** [comment]
the log file is over 10mb.

**Comment by acburdine** [comment]
maybe look at the log via tail? `cat <log file> | tail -n 100`

**Comment by hintermair** [comment]
[ghost-cli-debug-2019-11-19T16_03_43_432Z.log](https://github.com/TryGhost/Ghost-CLI/files/3864947/ghost-cli-debug-2019-11-19T16_03_43_432Z.log)
or i turn on js, thats the complete log. lots of copying, than 2 symlink. than stderr.

**Comment by CptDoraemon** [comment]
Might be insufficient RAM.
I had exactly same issue, the downloading and installing of Ghost was very slow, and ended up with the same warning message.
Solved by changing to a server with 1GB RAM (was 512MB).

**Comment by CptDoraemon** [comment]
Might be insufficient memory.
I had exactly same issue, ghost install terminated with the same warning. And before that, the installing phase was very slow.
Problem solved by switching to another server with 1GB ram (was 512MB).

**Comment by mrusme** [comment]
Please find a possible solution (or at least some hints on how to further debug this) in #1103.
