### ISSUE TITLE
Use standard port for SELinux + Nginx compatability

### ISSUE THREAD

**Issue by heyakyra** [TryGhost/Ghost-CLI#1071]
### Summary

Ghost's port proxying causes issues with SELinux, which are described a bit here: 
https://github.com/taw00/howto/blob/master/howto-install-ghost-on-fedora.md#configure-nginx

### Steps to Reproduce

1. Use SELinux
2. Install Ghost

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Any
* Node Version: Any
* Ghost-CLI Version: Any

### Workarounds

Things that haven't worked:
* `sudo ln /var/www/[ghost site]/system/files/ghost_[ghost site].service /etc/systemd/system/ghost_[ghost site].service`
* `sudo semanage fcontext -a -t systemd_unit_file_t system/files/ghost_[ghost site].service`
* `sudo restorecon -vF 'files/system/ghost_dfwalliance-org.service'`
* `sudo semanage fcontext -a -t systemd_unit_file_t -s system_u /usr/lib/systemd/system/ghost_[ghost site].service`
* `sudo restorecon -vF '/usr/lib/systemd/system/ghost_dfwalliance-org.service'`

Have `setroubleshoot` installed and monitor `journalctl` for errors / suggestions.

**Comment by heyakyra** [comment]
Still relevant

**Comment by ErisDS** [comment]
Do you intend to work on it?

**Comment by ErisDS** [comment]
To be clear, you opened this feature request to add support beyond our recommended stack well over a year ago. We only just have enough contributors to maintain the recommended stack. No one else has interacted with this to suggest it's desirable or that there's a team of people wanting to work on it, and as far as we're aware you're not intending to work on it either. Therefore it's not something we need to keep open.
