### ISSUE TITLE
Fedora Compatability

### ISSUE THREAD

**Issue by heyakyra** [TryGhost/Ghost-CLI#1072]
### Summary

Fedora is becoming a popular choice for modern GNU+Linux features and security. Support should not be too difficult to implement, so long as SELinux compatability #1071 and detecting which nginx and mysql packages #460 to look for.

**Comment by heyakyra** [comment]
Still relevant

**Comment by ErisDS** [comment]
Do you intend to work on it?

**Comment by ErisDS** [comment]
To be clear, you opened this feature request to add support beyond our recommended stack well over a year ago. We only just have enough contributors to maintain the recommended stack. No one else has interacted with this to suggest it's desirable or that there's a team of people wanting to work on it, and as far as we're aware you're not intending to work on it either. Therefore it's not something we need to keep open.
