### ISSUE TITLE
Subscription error (after update 3.6.0)

### ISSUE THREAD

**Issue by antomal** [TryGhost/Ghost-CLI#1108]
After the update 3.6.0, it is impossible to subscribe. Error → → Please enter a valid email address!
The mail setup is correct.
Sends a magic link for registered users. There is no error. The letter is coming.

The problem is only with the registration of new users.

Version from marketplace Digitalocean.

![Снимок экрана 2020-02-16 в 6 11 07](https://user-images.githubusercontent.com/44556749/74598494-b2449b80-5083-11ea-9273-0cf769e02ac2.png)

**Comment by antomal** [comment]
Sorry! The problem is resolved. Everything works!

**Comment by savsofts** [comment]
Getting same error.
How did you fix this issue?
