### ISSUE TITLE
Theme demo post prompt has version number hardcoded

### ISSUE THREAD

**Issue by llakssz** [TryGhost/Ghost-CLI#1116]
https://github.com/TryGhost/Ghost-CLI/blob/c3c7a55316df90fac0a5292291df67399df0377e/lib/tasks/major-update/ui.js#L50
https://github.com/TryGhost/Ghost-CLI/blob/c3c7a55316df90fac0a5292291df67399df0377e/lib/tasks/major-update/ui.js#L90

I guess just change it to:
'Visit the demo post at ${chalk.cyan(demoLink)} to see how your theme looks like.' ~~in Ghost 2.0~~

**Comment by acburdine** [comment]
good catch - I'll make sure to get that updated.
