### ISSUE TITLE
Error on ghost install local

### ISSUE THREAD

**Issue by cyrano007** [TryGhost/Ghost-CLI#1120]
after install the ghost CLI
`sudo npm install ghost-cli -g
/usr/local/bin/ghost -> /usr/local/lib/node_modules/ghost-cli/bin/ghost
+ ghost-cli@1.13.1
updated 1 package in 9.802s`

i become follow error 

`Debug Information:
    OS: LinuxMint, v19.1
    Node Version: v12.16.1
    Ghost Version: 3.9.0
    Ghost-CLI Version: 1.13.1
    Environment: development
    Command: 'ghost install local'
Message: Ghost process exited with code: null
Stack: Error: Ghost process exited with code: null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:56:24)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`

Can you help me ?

**Comment by aidenmitchell** [comment]
Try ```sudo npm install ghost-cli@latest -g```

**Comment by mrusme** [comment]
Please find a possible solution (or at least some hints on how to further debug this) in #1103.

**Comment by vikaspotluri123** [comment]
@zaxayn a new version of the CLI has been released that includes a better error message. Can you please update your CLI, try installing Ghost again, and sharing the output?
