### ISSUE TITLE
Ability to export JSON file through CLI in addition to admin interface

### ISSUE THREAD

**Issue by aidenmitchell** [TryGhost/Ghost-CLI#1146]
### Summary

I'd like the ability to export a JSON file of my posts and settings, like you can though the web admin interface, but though the CLI. This would be useful so that it cat be set up as a cron job to have backups automatically or added to a .sh script to be uploaded to a storage service, such as AWS S3.

**Comment by acburdine** [comment]
This is currently possible via the export command: https://github.com/TryGhost/Ghost-CLI/blob/master/lib/commands/export.js

I need to get the import/export commands added to the Ghost-CLI docs page, I'll make a note to do that.

**Comment by aidenmitchell** [comment]
I'm having trouble getting this command to work. I'm trying ```ghost export /var/www/ghost/backups``` , but it's reporting ```'EISDIR: illegal operation on a directory, open '/var/www/ghost/backups''```

```\Debug Information:
    OS: Ubuntu, v18.04.4 LTS
    Node Version: v10.19.0
    Ghost Version: 3.13.1
    Ghost-CLI Version: 1.13.1
    Environment: production
    Command: 'ghost export /var/www/ghost/backups'
An error occurred.
Message: 'EISDIR: illegal operation on a directory, open '/var/www/ghost/backups''

Stack: Error: EISDIR: illegal operation on a directory, open '/var/www/ghost/backups'
Code: EISDIR
Path: /var/www/ghost/backups
```

**Comment by acburdine** [comment]
so the `ghost export` command expects a specific file to write the export to - since you're passing it an existing directory, it can't write the file there.

what _should_ work is `ghost export /var/www/ghost/backup.json`. We could potentially add an improvement to the command where if what you pass is a directory, it autogenerates a filename in that directory and writes it (maybe something like `backup-<timestamp>.json`)

**Comment by aidenmitchell** [comment]
Got it, thanks.

**Comment by aidenmitchell** [comment]
Is there a non-interactive version of ```ghost export```? I'm trying to write a script to run ```ghost export``` but it's hand to script because it expects a user to enter the admin email and password.
