### ISSUE TITLE
failed to start Ghost server

### ISSUE THREAD

**Issue by arun312** [TryGhost/Ghost-CLI#1184]
We primarily use GitHub as an issue tracker.

For usage and support questions, or ideas & feature requests please check out [our forum](https://forum.ghost.org).

Alternatively, check out these resources below. Thanks! 😁.

- [Ghost-CLI docs](https://ghost.org/docs/api/ghost-cli/)
- [Forum Support](https://forum.ghost.org/c/help)
- [Ideas](https://forum.ghost.org/c/Ideas)
- [Contributing Guide](https://ghost.org/docs/concepts/contributing/)
- [Self-hoster Docs](https://ghost.org/docs/install/ubuntu/)

**Comment by acburdine** [comment]
@arun312 there's nothing we can really do to debug this issue without more information 😕, so I'm going to close this.

If you can update your comment to provide more information, then we can reopen & investigate if necessary.
