### ISSUE TITLE
Support for CLI installation in Node 13.x

### ISSUE THREAD

**Issue by jackHedaya** [TryGhost/Ghost-CLI#1199]
### Summary

Unable to install `ghost-cli` locally using yarn. However, I was able to install with npm.

### Steps to Reproduce

1. `yarn global add ghost-cli@latest`

### Log 

```
error ghost-cli@1.13.1: The engine "node" is incompatible with this module. Expected version "^8.16.0 || ^10.13.0 || ^12.10.0". Got "13.12.0"
error Found incompatible module.
```

### Environment
OS: macOS Catalina
Yarn Version: 1.22.4
Node Version: 13.12.0

**Comment by vikaspotluri123** [comment]
@jackHedaya That's expected, only node LTS is supported. https://ghost.org/faq/node-versions/

**Comment by jackHedaya** [comment]
Ah that’s my bad. Might I ask why the installation would require a different version as opposed to solely the use of Ghost?

**Comment by vikaspotluri123** [comment]
It looks like there just hasn't been a new release of the CLI in a bit - the CLI's node engines in master line up with the core

**Comment by jackHedaya** [comment]
Gotcha, looks like there's no real issue here. I'll close now.

**Comment by vikaspotluri123** [comment]
@jackHedaya version 1.14.0 was released; the engines should be in sync now 😃
