### ISSUE TITLE
Improve IPC messaging to make errors more visible

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#1201]
**Problem:**

Frequently, Ghost fails to start with nothing more than an error code to show for itself, and the error code is often just "0". This makes debugging really difficult, people new to the tool don't have a chance, and even when they do make it to the forum it's really hard for seasoned Ghost-CLI users to determine where to go looking.

Here's a handful of examples from issues and the forum:
- https://github.com/TryGhost/Ghost-CLI/issues/1103
- https://github.com/TryGhost/Ghost-CLI/issues/1120
- https://github.com/TryGhost/Ghost-CLI/issues/1070
- https://forum.ghost.org/t/ghost-installation-rebuilding-issues/11443
- https://forum.ghost.org/t/latest-ghost-wont-start-openbsd-6-7/

This seems to happen mostly on local installs, but I'm not convinced that's entirely true. Other commands can sometimes surface a partial error:

- https://github.com/TryGhost/Ghost-CLI/issues/1150
- https://forum.ghost.org/t/attempt-to-upgrade-2-to-3-fails/13170

But still not enough to debug an issue.

**Background:**

Whenever anyone runs `ghost start` either manually, or as the last step in `ghost install`, 3 separate processes are created:

- `ghost start`
- `ghost run` 
- `node index` (Ghost itself)

Often, the error happens in Ghost or the `ghost run` command, and isn't passed up. Therefore `ghost run -D` can sometimes show the error, but sometimes you have to go digging in the Ghost logs!

**Solution:**

We need to make sure that any and all relevant error messages are passed to the top level process and displayed, no matter which process they occurred in.

Ideally we also need to output which process the error occurred in, and if possible the debug info from _that_ process. 

Ghost was recently updated so that it passes additional debug info: https://github.com/TryGhost/Ghost/blob/21d38b2d37d9dd1797a40f5d14bfa600b183581f/core/server/ghost-server.js#L346

The `ghost run` process may need a similar update to provide some more debug info. 

This is a somewhat nebulous and hard-to-reproduce problem, but we see it all the time. I think the first step is to assess how the IPC is working, make sure errors are passed around, and then iterate on improving the output.

**Comment by vikaspotluri123** [comment]
The change that was published over the weekend seems to be on the right path. If people are still running into the `exit code 0` issue, we'll hopefully have more debug information to improve the CLI.

More references:

https://forum.ghost.org/t/ghost-error-occurred-knex-sqlite/14669

**Comment by daniellockyer** [comment]
We also randomly see this in the Ghost-CLI tests in Core. I've updated the repo to use the latest version and asked the team to keep their eye out for any instances.

**Comment by ErisDS** [comment]
@daniellockyer what do you mean by "this"?

**Comment by daniellockyer** [comment]
@ErisDS The error code 0 issue. Wanted to weigh in here to say we've also seen it and the error output addition coming from this issue should be useful.

From https://github.com/TryGhost/Ghost/pull/11862/checks?check_run_id=716617549 (this log might not last forever so pic below. Unable to download the log mentioned):

![2020-05-28-15:50:02](https://user-images.githubusercontent.com/964245/83156986-fe7b8f00-a0fa-11ea-92cd-2aa87d8a71af.png)
