### ISSUE TITLE
Improve Binary Dependency Check

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#1205]
Upgrading node is a common usecase, as a fact of how this works, it blows away binary dependencies and they have to be re-installed.

We have a binary dependency check in place that tries to detect if node changed, but this isn't catching all cases.

We need to catch the case that the binaries are out of date some how, and show the same error:

ref: https://forum.ghost.org/t/ghost-error-occurred-knex-sqlite/14669

**Comment by acburdine** [comment]
this might be a duplicate of #760 - had the idea awhile back to add a `yarn check` call to `ghost doctor` to catch these types of cases. That said, according to the yarn docs, yarn check is deprecated and will be removed in yarn 2, so perhaps there's a better way to run this check.

One alternative solution might be to use the `node-version` property in the instance config - if the node version changes on `ghost start`, automatically re-run `yarn install` (might have to add some additional flags to the command) prior to starting Ghost.
