### ISSUE TITLE
ERR: Ghost install

### ISSUE THREAD

**Issue by xinchen37** [TryGhost/Ghost-CLI#1222]
ghost-team-blog>ghost install local
√ Checking system Node.js version
√ Checking current folder permissions
√ Checking memory availability
√ Checking for latest Ghost version
√ Setting up install directory
× Downloading and installing Ghost v3.18.1
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@3.18.1: The engine "cli" appears to be invalid.
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@0.5.28"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@0.5.28"
error An unexpected error occurred: "C:\\Users\\Cdsj8j\\AppData\\Local\\Yarn\\Cache\\v6\\npm-express-brute-1.0.1-9f36d107fe34e40a682593e39bffcc53102b5335-integrity\\node_modules\\express-brute\\.yarn-metadata.json: Unexpected end of JSON input".

yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "C:\\bicheng\\ghost-team-blog\\versions\\3.18.1\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1

Debug Information:
    OS: Microsoft Windows 10 רҵ��, v10.0.19041
    Node Version: v12.17.0
    Ghost-CLI Version: 1.14.1
    Environment: development
    Command: 'ghost install local'

**Comment by vikaspotluri123** [comment]
@xinchen37 it looks like your cache might be corrupted. Please run `ghost buster` and then re-try installing Ghost. If you're still having trouble, please ask on the [forum](https://forum.ghost.org) as you're more likely to get a response 😄
