### ISSUE TITLE
Cannot read property 'connection' of undefined

### ISSUE THREAD

**Issue by josephgeis** [TryGhost/Ghost-CLI#1227]
I tried to install Ghost locally, but it kept giving me an error.
```
Debug Information:
    OS: Ubuntu, v20.04 LTS
    Node Version: v12.18.0
    Ghost Version: 3.19.0
    Ghost-CLI Version: 1.14.1
    Environment: development
    Command: 'ghost install local'
Message: Ghost process exited with code: null
Stack: Error: Ghost process exited with code: null
    at ChildProcess.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/ghost-cli/lib/utils/local-process.js:68:24)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```
`ghost doctor` found nothing.

Here is the output of `ghost run`.
```
/home/joseph/Documents/ghost-dev/versions/3.19.0/core/shared/config/utils.js:103
        delete database.connection.host;
                        ^

TypeError: Cannot read property 'connection' of undefined
    at exports.Provider.sanitizeDatabaseProperties (/home/joseph/Documents/ghost-dev/versions/3.18.0/core/shared/config/utils.js:103:25)
    at Object.loadNconf (/home/joseph/Documents/ghost-dev/versions/3.18.0/core/shared/config/index.js:52:11)
    at Object.<anonymous> (/home/joseph/Documents/ghost-dev/versions/3.18.0/core/shared/config/index.js:83:27)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/joseph/Documents/ghost-dev/versions/3.18.0/core/shared/sentry.js:1:16)
```

**Comment by vikaspotluri123** [comment]
Hey @juniorRubyist :wave:

do you have a `config.development.json` file? If so, can you share it, redacting any sensitive information? It seems that there might be something wrong with the config 😬

**Comment by juniorRubyist** [comment]
```
{
  "url": "http://localhost:2368/",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  },
  "database": {
    "client": "sqlite3",
    "connection": {
      "filename": "/home/joseph/Documents/ghost-dev/content/data/ghost-local.db"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "local",
  "paths": {
    "contentPath": "/home/joseph/Documents/ghost-dev/content"
  }
}
```

**Comment by acburdine** [comment]
@juniorRubyist what happens if you run `ghost run -D`...`ghost run` will default to trying to load a production config

**Comment by juniorRubyist** [comment]
Running `ghost run` with the `-D` flag makes it spin up. There still appears to be a bug though where it doesn’t look for it by default.

**Comment by juniorRubyist** [comment]
Also, `ghost start -D` does not work.

**Comment by ErisDS** [comment]
Sounds like the same problem as this: https://forum.ghost.org/t/typeerror-cannot-read-property-connection-of-undefined/15334/5 where the config files are not being kept in the right location?

**Comment by daniellockyer** [comment]
I hit this error today when trying to restart a stopped local Ghost instance.

```
0 neo@ariel /tmp/ghost2 λ ghost install --local
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v3.28.0
✔ Finishing install process
✔ Configuring Ghost
✔ Setting up instance
✔ Starting Ghost

Ghost uses direct mail by default. To set up an alternative email method read our docs at https://ghost.org/docs/concepts/config/#mail

------------------------------------------------------------------------------

Ghost was installed successfully! To complete setup of your publication, visit:

    http://localhost:2368/ghost/

0 neo@ariel /tmp/ghost2 λ ghost stop
✔ Stopping Ghost: ghost-local-2
0 neo@ariel /tmp/ghost2 λ ghost restart
Ghost instance is not running! Starting...
✖ Starting Ghost
A GhostError occurred.

Message:
/tmp/ghost2/versions/3.28.0/core/shared/config/utils.js:103
        delete database.connection.host;
                        ^

TypeError: Cannot read property 'connection' of undefined
    at exports.Provider.sanitizeDatabaseProperties (/tmp/ghost2/versions/3.28.0/core/shared/config/utils.js:103:25)
    at Object.loadNconf (/tmp/ghost2/versions/3.28.0/core/shared/config/index.js:52:11)
    at Object.<anonymous> (/tmp/ghost2/versions/3.28.0/core/shared/config/index.js:83:27)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/ghost2/versions/3.28.0/core/shared/sentry.js:1:16)


Debug Information:
    OS: Arch Linux, vunknown
    Node Version: v12.18.0
    Ghost Version: 3.28.0
    Ghost-CLI Version: 1.14.1
    Environment: production
    Command: 'ghost restart'

Additional log info available in: /home/neo/.ghost/logs/ghost-cli-debug-2020-08-10T12_09_22_000Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/api/ghost-cli/ for troubleshooting.
```

**Comment by acburdine** [comment]
@daniellockyer my guess is the error you ran into is based on `ghost restart` defaulting to try and start in production mode. If there's no production configuration file, Ghost will ultimately throw the error you saw. Fix is to run `ghost restart -D` to force Ghost-CLI to run Ghost in development mode.

**Comment by ErisDS** [comment]
@acburdine there's definitely something weird going on here.

For a local install on a mac the commands all work as expected without having to specify -D. 

It seems local installs on linux behave differently?

**Comment by acburdine** [comment]
@ErisDS that's a possibility - there's a lot of `platform === 'linux'` code that is used to enable/disable certain things. I'll have a look to see if something's interfering with the environment check.

Only other thing I can think of outside of a CLI issue is if there happens to be an empty `config.production.json` file in the Ghost installation directory.

**Comment by Unknow1002** [comment]
> I hit this error today when trying to restart a stopped local Ghost instance.
> 
> ```
> 0 neo@ariel /tmp/ghost2 λ ghost install --local
> ✔ Checking system Node.js version
> ✔ Checking current folder permissions
> ✔ Checking memory availability
> ✔ Checking for latest Ghost version
> ✔ Setting up install directory
> ✔ Downloading and installing Ghost v3.28.0
> ✔ Finishing install process
> ✔ Configuring Ghost
> ✔ Setting up instance
> ✔ Starting Ghost
> 
> Ghost uses direct mail by default. To set up an alternative email method read our docs at https://ghost.org/docs/concepts/config/#mail
> 
> ------------------------------------------------------------------------------
> 
> Ghost was installed successfully! To complete setup of your publication, visit:
> 
>     http://localhost:2368/ghost/
> 
> 0 neo@ariel /tmp/ghost2 λ ghost stop
> ✔ Stopping Ghost: ghost-local-2
> 0 neo@ariel /tmp/ghost2 λ ghost restart
> Ghost instance is not running! Starting...
> ✖ Starting Ghost
> A GhostError occurred.
> 
> Message:
> /tmp/ghost2/versions/3.28.0/core/shared/config/utils.js:103
>         delete database.connection.host;
>                         ^
> 
> TypeError: Cannot read property 'connection' of undefined
>     at exports.Provider.sanitizeDatabaseProperties (/tmp/ghost2/versions/3.28.0/core/shared/config/utils.js:103:25)
>     at Object.loadNconf (/tmp/ghost2/versions/3.28.0/core/shared/config/index.js:52:11)
>     at Object.<anonymous> (/tmp/ghost2/versions/3.28.0/core/shared/config/index.js:83:27)
>     at Module._compile (internal/modules/cjs/loader.js:1138:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
>     at Module.require (internal/modules/cjs/loader.js:1026:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/tmp/ghost2/versions/3.28.0/core/shared/sentry.js:1:16)
> 
> 
> Debug Information:
>     OS: Arch Linux, vunknown
>     Node Version: v12.18.0
>     Ghost Version: 3.28.0
>     Ghost-CLI Version: 1.14.1
>     Environment: production
>     Command: 'ghost restart'
> 
> Additional log info available in: /home/neo/.ghost/logs/ghost-cli-debug-2020-08-10T12_09_22_000Z.log
> 
> Try running ghost doctor to check your system for known issues.
> 
> You can always refer to https://ghost.org/docs/api/ghost-cli/ for troubleshooting.
> ```

You get this error cause you didn't put () at `delete database.connection.host;`.

**Comment by bennmaina** [comment]
> > I hit this error today when trying to restart a stopped local Ghost instance.
> > ```
> > 0 neo@ariel /tmp/ghost2 λ ghost install --local
> > ✔ Checking system Node.js version
> > ✔ Checking current folder permissions
> > ✔ Checking memory availability
> > ✔ Checking for latest Ghost version
> > ✔ Setting up install directory
> > ✔ Downloading and installing Ghost v3.28.0
> > ✔ Finishing install process
> > ✔ Configuring Ghost
> > ✔ Setting up instance
> > ✔ Starting Ghost
> > 
> > Ghost uses direct mail by default. To set up an alternative email method read our docs at https://ghost.org/docs/concepts/config/#mail
> > 
> > ------------------------------------------------------------------------------
> > 
> > Ghost was installed successfully! To complete setup of your publication, visit:
> > 
> >     http://localhost:2368/ghost/
> > 
> > 0 neo@ariel /tmp/ghost2 λ ghost stop
> > ✔ Stopping Ghost: ghost-local-2
> > 0 neo@ariel /tmp/ghost2 λ ghost restart
> > Ghost instance is not running! Starting...
> > ✖ Starting Ghost
> > A GhostError occurred.
> > 
> > Message:
> > /tmp/ghost2/versions/3.28.0/core/shared/config/utils.js:103
> >         delete database.connection.host;
> >                         ^
> > 
> > TypeError: Cannot read property 'connection' of undefined
> >     at exports.Provider.sanitizeDatabaseProperties (/tmp/ghost2/versions/3.28.0/core/shared/config/utils.js:103:25)
> >     at Object.loadNconf (/tmp/ghost2/versions/3.28.0/core/shared/config/index.js:52:11)
> >     at Object.<anonymous> (/tmp/ghost2/versions/3.28.0/core/shared/config/index.js:83:27)
> >     at Module._compile (internal/modules/cjs/loader.js:1138:30)
> >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
> >     at Module.load (internal/modules/cjs/loader.js:986:32)
> >     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
> >     at Module.require (internal/modules/cjs/loader.js:1026:19)
> >     at require (internal/modules/cjs/helpers.js:72:18)
> >     at Object.<anonymous> (/tmp/ghost2/versions/3.28.0/core/shared/sentry.js:1:16)
> > 
> > 
> > Debug Information:
> >     OS: Arch Linux, vunknown
> >     Node Version: v12.18.0
> >     Ghost Version: 3.28.0
> >     Ghost-CLI Version: 1.14.1
> >     Environment: production
> >     Command: 'ghost restart'
> > 
> > Additional log info available in: /home/neo/.ghost/logs/ghost-cli-debug-2020-08-10T12_09_22_000Z.log
> > 
> > Try running ghost doctor to check your system for known issues.
> > 
> > You can always refer to https://ghost.org/docs/api/ghost-cli/ for troubleshooting.
> > ```
> 
> You get this error cause you didn't put () at `delete database.connection.host;`.


I had the same error on restart. Solved it by running `ghost start`

**Comment by raghavatreya** [comment]
how to find location of config.development.json


I am getting the error 
 ghost restart
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                     The current Node.js version (10.24.1) has reached end-of-life status.                      │
│Ghost-CLI will drop support for this Node.js version in an upcoming release, please update your Node.js version.│
│                                 See https://ghost.org/docs/faq/node-versions/.                                 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Ghost instance is not running! Starting...
✖ Starting Ghost
A GhostError occurred.

Message: 
TypeError: Cannot read property 'connection' of undefined
    at exports.Provider.sanitizeDatabaseProperties (/ghost-app/ghost/versions/4.4.0/core/shared/config/utils.js:103:25)
    at Object.loadNconf (/ghost-app/ghost/versions/4.4.0/core/shared/config/index.js:54:11)
    at Object.<anonymous> (/ghost-app/ghost/versions/4.4.0/core/shared/config/index.js:93:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)


Debug Information:
    OS: Ubuntu, v18.04.2 LTS
    Node Version: v10.24.1
    Ghost Version: 4.4.0
    Ghost-CLI Version: 1.17.3
    Environment: production
    Command: 'ghost restart'

Additional log info available in: /home/ghost-user/.ghost/logs/ghost-cli-debug-2021-07-17T02_22_03_233Z.log
