### ISSUE TITLE
Error: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  useradd --system --user-group ghost

### ISSUE THREAD

**Issue by AhsanE** [TryGhost/Ghost-CLI#1230]
After running ghost setup

**Comment by vikaspotluri123** [comment]
@AhsanE can you please post screenshots and logs from the installation? It's really hard to debug issues if we only get one line of output 😉

**Comment by ErisDS** [comment]
@AhsanE we have a bug report template, if you wish to report a bug please fill it out else we cannot be expected to provide any help.

Closing this as there's nothing anyone can do, and starting from scratch with the template is better than trying to back fill this.
