### ISSUE TITLE
Ghost start and doctor fails permission checks but ghost run works fine

### ISSUE THREAD

**Issue by planetahuevo** [TryGhost/Ghost-CLI#1249]
### Steps to Reproduce

I am following this guide:
https://blog.runcloud.io/ghost/

And everything works fine and ghost start after install. 
I can login, access everything and upload and activate a neew theme. 
Everything working fine.

The problem is that ghost doctor detects problems on the folders, even if there is no problems.
So, if I run ghost stop, then I cannot longer run ghost start, because it raise the permissions issues, that are not real, so I cannot fix them.

Running ghost run allow the server to work again. 

How can run ghost start without checking the folders until this is fixed?

Thanks

### Log file
This is the log after running ghost install
```
✔ Setting up instance
+ sudo chown -R ghost:ghost /home/userghost/webapps/randomname/content
✔ Setting up "ghost" system user
ℹ Setting up "ghost" mysql user [skipped]
? Do you wish to set up Nginx? No
ℹ Setting up Nginx [skipped]
Nginx setup task was skipped, skipping SSL setup
ℹ Setting up SSL [skipped]
? Do you wish to set up Systemd? Yes
✔ Creating systemd service file at /home/userghost/webapps/randomname/system/files/ghost_randomname.service
+ sudo ln -sf /home/userghost/webapps/randomname/system/files/ghost_randomname.service /lib/systemd/system/ghost_randomname.service
+ sudo systemctl daemon-reload
✔ Setting up Systemd
+ sudo systemctl is-active ghost_randomname
? Do you want to start Ghost? Yes
+ sudo systemctl start ghost_randomname
+ sudo systemctl is-enabled ghost_randomname
✔ Starting Ghost
```
This is ls -la
```
drwxr-xr-x+ 5 userghost userghost   8 Jul 13 01:59 .
drwxr-xr-x  3 root       root         3 Jul 13 00:40 ..
-rw-rw-r--+ 1 userghost userghost  97 Jul 13 02:01 .ghost-cli
-rw-rw-r--+ 1 userghost userghost 556 Jul 13 01:59 config.production.json
drwxrwxr-x+ 8 ghost      ghost        8 Jul 13 01:58 content
lrwxrwxrwx  1 userghost userghost  64 Jul 13 01:58 current -> /home/userghost/webapps/randomname/versions/3.24.0
drwxrwxr-x+ 3 userghost userghost   3 Jul 13 01:59 system
drwxrwxr-x+ 3 userghost userghost   3 Jul 13 01:58 versions
```
### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

Debug Information:
    OS: Ubuntu, v20.04 LTS
    Node Version: v12.18.2
    Ghost Version: 3.24.0
    Ghost-CLI Version: 1.14.1
    Environment: production
    Command: 'ghost doctor'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by ErisDS** [comment]
I'm confused, what's the error you're seeing?

**Comment by planetahuevo** [comment]
Oh, I pasted everything but the error... :O 
Sorry for that. 
The error was that the "ghost doctor" cannot read the folders so it consider that the permissions where not right.
I do not have the capture anymore. 
This morning I was testing it again and it seems that the problem is that RunCloud put the webapp files on the home of the user, and reading your docs again found this:
https://ghost.org/docs/install/ubuntu/#install-ghost
"Note: Installing Ghost in the /root or home/<user> directories results in a broken setup. Always use a custom directory with properly configured permissions."

So, it seems Runcloud guide was never tested by them. 
Runcloud support suggested to use the same "ghost" username for the system, but that makes no sense from a security point of view. 

So, we can close this and we just need to consider that Runcloud is not compatible with Ghost at the moment because they use home as the location of the websites.

**Comment by ErisDS** [comment]
Ok cool, thanks for the update!

**Comment by planetahuevo** [comment]
No problem! :) 
We could look further into why the system mark it as "wrong" when doctor checks but then the website works fine on "run", but I am not sure if it is a priority for you. 
Happy to give you more info if you are interested.
