### ISSUE TITLE
Unable to start ghost

### ISSUE THREAD

**Issue by AKmoex** [TryGhost/Ghost-CLI#1253]
When I try `ghost start`，An error occurred
Error：
```
Found a development config but not a production config, running in development mode instead
√ Checking current folder permissions
√ Validating config
√ Checking memory availability
√ Checking binary dependencies
× Starting Ghost: ghost-local
A GhostError occurred.

Message:
D:\NodeProject\myGhost\versions\3.25.0\node_modules\knex\lib\client.js:236
      throw new Error(`${message}\n${e.message}`);
      ^

Error: Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack: .............
```
`ghost doctor`:
```
√ Checking system Node.js version
√ Checking current folder permissions
√ Validating config
√ Checking memory availability
√ Checking binary dependencies
```

I don’t know what’s going on. I’ve tried many methods but it still hasn’t been solved, thank you。

**Comment by acburdine** [comment]
@AKmoex you might try running `ghost update --force` - that will re-install the most recent version of Ghost, as well as any missing dependencies. That should hopefully force sqlite to install again, which should fix your issue.

**Comment by nteinert2005** [comment]
Having the same issues. Tried `ghost update --force` and also `npm uninstall ghost-cli && npm i ghost-cli`. Still not working. Any help would be helpful.

**Comment by shayangraph** [comment]
after writting ghost update --force
show this massege
Found a development config but not a production config, running in development mode instead
what is this
