### ISSUE TITLE
ghost update hangs on Step 5

### ISSUE THREAD

**Issue by aidenmitchell** [TryGhost/Ghost-CLI#1256]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in our forum: https://forum.ghost.org 👫.

Docs: https://ghost.org/docs/ 📖.

Please be aware that the team behind the Ghost CLI only supports the recommended stack: https://github.com/TryGhost/Ghost-cli#recommended-stack.

### Summary

When running ```ghost update```, the script hangs on ```Step 5 > Building fresh packages```, server resources max out and blog goes down,

### Steps to Reproduce

1. Run ```ghost update```

### Log file

No errors were thrown, therefore no log path was indicated.

### Technical details

No error was thrown; I've filled this in to the best of my ability.

* OS: Ubuntu 18.04
* Node Version: v10.21.0
* Ghost-CLI Version: 1.14.1
* Environment: N/A
* Command: ```ghost update```

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [ ] Attached log file 
where can I find update logs?
- [x] Provided technical details incl. operating system

**Comment by acburdine** [comment]
@aidenmitchell most likely this is due to the yarn install process running out of memory. What may be necessary is for you to stop your running blog, do the update, and then start your blog again. Or, you can try increasing the RAM/swap space on your server, which may give the server enough resources to do the update with the blog still running.

**Comment by aidenmitchell** [comment]
Ok, I'll try that next version. This didn't used to be an issue, but stopping, updating, and starting is probably better anyway.

**Comment by acburdine** [comment]
Going to close this issue as there's not much we can really do in the CLI to prevent this. We do have a memory check that does its best to warn you about the system not having enough resources before doing an operation like an update or start, but knowing how much memory is needed is unfortunately not an exact science 😕 

If you continue to run into issues, please drop by our [forum](https://forum.ghost.org). If we find there's something we can do in the CLI to help fix this issue, then we can reopen.
