### ISSUE TITLE
'ghost install local' not working

### ISSUE THREAD

**Issue by fredrikaurdal** [TryGhost/Ghost-CLI#1257]
I have installed Ghost locally with `npm install ghost-cli@latest -g`.

However, when I run `ghost install local` I get the following error:

```
ghost : The term 'ghost' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is corre
ct and try again.    
At line:1 char:1     
+ ghost install local
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (ghost:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I'm running Windows 10 and Node v12.16.3.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
@fredrikaurdal it looks like you have an issue with your [path](https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them). You'll need to find the npm bin path (`npm bin -g`) and add it to your Windows Path (see something like [this](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) article).

I'm going to close this as it's not an issue with the Ghost CLI. If you have any questions or run into any issues, please stop by the [forum](https://forum.ghost.org) 😄

**Comment by oeh77** [comment]
1. Add "C:\Program Files\nodejs\node.exe”  to the user variable PATH
2. open new terminal 
3. use the command “ghost install local” after installed globally.
4. it will work
5. cd inside the folder then use these commands :
                                               ghost stop to stop Ghost
ghost start to start Ghost
ghost log views logs
ghost ls to list all running Ghost blogs
Run ghost help for a list of available commands, or explore the full [Ghost-CLI documentation](https://ghost.org/docs/api/ghost-cli/).
