### ISSUE TITLE
[Feature] Use `node` as primary alias instead of `nodejs`

### ISSUE THREAD

**Issue by sooxt98** [TryGhost/Ghost-CLI#1276]
Which help to solve `Could not communicate with Ghost` & `Ghost start stuck forever problem`

The problem is there's two diff node in the machine, one is nvm's one another is default one; but ghost-cli tend to use the system default one instead of using `node` alias

https://forum.ghost.org/t/getting-error-when-trying-to-upgrade-to-ghost-3-x/13636/2

**Comment by vikaspotluri123** [comment]
@sooxt98 hey 👋🏾 

We already use `node` as the alias where necessary. The issue people are seeing is their node path changing for one reason or another; Ghost needs to store the executable path to `node` for process managers.

There's some work in progress to detect when the node executable path changes, which should alleviate some of the cryptic messages some users are seeing.

As we already do this, I'm going to go ahead and close this issue for now 😄
