### ISSUE TITLE
ghost cli set admin url doesn't work 

### ISSUE THREAD

**Issue by mlicheng** [TryGhost/Ghost-CLI#1281]
### Summary
ghost cli set admin url doesn't work 
the ghost command says its setting successful, but when went to the url i was setted it report a http error 404

### Steps to Reproduce
```
Tom@bogon ghost-local : ghost config set admin-url http://localhost:2368/admin
Successfully set 'admin-url' to 'http://localhost:2368/admin'
```
### Debug Information:
    OS: Mac OS X, v10.15.6
    Node Version: v10.18.1
    Ghost Version: 3.30.1
    Ghost-CLI Version: 1.14.1
    Environment: production
    Command: 'ghost doctor'

## Bug submission checklist
- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [ ] Attached log file
- [x] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
If you're looking to set the admin URL, you need to use `ghost config set admin.url {url}`. You can't change currently change the admin path. Here are the docs relating to that: https://ghost.org/docs/concepts/config/#admin-url

If you have any more questions, please create a post over on the [forum](https://forum.ghost.org) :smile:
