### ISSUE TITLE
Message: Command failed: yarn install --no-emoji --no-progress

### ISSUE THREAD

**Issue by EmmaNguyen** [TryGhost/Ghost-CLI#1335]
Hi,

I am newbie Ghost trying to run the first basic command `ghost install local` but it does not work. 

Please help me review this weird bug. Below is the log & thank you.

### Log file

```
Message: Command failed: yarn install --no-emoji --no-progress
Usage: yarn [options]

yarn: error: no such option: --no-emoji


Exit code: 2

--------------- stderr ---------------
Usage: yarn [options]

yarn: error: no such option: --no-emoji

```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

Debug Information:
    OS: Ubuntu, v20.04.1 LTS
    Node Version: v10.19.0
    Ghost-CLI Version: 1.15.2
    Environment: development
    Command: 'ghost install local'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [ v ] Tried to find help in the forum & docs
- [ v ] Checked for existing issues
- [ v ] Attached log file
- [ v ] Provided technical details incl. operating system

**Comment by acburdine** [comment]
@EmmaNguyen Apologies for the delay in responding to this - can you run `yarn --version` and post the output? My suspicion is that you're running either a newer or older version of Yarn that doesn't support that option, but it'd be helpful to know which specific version so I can see what the fix might be on the Ghost-CLI side.

**Comment by WatsonJH** [comment]
Hi,

I have the same issue.
I tried to update Ghost from 3.40.5 to the latest version (3.41.3), but I encountered an error.

I first ran `sudo npm install -g ghost-cli@latest` to update Ghost-CLI, then I ran `ghost update` while being in the Ghost folder as usual.

And I ended up with the following:

> sudo systemctl is-active ghost_ghost-site
> 
> - Checking system Node.js version
> - Ensuring user is not logged in as ghost user
> - Checking if logged in user is directory owner
> - Checking current folder permissions
> - Checking folder permissions
> - Checking file permissions
> - Checking content folder ownership
> - Checking memory availability
> - Checking free space
> - Checking for available migrations
> - Checking for latest Ghost version
> 
> Fixed default urls for checkout session - Rishabh Garg
> View the changelogs for full details:
> 
> Ghost - Comparing 3.41.2...3.41.3 · TryGhost/Ghost · GitHub
> Ghost-Admin - Comparing 3.41.2...3.41.3 · TryGhost/Admin · GitHub
> :heavy_check_mark: Fetched release notes
> :heavy_multiplication_x: Downloading and updating Ghost to v3.41.3
> A ProcessError occurred.
> 
> Message: Command failed: yarn install --no-emoji --no-progress
> Usage: yarn [options]
> 
> yarn: error: no such option: --no-emoji
> 
> Exit code: 2
> 
> Debug Information:
> OS: Ubuntu, v20.04.2 LTS
> Node Version: v10.19.0
> Ghost Version: 3.40.5
> Ghost-CLI Version: 1.15.3
> Environment: production
> Command: ‘ghost update’
> 
> Additional log info available in: /home/ghostuser/.ghost/logs/ghost-cli-debug-2021-02-01T20_32_23_186Z.log
> 
> Try running ghost doctor to check your system for known issues.

I ran ghost doctor, but it did not help, it passes all tests.
This is the log file produced after the failure:

> Debug Information:
> OS: Ubuntu, v20.04.2 LTS
> Node Version: v10.19.0
> Ghost Version: 3.40.5
> Ghost-CLI Version: 1.15.3
> Environment: production
> Command: ‘ghost update’
> Message: Command failed: yarn install --no-emoji --no-progress
> Usage: yarn [options]
> 
> yarn: error: no such option: --no-emoji
> 
> Exit code: 2
> 
> --------------- stderr ---------------
> Usage: yarn [options]
> 
> yarn: error: no such option: --no-emoji

I tried allowing more RAM to the VM but not luck.

**Comment by kevinansfield** [comment]
> yarn --version
> 0.32+git

This is a _really_ old version and most likely the problem. Can you try updating to 1.22.5? You'll probably need to configure the yarn package repository first https://classic.yarnpkg.com/en/docs/install#debian-stable

**Comment by WatsonJH** [comment]
Installing following your link fixed the issue. I do not know why I did not encounter it prior to this specific update nor why Ubuntu did not install the latest version.

Thank you for your help.

**Comment by acburdine** [comment]
I'll do some digging - Ghost-CLI _should_ be installing the right version of `yarn`, as well as using it, but perhaps there's something we need to fix to ensure we use the version of yarn that the CLI installs and not any other version on the system.

**Comment by chnthkksn** [comment]
I had the same issue and downgraded node to 14. Now it's working fine.
