### ISSUE TITLE
ghost update problem

### ISSUE THREAD

**Issue by mrneilypops** [TryGhost/Ghost-CLI#136]
trying to upgrade to 1.0.0-alpha.10 from 1.0.0-alpha.09  but get the following error with 'ghost update' in my ghost folder
` expecting an array or an iterable object but got [object Null]`

Linux Ubuntu 16.04 LTS 64-bit
ghost-cli@1.0.0-alpha.9 
node v4.2.6

**Comment by acburdine** [comment]
@mrneilypops I'm not sure exactly what caused this in the first place, but I've throughly tested the update command after the large refactor I did of the CLI - it should work in the next version :smile:

**Comment by mrneilypops** [comment]
Thanks...standing by...

**Comment by acburdine** [comment]
@mrneilypops Refactor is released with Ghost 1.0.0-alpha.10
