### ISSUE TITLE
ProcessError during installation using ghost-cli

### ISSUE THREAD

**Issue by farshid2** [TryGhost/Ghost-CLI#1361]
Hello,

I needed to ask for your help with the error message I receive when trying to install ghost.

Here are the message details:

 Checking logged in user/ghost/test$ ghost install
✔ Checking current folder permissions
✔ Checking system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking free space
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v3.40.2
A ProcessError occurred.

Message: spawn yarn ENOENT
Exit code: ENOENT

Debug Information:
    OS: Ubuntu, v20.04.1 LTS
    Node Version: v10.19.0
    Ghost-CLI Version: 1.15.3
    Environment: production
    Command: 'ghost install' 

Can I ask how to resolve this issue?

Many thanks,

**Comment by r0bbie** [comment]
Getting the same issue, all same versions (incl. Ubuntu etc) as above.

**Comment by farshid2** [comment]
Hi,
I have to say for me, this's now resolved. It's a yarn issue and I tried uninstall/reinstall yarn and ghost-cli (plus rebooting) and it's now working.

**Comment by r0bbie** [comment]
Also eventually managed to resolve by instead installing yarn as a .deb package (via instructions at [https://classic.yarnpkg.com/en/docs/install/#debian-stable)](https://classic.yarnpkg.com/en/docs/install/#debian-stable)) then uninstalling/reinstalling Ghost. Weirdly had to run the command to install Ghost twice in a row  before it recognised the "ghost install" command too, but in any case, appears now to be working.

**Comment by farshid2** [comment]
This issue is resolved.
