### ISSUE TITLE
`systemd` does not have permissions to execute `ghost`

### ISSUE THREAD

**Issue by selfagency** [TryGhost/Ghost-CLI#1371]
### Summary

First, my user does not have permission to run `ghost` after installing via `sudo`. 

```
❯ which ghost

❯ sudo which ghost
/usr/bin/ghost
```

`/usr/bin` is in my path:

```
❯ echo $PATH
/home/selfagency/.config/yarn/global/node_modules/.bin /usr/local/go/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin
```

Then, if I change the owner of `/usr/lib/node_modules` from root to my own user, I can run it, but the `systemd` process says it can't find `/usr/bin/ghost`.

Likewise, if I install `ghost-cli` globally, without using `sudo`, I can run it but `systemd` says it can't find `ghost` in my `~/.config/yarn/global` folder because of permissions.

If I try to run `ghost run` from my instance's folder, it says it doesn't have permission to access the `versions/[version_number]/index.js` file.

Yes, I setup a `ghost` user using `ghost setup linux-user`. Yes, I ran `sudo find ./ -type d -exec chmod 00775 {} \;` and `sudo find ./ ! -path "./versions/*" -type f -exec chmod 664 {} \;`. Yes, it passes all the validation checks. But no matter what I do, `ghost` simply will not start. 

### Steps to Reproduce

1. `sudo npm -g i ghost-cli` or `sudo yarn global add ghost-cli`
2. `ghost install`
3. `ghost start`

### Log file

sudo install:

```
Jan 7 19:46:46 selfagency syslog Started Ghost systemd service for blog: jewishworker.
Jan 7 19:46:46 selfagency syslog internal/modules/cjs/loader.js:818
Jan 7 19:46:46 selfagency syslog   throw err;
Jan 7 19:46:46 selfagency syslog   ^
Jan 7 19:46:46 selfagency syslog Error Error: Cannot find module '/usr/bin/ghost'
Jan 7 19:46:46 selfagency syslog     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
Jan 7 19:46:46 selfagency syslog     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
Jan 7 19:46:46 selfagency syslog     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
Jan 7 19:46:46 selfagency syslog     at internal/main/run_main_module.js:17:47 {
Jan 7 19:46:46 selfagency syslog   code: 'MODULE_NOT_FOUND',
Jan 7 19:46:46 selfagency syslog   requireStack: []
Jan 7 19:46:46 selfagency syslog }
Jan 7 19:46:46 selfagency syslog ghost_jewishworker.service: Main process exited, code=exited, status=1/FAILURE
Jan 7 19:46:46 selfagency syslog ghost_jewishworker.service: Failed with result 'exit-code'.
```

user install:

```
Jan 7 20:27:18 selfagency syslog Started Ghost systemd service for blog: jewishworker.
Jan 7 20:27:18 selfagency syslog internal/modules/cjs/loader.js:818
Jan 7 20:27:18 selfagency syslog   throw err;
Jan 7 20:27:18 selfagency syslog   ^
Jan 7 20:27:18 selfagency syslog Error Error: Cannot find module '/home/selfagency/.config/yarn/global/node_modules/.bin/ghost'
Jan 7 20:27:18 selfagency syslog     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
Jan 7 20:27:18 selfagency syslog     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
Jan 7 20:27:18 selfagency syslog     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
Jan 7 20:27:18 selfagency syslog     at internal/main/run_main_module.js:17:47 {
Jan 7 20:27:18 selfagency syslog   code: 'MODULE_NOT_FOUND',
Jan 7 20:27:18 selfagency syslog   requireStack: []
Jan 7 20:27:18 selfagency syslog }
Jan 7 20:27:18 selfagency syslog ghost_jewishworker.service: Main process exited, code=exited, status=1/FAILURE
Jan 7 20:27:18 selfagency syslog ghost_jewishworker.service: Failed with result 'exit-code'.
```

### Technical details

`ghost-cli` never errors out, it just hangs there after failing to start.

* OS: Ubuntu 18.04
* Node Version: 12.20
* Ghost-CLI Version: 1.15.3

## Bug submission checklist

- [X] Tried to find help in the forum & docs
- [X] Checked for existing issues
- [X] Attached log file
- [X] Provided technical details incl. operating system

**Comment by acburdine** [comment]
@selfagency based on this comment:

> Then, if I change the owner of /usr/lib/node_modules from root to my own user, I can run it, but the systemd process says it can't find /usr/bin/ghost.

I think I know what's happening. For some reason the `/usr/lib/node_modules` folder is being created without granting all users of the system read access. What you might try doing is repeating the installation process using globally-installed `ghost-cli` (i.e. via `sudo npm i -g ghost-cli`) and after installation running `sudo chmod -R a+r /usr/lib/node_modules`. Instead of changing the ownership of that directory to your user (which, as you mentioned, breaks the systemd process) it will instead grant all users of the system read access to the directory, which should (I think) fix the problem.

**Comment by selfagency** [comment]
@acburdine thanks! `a+x` did the trick for getting it working for all users, but i'm running into this still when running `ghost start` or `ghost run`:

```
Jan 8 20:35:57 selfagency syslog - Inspecting operating system
Jan 8 20:35:57 selfagency syslog internal/fs/utils.js:269
Jan 8 20:35:57 selfagency syslog     throw err;
Jan 8 20:35:57 selfagency syslog     ^
Jan 8 20:35:57 selfagency syslog Error Error: EACCES: permission denied, open '/mnt/hosting_data/www/jewishworker.org/html/versions/3.40.5/index.js'
Jan 8 20:35:57 selfagency syslog     at Object.openSync (fs.js:462:3)
Jan 8 20:35:57 selfagency syslog     at Object.readFileSync (fs.js:364:35)
Jan 8 20:35:57 selfagency syslog     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1025:18)
Jan 8 20:35:57 selfagency syslog     at Module.load (internal/modules/cjs/loader.js:863:32)
Jan 8 20:35:57 selfagency syslog     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Jan 8 20:35:57 selfagency syslog     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
Jan 8 20:35:57 selfagency syslog     at internal/main/run_main_module.js:17:47 {
Jan 8 20:35:57 selfagency syslog   errno: -13,
Jan 8 20:35:57 selfagency syslog   syscall: 'open',
Jan 8 20:35:57 selfagency syslog   code: 'EACCES',
Jan 8 20:35:57 selfagency syslog   path: '/mnt/hosting_data/www/jewishworker.org/html/versions/3.40.5/index.js'
Jan 8 20:35:57 selfagency syslog }
```

**Comment by selfagency** [comment]
ok, i figured that out. i added the `ghost` user to my own user's group and now it executes properly.
