### ISSUE TITLE
Replace sqlite3 with mysql on local development

### ISSUE THREAD

**Issue by koraylinux** [TryGhost/Ghost-CLI#1373]
Many of us suffering sqlite3 installation on local envoriment so here is a quick solution to replace sqlite3 with mysql. Here's what i did:

1. Installed mariadb and started. I created a database and assigned a user in it with all grants.
2. npm install ghost-cli@latest -g
3. ghost install local

After 3rd step, I encountered usual sqlite3 error and could not start the ghost. Now go ahead the directory where you install ghost and locate the file config.development.json. Open the file and replace the database section with this.

In this example, i used ghostuser but you can choose anything you want.

  ```
"database": {
    "client": "mysql",
    "connection": {
      "host": "localhost",
      "user": "ghostuser",
      "password": "ghostuser",
      "database": "ghostuser",
      "charset": "utf8"
    }
```

Then i started the ghost with `ghost start` and it worked.

**Comment by acburdine** [comment]
@koraylinux another option for using local ghost with mysql is to run `ghost install local --db mysql`, which should add the automatic prompts for MySQL host, username, password, etc. 😄 Removes any need to manually edit configuration.

**Comment by acburdine** [comment]
@koraylinux should have asked also - is there something you're looking for us to fix in the CLI here? or is this more of a "if you'd like to use mysql instead, here's how you'd do it."

**Comment by koraylinux** [comment]
There is no problem from your side. I tried to fix sqlite3 problem on my installation but failed so it's kinda way to avoid from sqlite. I did not know the --db prefix. Thanks for the tip!

**Comment by nkgst** [comment]
> @koraylinux another option for using local ghost with mysql is to run `ghost install local --db mysql`, which should add the automatic prompts for MySQL host, username, password, etc. 😄 Removes any need to manually edit configuration.

trying this method brings me to another error. This is may be silly but don't really fluent on mysql. 
this is what it prints:
`PS C:\Users\Niccolò\Desktop\Sito\v9> ghost install local --db mysql
√ Checking system Node.js version
√ Checking current folder permissions
√ Checking memory availability
√ Checking free space
√ Checking for latest Ghost version
√ Setting up install directory
√ Downloading and installing Ghost v3.40.5
√ Finishing install process
? Enter your MySQL hostname: localhost
? Enter your MySQL username: ODBC
? Enter your MySQL password: [hidden]
? Enter your Ghost database name: v9_dev
√ Configuring Ghost
√ Setting up instance
× Starting Ghost
One or more errors occurred.

1) GhostError

Message: connect ECONNREFUSED 127.0.0.1:3306
Help: Unknown database error

Debug Information:
    OS: Microsoft Windows 10 Pro, v10.0.18363
    Node Version: v14.15.4
    Ghost Version: 3.40.5
    Ghost-CLI Version: 1.15.3
    Environment: development
    Command: 'ghost install local --db mysql'`

**Comment by acburdine** [comment]
@nkgst generally this means that you don't have mysql installed locally - see [here](https://dev.mysql.com/doc/refman/8.0/en/windows-installation.html) for instructions on how to install MySQL on Windows.

I'm closing this issue since there's nothing to update on the CLI side. If you run into any more issues, please reach out on our [forum](https://forum.ghost.org) 😄
