### ISSUE TITLE
Ghost-CLI install fails with Node ^15.x.x

### ISSUE THREAD

**Issue by JPBarringer** [TryGhost/Ghost-CLI#1379]
### Summary
Ghost-CLI install fails on OSX with Node ^15.x.x

### Steps to Reproduce
1. (Using Yarn. Run:) `sudo yarn global add ghost-cli@latest`
2. (Install runs, then:) `ghost-cli@1.15.3: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.10.0 || ^14.15.0". Got "15.5.1"`

### Technical details
* OS: Mac OS Catalina 10.15.7
* Node Version: 15.5.1
* Ghost-CLI Version: 1.15.3
* Environment: Local
* Command: sudo yarn global add ghost-cli@latest

## Bug submission checklist
- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [N/A] Attached log file
- [x] Provided technical details incl. operating system

**Comment by acburdine** [comment]
Per [the documentation](https://ghost.org/docs/faq/node-versions/), only the LTS versions of Node are supported.
