### ISSUE TITLE
unable install ghost

### ISSUE THREAD

**Issue by shayangraph** [TryGhost/Ghost-CLI#1391]
We primarily use GitHub as an issue tracker.

For usage and support questions, or ideas & feature requests please check out [our forum](https://forum.ghost.org).

Alternatively, check out these resources below. Thanks! 😁.

- [Ghost-CLI docs](https://ghost.org/docs/ghost-cli/)
- [Forum Support](https://forum.ghost.org/c/help)
- [Ideas](https://forum.ghost.org/c/Ideas)
- [Contributing Guide](https://ghost.org/docs/contributing/)
- [Self-hoster Docs](https://ghost.org/docs/install/ubuntu/)

**Comment by shayangraph** [comment]
after writting ghost update --force
show this massege
Found a development config but not a production config, running in development mode instead
what is this

**Comment by vikaspotluri123** [comment]
@shayangraph please create a post in the [forum](https://forum.ghost.org) for help with installing Ghost. You'll need to provide more information than you did here, otherwise the community won't be able to help you.
