### ISSUE TITLE
IP configuration does not update `config.production.json`

### ISSUE THREAD

**Issue by seanhamlin** [TryGhost/Ghost-CLI#1438]
### Summary

It seems that the `ip` configuration option does not update `config.production.json`.

### Steps to Reproduce

1. Run `ghost config --ip "0.0.0.0"`
2. Notice how the key `server.host` in `config.production.json` does not get updated from the default of `127.0.0.1`

My current workaround is to use `sed`:

```bash
sed -i -e '#"host": "127.0.0.1"#"host": "0.0.0.0"#' config.production.json;
```

### Technical details

Running inside a docker container.

```
Debug Information:
    OS: Alpine Linux, v3.12.3
    Node Version: v14.15.5
    Ghost Version: 4.1.0
    Ghost-CLI Version: 1.16.3
    Environment: production
```

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [ ] Attached log file
- [x] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
`ghost config --ip 0.0.0.0` works for me 🤔. Does it work when you run `ghost config set server.ip 0.0.0.0`?

**Comment by seanhamlin** [comment]
That seems to work if I use the direct key

```
node:/var/lib/ghost$ ghost config set server.host 0.0.0.0
Successfully set 'server.host' to '0.0.0.0'
Process manager 'systemd' will not run on this system, defaulting to 'local'
node:/var/lib/ghost$ cat config.production.json
{
  "url": "http://localhost:3000/",
  "server": {
    "port": 3000,
    "host": "0.0.0.0"
  },
```
