### ISSUE TITLE
Can't update ghost-cli on DigitalOcean

### ISSUE THREAD

**Issue by luizkowalski** [TryGhost/Ghost-CLI#1439]
### Summary

I can't update the `ghost-cli` on the DigitalOcean instance, no matter what I do. The update command runs without issue but the `ghost-cli` is never updated

### Steps to Reproduce
```
ghost-mgr@ghost-new:/var/www/ghost$ ghost -v
Ghost-CLI version: 1.13.1
Ghost version: 3.41.9 (at /var/www/ghost)
ghost-mgr@ghost-new:/var/www/ghost$ sudo npm install -g ghost-cli@latest

changed 403 packages, and audited 404 packages in 24s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
ghost-mgr@ghost-new:/var/www/ghost$ ghost -v
Ghost-CLI version: 1.13.1
Ghost version: 3.41.9 (at /var/www/ghost)
```

I tried using `1.16.3` instead of `latest` too, didn't help, also tried to update the cli while logged as root user, not as ghost-mgr. Nothing helps

also, `ghost doctor` doesn't seem to see any issues

```
ghost-mgr@ghost-new:/var/www/ghost$ ghost doctor
✔ Checking system Node.js version
✔ Checking logged in user
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
+ sudo systemctl is-active ghost_luizkowalski-net
Instance is currently running
ℹ Validating config [skipped]
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking binary dependencies
```

### Log file

I don't have any

### Technical details

This is an one-click install droplet from DigitalOcean

```
Linux ghost-new 4.15.0-139-generic #143-Ubuntu


ghost-mgr@ghost-new:/var/www/ghost$ npm -v
7.6.3
```

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [X] Tried to find help in the forum & docs
- [X] Checked for existing issues
- [ ] Attached log file
- [X] Provided technical details incl. operating system

**Comment by acburdine** [comment]
@luizkowalski can you run `which ghost` and see what it outputs?

My guess is you have multiple ghost-cli install locations, and the `sudo npm i -g ghost-cli@latest` is updating a different one than your shell is automatically picking up.

**Comment by luizkowalski** [comment]
@acburdine that sounds plausible since in the beginning, when I first started the blog, I had no idea how to properly handle migrations and upgrades hahahaha


```
ghost-mgr@ghost-new:~$ which ghost
/usr/local/bin/ghost
```

in both users (ghost-mgr and sudo)

**Comment by acburdine** [comment]
@luizkowalski alright, so the _quick_ fix would likely be to `sudo rm /usr/local/bin/ghost`, which would get rid of the symlink to the wrong Ghost-CLI version. The old CLI version would still be around somewhere on your filesystem, but removing that symlink _should_ ensure that you get the version installed via `sudo npm i -g ghost-cli@latest` (which should be `/usr/bin/ghost`)

**Comment by luizkowalski** [comment]
```
✖ Checking for latest Ghost version
A CliError occurred.

Message: Unable to update Ghost directly to v4.1.0. You must be on the latest v3.x to update across major versions.
Help: Run "ghost update v3" to get the latest v3.x version, then run "ghost update" to get to v4.
```

that did the trick! now I need to update to v3 before hahha


thanks a lot!
