### ISSUE TITLE
Migration failed silently and stops ghost from starting

### ISSUE THREAD

**Issue by vernak2539** [TryGhost/Ghost-CLI#1443]
I recently upgraded from `v3.12.1` to `v3.42.4` in preparation for upgrading to v4.

I exported my data, upgraded to the latest ghost-cli version, and the went through the progress by running `ghost update v3`. 

It went through the steps with no errors and tried to restart my instance using systemctl. I checked the url after this and it failed to load.

Upon further inspection of the logs, it gives the following error, which makes me think the migration didn't happen successfully.

```
Mar 24 17:45:19 code-by-vernacchia node[31039]: #033[90m----------------------------------------#033[39m
Mar 24 17:45:19 code-by-vernacchia node[31039]: #033[90mRollbackError: show columns from `email_recipients` - ER_NO_SUCH_TABLE: Table 'ghost_code_db.email_recipients' doesn't exist
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at RollbackError.KnexMigrateError (/var/www/ghost/versions/3.42.4/node_modules/knex-migrator/lib/errors.js:7:26)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at new RollbackError (/var/www/ghost/versions/3.42.4/node_modules/knex-migrator/lib/errors.js:31:26)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at /var/www/ghost/versions/3.42.4/node_modules/knex-migrator/lib/index.js:440:23
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at tryCatcher (/var/www/ghost/versions/3.42.4/node_modules/bluebird/js/release/util.js:16:23)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at Promise._settlePromiseFromHandler (/var/www/ghost/versions/3.42.4/node_modules/bluebird/js/release/promise.js:547:31)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at Promise._settlePromise (/var/www/ghost/versions/3.42.4/node_modules/bluebird/js/release/promise.js:604:18)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at Promise._settlePromise0 (/var/www/ghost/versions/3.42.4/node_modules/bluebird/js/release/promise.js:649:10)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at Promise._settlePromises (/var/www/ghost/versions/3.42.4/node_modules/bluebird/js/release/promise.js:725:18)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at _drainQueueStep (/var/www/ghost/versions/3.42.4/node_modules/bluebird/js/release/async.js:93:12)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at _drainQueue (/var/www/ghost/versions/3.42.4/node_modules/bluebird/js/release/async.js:86:9)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at Async._drainQueues (/var/www/ghost/versions/3.42.4/node_modules/bluebird/js/release/async.js:102:5)
Mar 24 17:45:19 code-by-vernacchia node[31039]:     at Immediate.Async.drainQueues [as _onImmediate] (/var/www/ghost/versions/3.42.4/node_modules/bluebird/js/release/async.js:1
```

How would I go about fixing this so I can get my block backup and running?

### Technical details:

* Ghost-CLI version: 1.16.3
* Ghost version: 3.42.4
* Node Version: v10.24.0
* Database: MySQL

**Comment by amarjandu** [comment]
Did you verify that the ghost and node are installed in the same path?

```
which node
which ghost
```

**Comment by vernak2539** [comment]
Yes. This was working before the upgrade and the error logs seem to indicate a missing migration

**Comment by reubano** [comment]
Similar error for me

```bash
275836 [2021-06-11 18:20:26] INFO Your site is now available on ...
276481 [2021-06-11 18:20:26] INFO Ctrl+C to shut down
456247 [2021-06-11 18:20:26] INFO Creating database backup
609285 [2021-06-11 18:20:26] INFO Database backup written to: /app/content/data/wei.ghost.2021-06-11-18-20-26.json
701442 [2021-06-11 18:20:26] WARN Skipping ON DELETE CASCADE for "members_labels_member_id_foreign" constraint - already set
701760 [2021-06-11 18:20:26] WARN Skipping ON DELETE CASCADE for "members_labels_label_id_foreign" constraint - already set
706213 [2021-06-11 18:20:26] WARN Skipping "members_stripe_customers_member_id_foreign" foreign key constraint creation - already exists
706496 [2021-06-11 18:20:26] INFO Adding "members_stripe_customers_customer_id_unique" index
746531 [2021-06-11 18:20:26] WARN Removing members.email_opened_count column
751659 [2021-06-11 18:20:26] WARN Removing members.email_count column
762923 [2021-06-11 18:20:26] WARN Removing members.email_open_rate column
775230 [2021-06-11 18:20:26] WARN Removing emails.failed_count column
780543 [2021-06-11 18:20:26] WARN Removing emails.opened_count column
785742 [2021-06-11 18:20:26] WARN Removing emails.delivered_count column
822130 [2021-06-11 18:20:26] ERROR show columns from `email_recipients` - ER_NO_SUCH_TABLE: Table 'heroku_35c….email_recipients' doesn't exist
822131 
822132 show columns from `email_recipients` - ER_NO_SUCH_TABLE: Table 'heroku_35c….email_recipients' doesn't exist
822132 
822133 "OuterError: Field length of `customer_id` in `members_stripe_customers` is too long!"
822133 
822134 Error ID:
822134 400
822134 
822135 Error Code: 
822135 ER_NO_SUCH_TABLE
822135 
822136 ----------------------------------------
822136 
822136 RollbackError: show columns from `email_recipients` - ER_NO_SUCH_TABLE: Table 'heroku_35c….email_recipients' doesn't exist
822138 at RollbackError.KnexMigrateError (/app/node_modules/ghost/node_modules/knex-migrator/lib/errors.js:7:26)
```

**Comment by override80** [comment]
I experienced exactly the same error. Stuck with a 502 error here, does anybody have a workaround?

**Comment by reubano** [comment]
Don't migrate...

**Comment by reubano** [comment]
v3.28.0 is the latest I got up to

**Comment by rjsquire** [comment]
same issue:

<code>[2021-09-27 20:43:38] ERROR show columns from `email_recipients` - ER_NO_SUCH_TABLE: Table 'giigate.email_recipients' doesn't exist

show columns from `email_recipients` - ER_NO_SUCH_TABLE: Table 'giigate.email_recipients' doesn't exist

"OuterError: alter table `tags` add `twitter_image` varchar(2000) null - ER_TOO_BIG_ROWSIZE: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"

Error ID:
    400

Error Code:
    ER_NO_SUCH_TABLE

----------------------------------------

RollbackError: show columns from `email_recipients` - ER_NO_SUCH_TABLE: Table 'giigate.email_recipients' doesn't exist
    at RollbackError.KnexMigrateError (/var/www/giigate.com/versions/3.42.6/node_modules/knex-migrator/lib/errors.js:7:26)
    at new RollbackError (/var/www/giigate.com/versions/3.42.6/node_modules/knex-migrator/lib/errors.js:31:26)
    at /var/www/giigate.com/versions/3.42.6/node_modules/knex-migrator/lib/index.js:440:23
    at tryCatcher (/var/www/giigate.com/versions/3.42.6/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/giigate.com/versions/3.42.6/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/giigate.com/versions/3.42.6/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/www/giigate.com/versions/3.42.6/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/www/giigate.com/versions/3.42.6/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/www/giigate.com/versions/3.42.6/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/www/giigate.com/versions/3.42.6/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/www/giigate.com/versions/3.42.6/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/giigate.com/versions/3.42.6/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)</code>

**Comment by tonyarnold** [comment]
Did anyone find a workaround for this? I'm stuck here, too.

**Comment by leonardonunespuc** [comment]
I'm having this exact same error updating from version `v3.9.0` to `v3.42.9`.

Any workaround?

**Comment by vernak2539** [comment]
Not that I've found. I just stopped using it as it was borked completely. Wish someone would've actually looked into the issue 🤷

**Comment by ErisDS** [comment]
We have a forum where you can get help & support https://forum.ghost.org. GitHub reaches a different audience, it's really for reproducible bugs rather than digging into environment problems. We've updated the new issue template here now to try to direct people better.

**Comment by vernak2539** [comment]
Hey @ErisDS, thanks for the response and for updating the template (when I submitted this a year ago I didn't know the forum existed)

A quick questionif you don't mind. You said that github is for reproducible bugs. I feel like this is a reproducible bug due to the fact that others are running into it. I know it's not a bug that details code execution paths in certain conditions, but a bug nonetheless. I would think that migration problems aren't environment problems, but rather bugs, especially if you're migrating between minor versions with tooling provided. This isn't how Ghost views it?

**Comment by ErisDS** [comment]
90% of the time migration errors are caused by configuration problems on the host system, usually one of the problems [documented here](https://ghost.org/docs/faq/troubleshooting-mysql-database/). Multiple people might encounter the same misconfiguration, but that doesn't constitute a bug in the migrations.

If I can spin up a DO 1-click droplet and always reproduce the problem using the recommended stack, that's a bug in the migrations.

Everything else is a question of whether or not Ghost CLI should detect or do something with the environment problem to make it easier to find, but ultimately that requires code to be written by someone & again 90% of the time the person encountering the config issue solves their config issue and moves on rather than contributing any improvements.

As a small team, we focus on things that are reproducible on the recommended stack, but that doesn't preclude anyone from coming along and contributing improvements if they want to.
