### ISSUE TITLE
Message: Command failed: yarn install --no-emoji --no-progress

### ISSUE THREAD

**Issue by partizan007** [TryGhost/Ghost-CLI#1474]
Following the steps in the official guide, installation fails at ghost install with the following message:

✔ Checking system Node.js version - found v14.17.0
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking free space
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v4.4.0
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@4.4.0: The engine "cli" appears to be invalid.
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@0.5.31"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
error An unexpected error occurred: "/home/ou/.cache/yarn/v6/npm-moment-2.24.0-0d055d53f5052aa653c9f6eb68bb5d12bf5c2b5b-integrity/node_modules/moment/.yarn-metadata.json: Unexpected end of JSON input".

yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "/var/www/ou/versions/4.4.0/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1

Debug Information:
    OS: Ubuntu, v18.04.5 LTS
    Node Version: v14.17.0
    Ghost-CLI Version: 1.17.2
    Environment: production
    Command: 'ghost install'

Additional log info available in: /home/ou/.ghost/logs/ghost-cli-debug-2021-05-22T16_36_50_538Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.

Ubuntu fresh installed
Is any suggestions how to fix it?

**Comment by acburdine** [comment]
@partizan007 Can you show the contents of the log file? my guess is there was an issue installing dependencies.

**Comment by Razunter** [comment]
Same issue, I suspect it's because of Yarn 2 (Yarn v2.4.1)

Log is pretty empty
```Debug Information:
    OS: �������� Windows 10 Pro, v10.0.19043
    Node Version: v14.17.1
    Ghost-CLI Version: 1.17.3
    Environment: development
    Command: 'ghost install local'
Message: Command failed: yarn install --no-emoji --no-progress

Unknown Syntax Error: Unsupported option name ("--no-emoji").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--skip-builds]

Exit code: 1

--------------- stdout ---------------
Unknown Syntax Error: Unsupported option name ("--no-emoji").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--skip-builds]
```

**Comment by meitantenik** [comment]
Facing the same issue

**Comment by lukeeno** [comment]
Same here. I am glad bot closed this issue even though it's not resolved
