### ISSUE TITLE
Add support for node 16

### ISSUE THREAD

**Issue by vladshcherbin** [TryGhost/Ghost-CLI#1491]
### Summary

Currently, supported node versions are `^12.10.0 || ^14.15.0`.

Trying to install with node 16 results in an incompatible "node" engine error.

**Comment by vikaspotluri123** [comment]
Ghost only supports node LTS as per the version policy 🙂

https://ghost.org/docs/faq/node-versions/

Closing as node 16 will be supported when it becomes LTS
