### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by khrome83** [TryGhost/Ghost-CLI#1516]
### Node Version Issues

Because Apple Silicon required Node v15.5 and Ghost CLI is listing Node v14.15 as the latest, you can't run Ghost-CLI on M1 chips. 

Is there a flag to have ghost-CLI ignore this warning and force an install?

**Comment by acburdine** [comment]
@khrome83 you should be able to run `GHOST_NODE_VERSION_CHECK=false ghost <command>` to disable the node version check. May not work for everything though.

**Comment by khrome83** [comment]
Thank you @acburdine, worked like a charm.
