### ISSUE TITLE
`ghost export` from within docker container or at running instance

### ISSUE THREAD

**Issue by dalanmiller** [TryGhost/Ghost-CLI#1521]
I've read:

* #981 
* #961 

Totally onboard with the rationale around setting up ghost via the official CLI and having ghost run via the community docker image. These are two very different installation paths. However, what I do think would be great though would be the ability to automate the backup of your ghost instance that you have running in the Docker container via `ghost export`. 

https://github.com/TryGhost/Ghost-CLI/blob/main/packages/ghost-cli/lib/tasks/import/api.js#L128-L137

Reading through the code base `ghost export` seems to be authenticating via admin credentials and then hitting the `/db/` endpoint on my ghost instance and piping that all into a file. It would be pretty great to be able to do something like:

```
docker-compose exec ghost /usr/bin/local/ghost export 
```

But when I try this, I get the response saying that "there isn't a ghost process running" because the entrypoint is `node current/index.js` which is starting ghost directly. 

My question is, if `ghost export` from within the container is off the table how else might export all my ghost data in an automated way? Is there or could there be way to point the CLI I have running on another machine (say my laptop) at my ghost blog public URL to export everything? It doesn't seem like there's any constraint necessarily on having the CLI running on the same host as the ghost instance. I'm thinking:

```
ghost export --url https://blog.example.com --email me@cool.com --password-file ./ghost_pw
```

Otherwise, other than logging in manually and clicking 'export', I'm not sure how else I should be backing up `ghost`! 

Aside: thank you for making such a great platform. 🙏🏻👻

**Comment by chardskarth** [comment]
@devinschumacher have you had a good progress on this? Or should we move on and look for another self-hosted, container friendly alternative?

**Comment by chardskarth** [comment]
Getting back here. I'll try getting my luck on the [forum](https://forum.ghost.org) instead. Hopefully, people would be more active to respond there.
