### ISSUE TITLE
Install the specified version error

### ISSUE THREAD

**Issue by ZhelinCheng** [TryGhost/Ghost-CLI#1577]
### Summary
![QQ截图20211031170434](https://user-images.githubusercontent.com/16441850/139575501-0c474451-3d5d-48cf-abb6-f671b3135abd.png)
![QQ截图20211031170555](https://user-images.githubusercontent.com/16441850/139575550-45d75d54-56e1-45ad-ba5a-2fdc14cec124.png)

**Comment by vikaspotluri123** [comment]
I just tried this and it works. Are you using a custom npm registry? Since Ghost is distributed using npm, if you use a custom registry, you have to make sure that registry is in sync with npm.

**Comment by ZhelinCheng** [comment]
> I just tried this and it works. Are you using a custom npm registry? Since Ghost is distributed using npm, if you use a custom registry, you have to make sure that registry is in sync with npm.

Thanks
