### ISSUE TITLE
Do not check for nginx nor MySQL when instructed via an addional parameter

### ISSUE THREAD

**Issue by samip5** [TryGhost/Ghost-CLI#1587]
### Summary

I'm hoping that there could be an option for the `ghost install` to skip nginx/MySQL checking all together as well as the directory being readable by other users.
My use case is that I have an haproxys in front, and then have multiple backend servers behind those (running Apache), that proxy to an application server via mod_rewrite.
This application server does not have MySQL nor nginx, but there is a MySQL server on the internal network, which Ghost can access.
So the ghost cli should NOT check if these exist via an additional parameter, so that I could still install it into this kind of environment.

**Comment by ErisDS** [comment]
This is already possible as documented in the [ghost setup](https://ghost.org/docs/ghost-cli/#ghost-setup) documentation, specifically [here](https://ghost.org/docs/ghost-cli/#what-if-i-want-to-do-something-else) 

You can use the `--no-setup-[stage]` commands to skip setup e.g. `ghost setup --no-setup-mysql`
