### ISSUE TITLE
spawn yarn ENOENT

### ISSUE THREAD

**Issue by loskiq** [TryGhost/Ghost-CLI#160]
### Issue Summary

What is this?

```
root@ghost:/opt/test# ghost install
 ✖ Checking for latest Ghost version
   → spawn yarn ENOENT
   Running system checks
   Setting up install directory
   Downloading and installing Ghost
   Moving files
spawn yarn ENOENT
```

### Technical details:

* Ghost Version: ghost installer
* Node Version: 6.9.5
* Browser/OS: Debian Jessie x86_64
* Database: SQLite

**Comment by acburdine** [comment]
@loskiq so Ghost-CLI uses Yarn to install dependencies - so you will need to install Yarn first, as is noted in the [installation documentation](https://github.com/TryGhost/Ghost-CLI/wiki/Installation) 😄

**Comment by ErisDS** [comment]
Hmmm... this for me is a blocking reason why we should not be using yarn in here ☹️

**Comment by acburdine** [comment]
@loskiq So this is issue will be fixed in the next release of Ghost-CLI. Yarn is now included in Ghost-CLI's dependencies, so that should fix any issues 😄

**Comment by ajmalbinabdulaziz** [comment]
Ofiicial ghost doc says either Yarn or NPM to manage packages >> https://ghost.org/docs/install/local/
But you can't install ghost locally without yarn. Anyway that's great. Whatever the features are, a cms should be developer friendly, that's the first thing, it should be installed without wasting hours searching in the forums for solution.
