### ISSUE TITLE
2 vulnerabilities found updating to 1.19.3

### ISSUE THREAD

**Issue by jcgallaher** [TryGhost/Ghost-CLI#1634]
When I run sudo npm install -g ghost-cli@latest I get the following message:

changed 427 packages, and audited 428 packages in 12s

32 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

If I run sudo npm audit fix --force I get the following error message.

npm WARN using --force Recommended protections disabled.
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-04T20_55_15_953Z-debug-0.log

**Comment by ErisDS** [comment]
Not every reported vulnerability is a legitimate vector. We monitor reports and deal with them as needed. If you think you have found a true security problem or attack vector, please follow our security policy to report them responsibly: https://github.com/TryGhost/Ghost-CLI/blob/main/SECURITY.md

**Comment by jcgallaher** [comment]
Ok, thank you Hannah for clarifying. 😃
