### ISSUE TITLE
`ghost-cli` assumes I want to install version 2?

### ISSUE THREAD

**Issue by markstos** [TryGhost/Ghost-CLI#1649]
### Summary

When I use the following arguments, the `ghost` CLI refuses to continue because it believes I want to install Ghost 2:

### Steps to Reproduce

```
ghost install --url example.com --log stdout --db mysql --dbhost localhost --dbname some_name --mail sendmail -f /home/mark/ghost-import/ghost-import.json 
```

Result

```
✔ Checking system Node.js version - found v16.15.0
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking free space
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v2.0.0
A SystemError occurred.

Message: Ghost v2.0.0 is not compatible with the current Node version. Your node version is 16.15.0, but Ghost v2.0.0 requires ^6.9.0 || ^8.9.0

Debug Information:
    OS: Ubuntu, v20.04.4 LTS
    Node Version: v16.15.0
    Ghost-CLI Version: 1.21.0
    Environment: production
```

If I just use `ghost install` then version 5 is selected, or if I put a "5" at the end of the command line above, then the current version is selected, but the above command line seems to wrongly trigger a default to version 2.

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [ ] Tried to find help in the forum & docs (n/a)
- [x] Checked for existing issues
- [ ] Attached log file (n/a)
- [x] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
Hey @markstos, what version of Ghost was your export created on? If you have jq, you can run `cat /home/mark/ghost-import/ghost-import.json | jq '.db[0].meta.version'`

**Comment by markstos** [comment]
I created the zip file with `migrate jekyll`, provided by the TryGhost project. I believe the version is set from here, which is set to `2.0.0`:

https://github.com/TryGhost/migrate/blob/main/packages/mg-json/lib/to-ghost-json/base-template.js#L10

Is that a good default or should it track the current Ghost version?

**Comment by vikaspotluri123** [comment]
I can't comment on the migrator, but that's why the CLI is trying to install 2.0.0! If you don't provide a version when importing, it'll fall back to the import version.
