### ISSUE TITLE
The CLI should trust the sysadmin

### ISSUE THREAD

**Issue by pedrolucasp** [TryGhost/Ghost-CLI#1663]
### Summary

The CLI assumes a bunch of pre-defined options and doesn't have room to customize whenever someone deviates from that. For instance, if you create a system user with any different name from `ghost` the CLI simply falls flat to its face. 
Something similar goes with not having `sudo` available or having the service with any other name than whatever the CLI tries to look after.

These options should be customizable, if not via the command line at least the CLI should try to extract them from the configuration file.

**Comment by ErisDS** [comment]
Hey @pedrolucasp, sorry for taking a while to respond. I can hear you're frustrated, but without exact bugs and reproduction cases, it's really hard to know what to look at.

The phrase "Should trust the sysadmin" runs pretty counter to the mission of Ghost CLI, which is making it easy to self-host Ghost. The tool is used by a lot of people who don't have sysadmin experience, so the default behaviour and expected setup is extremely explicit on purpose. There's pretty much just one right way to do things [as per our docs](https://ghost.org/docs/install/ubuntu/), else people get themselves into trouble.

We're very open to experienced sysadmins adding options and flags to make it possible to do more custom setups, but that is not a use case that the community working on the tool are currently focused on.

If you'd be up for raising some more detailed bugs and fixing them, I'm all ears. For this issue, there's nothing really to do, so I'm going to close it.
