### ISSUE TITLE
Toggle-element is broken in preview/live-view

### ISSUE THREAD

**Issue by SivertGullbergHansen** [TryGhost/Ghost-CLI#1681]
![image](https://user-images.githubusercontent.com/6785315/188467148-437323e2-663e-4638-a1ab-fd91a8b1128a.png)
![image](https://user-images.githubusercontent.com/6785315/188467183-f0bb98a5-8899-496f-ae35-3ab813ac4313.png)

Toggle-button does nothing and text is visible.

### Steps to Reproduce

1. Install clean local copy of Ghost using CLI (_ghost install local_)
2. Finish setup of site
3. Create a new post and add a toggle
5. Preview and watch the broken toggle

I expected the toggle to behave the same as your example toggles here https://edition.ghost.io/style-guide/

### Technical details

* OS: Windows 11
* Node Version: v16.14.2
* Ghost-CLI version: 1.23.0
* Ghost version: 5.13.0 (at ~\Desktop\ghost2)
* Environment: Windows
* Command: ghost install local

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file (non-existing)
- [x] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
Looks to be the same issue as https://github.com/TryGhost/Ghost/issues/14278

**Comment by SivertGullbergHansen** [comment]
> Looks to be the same issue as [TryGhost/Ghost#14278](https://github.com/TryGhost/Ghost/issues/14278)

Indeed it does. I'm closing this issue then to prevent duplicates.
