### ISSUE TITLE
error during install ghost with external mysql and parameters as input

### ISSUE THREAD

**Issue by andrzejzysko** [TryGhost/Ghost-CLI#1696]
### Summary
It looks that there is a lack of possibility to skup mysql check in the situation where mysql is installed as external source

### Steps to Reproduce

1. Install ghost using command:
```bash
ghost install --no-setup
```
or with parameters and MySQL proxy configured in localhost
```bash
ghost setup --no-prompt --url http://localhost:2368 --port 2368 --db mysql --dbhost localhost --dbuser ghost --dbpass pass --dbname ghost_db --process local
```

Both command are waiting for promt about mysql check.
How to install ghost in automatic way using script?

### Log file
```
$ ghost install --no-setup

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org



✔ Checking system Node.js version - found v16.17.1
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking system compatibility
Local MySQL install was not found or is stopped. You can ignore this if you are using a remote MySQL host.
Alternatively you could:
a) install/start MySQL locally
b) run `ghost install --db=sqlite3` to use sqlite
c) run `ghost install local` to get a development install using sqlite3.
? Continue anyway? (y/N)
```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

Message: MySQL check failed.

Debug Information:
    OS: Ubuntu, v22.04.1 LTS
    Node Version: v16.17.1
    Ghost-CLI Version: 1.23.1
    Environment: production
    Command: 'ghost install --no-prompt --no-setup'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by ErisDS** [comment]
Hey @andrzejzysko, what do you mean by "external" mysql? Things might be getting confused because you're specifying `localhost` as the host... not sure, perhaps there is a logic error somewhere here: https://github.com/TryGhost/Ghost-CLI/blob/a9ce10007e64f4157a4867d30d2118bda5cc6307/lib/commands/doctor/checks/mysql.js#L41

But also, that code should be updated to skip the check if `--no-prompt` is set.

**Comment by andrzejzysko** [comment]
Hello @ErisDS, you are right probably this should be ignored with `--no-prompt`.
The case here is that I'm using Cloud SQL Auth proxy: https://cloud.google.com/sql/docs/mysql/sql-proxy
This is the reason that I'm passing `localhost` as connection to database but the database is located somewhere else.
