### ISSUE TITLE
Allow ghost install in a root of a partion (ie. ignore lost+found)

### ISSUE THREAD

**Issue by jesterhodl** [TryGhost/Ghost-CLI#1710]
I created a separate partition (/dev/sdb1) for ghost install.
I mounted it at /var/www/ghost
When I install ghost inside /var/www/ghost it complains it can't install because it's not empty.

```
drwxrwxr-x 3 ghost   ghost    4096 Nov  8 19:24 .
drwxr-xr-x 4 root root  4096 Nov  8 19:24 ..
drwx------ 2 root root 16384 Nov  8 19:24 lost+found
```

**Comment by ErisDS** [comment]
A PR for this would be very welcome.
