### ISSUE TITLE
`update`/`install` misinterprets provided versions, if omitting patch version, 2 digits & ending in `0`

### ISSUE THREAD

**Issue by SimJoSt** [TryGhost/Ghost-CLI#1713]
### Summary

The Ghost CLI allows for updating (and installing) specific versions/tag of Ghost. It is possible to provide them with `v` as a prefix, or without, as well as only providing the major version or the major and minor version, omitting the patch version.  
If minor version is a multiple of 10 (10, 20, ...), so having at least 2 digits and ends with `0`, the wrong version gets installed. The 2 digits are split, and the first is used as the minor version and the `0` as the patch version.

### Steps to Reproduce

1. Have a Ghost install  
  Preferably, with version <5.20, so the `--force` flag doesn't need to be used
2. Run `ghost update` and provide a specific version, that has a minor version of a multiple of 10 and don't provide the patch version, like `ghost update 5.20`
3. Observer, that Ghost version 5.2.0 is getting installed

Like with `ghost update 5.21`, it should install the correct minor version. Preferably, with the current patch version.

### Log

``` zsh
$ ghost update 5.20

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org

Running in development mode

✔ Checking system Node.js version - found v16.18.1
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✔ Checking for available migrations
✔ Checking for latest Ghost version
✔ Release notes were not found
✔ Downloading and updating Ghost to v5.2.0
✔ Linking latest Ghost and recording versions
✔ Removing old Ghost versions
ghost update 5.20  15.27s user 9.01s system 137% cpu 17.708 total
```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Debian GNU/Linux 10 (buster)
* Node Version: 16
* Ghost-CLI Version: 1.23.1
* Environment: development
* Command: `ghost update 5.20`

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by ErisDS** [comment]
A PR to fix this would be very welcome.

**Comment by SimJoSt** [comment]
@ErisDS currently, I don't have the time to do it. Especially, since I don't have the expertise to do it (easily).  
At some point I might get to it and I will save this issue for later. In the meantime, it shouldn't be closed as long as the bug is not fixed.
