### ISSUE TITLE
`ghost update` keeps 2 most current, not 2 last active versions, breaking downgrading

### ISSUE THREAD

**Issue by SimJoSt** [TryGhost/Ghost-CLI#1714]
### Summary

The Ghost CLI removes old versions while updating. In the easiest to find search results, it is documented or mentioned, that the last 5 versions are kept, e.g.: https://github.com/TryGhost/Ghost-CLI/issues/646#issuecomment-365882661
That includes the most current version, that was likely just installed through the update. So only 4 "old" versions are actually kept.

This has been changed in version [1.15.0](https://github.com/TryGhost/Ghost-CLI/releases/tag/1.15.0) with no mention in the short changelog through the commit https://github.com/TryGhost/Ghost-CLI/commit/badb662c462084d2b2f8cd9b6e9f566c09d2e8f2, so I just missed it.
Since then, only the 2 most current versions are kept, because of disk space concerns: https://github.com/TryGhost/Ghost-CLI/issues/201#issuecomment-647124236.
As this includes the most current version, only 1 "old" version is kept.

Checking the code, it seems like the version removal feature only takes semver sorting into account:
https://github.com/TryGhost/Ghost-CLI/blob/badb662c462084d2b2f8cd9b6e9f566c09d2e8f2/lib/commands/update.js#L145-L160
It does not check for the currently active or just installed version, or sorts the version by last use.

This leads to the unfortunate scenario, of just having downgraded to an older version and Ghost not being able to start, as it was promptly removed again and the `current` symlink points to a version directory that does not exist.

### Steps to Reproduce

1. Have a Ghost install with the 2 most current versions installed
2. Run `ghost update` with an older version, like `ghost update 5.2.0 --force`
3. Observe, that old Ghost versions are being removed
4. Try to start Ghost and see errors or check the `current` symlink pointing to a version directory that does not exist.

The version the update command just downgraded to, should not be removed.

#### Always keep currently active version
Add a check, to never delete the currently active version or excluding it from the removal feature outright.
The latter would increase the number of kept version to 3, if the feature is not adjusted for that.

#### Add config option and/or CLI flag for number of versions to keep
The change from keeping 5 versions to just 2 went by unnoticed, and it would have been great if users/admins could define the number themselves. Everybody has different infrastructure, storage requirements and rollback needs.  
This would be great as a config option as well as a CLI command flag.

#### Keep last _active_ versions
Instead of just keeping the latest versions according to semver, it would be cleaner to keep track of the actually _active_ & used versions. People might not just upgrade to newer versions, but jump around.  
Keeping previous versions according to the history of used versions would simply things a lot.

### Workaround
Make sure to have a "free slot" for keeping versions available. With only 2 version being kept, this means removing all (typically 1) but the most current one. That way, the feature won't be triggered, and the downgrade version is not deleted.

### Log

```
ghost update 5.2.0 --force

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org

Running in development mode

✔ Checking system Node.js version - found v16.18.1
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✔ Checking for available migrations
✔ Checking for latest Ghost version
✔ Release notes were not found
✔ Downloading and updating Ghost to v5.2.0
✔ Linking latest Ghost and recording versions
✔ Removing old Ghost versions
ghost update 5.2.0 --force  15.27s user 9.01s system 137% cpu 17.708 total
```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Debian GNU/Linux 10 (buster)
* Node Version: 16
* Ghost-CLI Version: 1.23.1
* Environment: development
* Command: `ghost update 5.2.0 --force`

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by ErisDS** [comment]
A PR to fix this would be very welcome.

**Comment by SimJoSt** [comment]
@ErisDS currently, I don't have the time to do it. Especially, since I don't have the expertise to do it (easily).  
At some point I might get to it and I will save this issue for later. In the meantime, it shouldn't be closed as long as the bug is not fixed.
