### ISSUE TITLE
Ghost backup and ghost install --zip not functioning properly

### ISSUE THREAD

**Issue by Kamori** [TryGhost/Ghost-CLI#1743]
### Summary

It seems currently if you install ghost via ghost-cli and take a backup, you are not able to install from the zip.

### Steps to Reproduce

1. Follow the recommended setup doc: https://ghost.org/docs/install/ubuntu/
2. proceed to yoursite.com/ghost to finish setting up your site
3. Run `ghost backup` on your newly created site. 
4. `cp backup-*.zip /tmp/website_backup.zip`
5. Run `ghost uninstall` on your newly created site
6. Run `ghost install --zip /tmp/website_backup.zip`
7. Get the following error
```npm
✔ Checking system Node.js version - found v16.19.0
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✖ Checking for latest Ghost version
A SystemError occurred.

Message: Archive file does not contain a valid package.json.
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
It seems new installs don't place a package.json in the root directory of the site so they aren't backing up correctly.

### Log file

``` ✔ Checking system Node.js version - found v16.19.0
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✖ Checking for latest Ghost version
A SystemError occurred.

Message: Archive file does not contain a valid package.json.
```
### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

    OS: Ubuntu, v22.04.1 LTS
    Node Version: v16.19.0
    Ghost-CLI Version: 1.24.0
    Environment: production
    Command: 'ghost install --zip /tmp/example.zip'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [ x ] Tried to find help in the forum & docs
- [ x ] Checked for existing issues
- [ x ] Attached log file
- [ x ] Provided technical details incl. operating system

**Comment by Kamori** [comment]
Additionally. I tried to copy the `package.json` from my example site from `$website_dir/current/package.json` and rebuilt the backup.zip file. Then when I try to install from zip I get a different error.

```bash
$ ghost install --zip /tmp/example-sitezip

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org



✔ Checking system Node.js version - found v16.19.0
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v5.33.0
✖ Finishing install process
An error occurred.
Message: 'ENOENT: no such file or directory, lstat '/var/www/example_site/current/content/themes/casper''


Debug Information:
    OS: Ubuntu, v22.04.1 LTS
    Node Version: v16.19.0
    Ghost Version: 5.33.0
    Ghost-CLI Version: 1.24.0
    Environment: production
    Command: 'ghost install --zip /tmp/example-site.zip'

Additional log info available in: /home/example-site/.ghost/logs/ghost-cli-debug-2023-01-31T05_39_52_719Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.```

**Comment by vikaspotluri123** [comment]
The `--zip` flag for the CLI is to install a custom build of Ghost, not to import content 😄

From my recollection, after you install Ghost and create an account, you need to upload the backup zip using the [importer](https://ghost.org/help/the-importer/).

**Comment by Kamori** [comment]
Oh lol, that is confusing. It would be great to be able to install an instance via CLI using a zip created via `ghost backup` it would definitely improve my situation.

**Comment by vikaspotluri123** [comment]
At this time it's not possible for the CLI to set up Ghost for you, so it wouldn't be possible to automatically import the content. What exactly are you trying to do?

**Comment by Kamori** [comment]
I have a site I'm using to host in a different location based on VPS pricing. So i'm trying to automate spinning up my blog and importing it best I can so support this effort. Effectively it means I'm constantly migrating. 

This is something I can pretty easily accomplish with wordpress, but seems isn't so simple with ghost.


My usecase may not be common, but I would expect backing up and restoring via automation would be a pretty common task. Honestly, i would expect the Ghost managed hosting would already require something similar.

**Comment by vikaspotluri123** [comment]
This sounds like something that would be better suited to discuss on the [forum](https://forum.ghost.org) 😄
