### ISSUE TITLE
Handle email sending failures during setup more cleanly

### ISSUE THREAD

**Issue by ExplodingCabbage** [TryGhost/Ghost-CLI#1760]
### Summary

If I follow the instructions at https://ghost.org/docs/install/ubuntu/ in an AWS instance, then visit `/ghost` and fill in the setup form, the POST request to `/ghost/api/admin/authentication/setup/` will time out with a 504. In the browser, it looks like this:

![image](https://user-images.githubusercontent.com/2358339/231527722-7eb33af5-a479-4bda-8c4a-ee00be866e87.png)

I sprinkled some logging into `core/server/api/endpoints/authentication.js` and confirmed that this happens because the call to `auth.setup.sendWelcomeEmail` hangs until after Nginx has timed out handling the incoming request. I _do_ eventually see an error like this in my error log...

```
{"name":"Log","hostname":"ip-172-31-86-103","pid":5779,"level":50,"version":"5.42.2","err":{"id":"463bd850-d86f-11ed-8adf-b3daa79cf9c8","domain":"https://markamery.com","code":null,"name":"EmailError","statusCode":500,"level":"normal","message":"Failed to send email. Reason: Email has been temporarily rejected.","context":"\"Unable to send welcome email, your site will continue to function.\"","help":"\"Please see https://ghost.org/docs/config/#mail for instructions on configuring email.\"","stack":"EmailError: Failed to send email. Reason: Email has been temporarily rejected.\n    at createMailError (/var/www/marks-blog/versions/5.42.2/core/server/services/mail/GhostMailer.js:68:12)\n    at GhostMailer.handleDirectTransportResponse (/var/www/marks-blog/versions/5.42.2/core/server/services/mail/GhostMailer.js:158:19)\n    at GhostMailer.send (/var/www/marks-blog/versions/5.42.2/core/server/services/mail/GhostMailer.js:120:25)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /var/www/marks-blog/versions/5.42.2/core/server/services/auth/setup.js:186:17","hideStack":false},"msg":"Failed to send email. Reason: Email has been temporarily rejected.","time":"2023-04-11T13:46:34.970Z","v":0}
```

I am by no means an expert on email, but I _think_ what's ultimately causing this is that, if you don't configure SES or Mailgun, Ghost tries to send the email by directly sending an SMTP request through `nodemailer`, and that fails because AWS [blocks outbound SMTP by default](https://repost.aws/knowledge-center/ec2-port-25-throttle), but nodemailer and Nginx both have a 1 minute timeout so Nginx times out a fraction of a second too soon.

I'd guess that a majority of users are probably on AWS hosting, and as such, probably a majority of users hit this mysterious bug during setup.

There are a couple of things that I suspect could be done on the Ghost-CLI side to make this experience a little cleaner:
- As part of the setup process triggered by `ghost install`, check if outbound traffic on port 25 is blocked (or even just check specifically whether Ghost-CLI is running inside an AWS instance), and if so, warn that welcome email sending will fail and disable email sending entirely in the app's config
- Tweak the Nginx timeout configured by Ghost-CLI; if it were increased by 5 seconds or so, then errors caused by nodemailer timing out could be reported to the frontend

**Comment by derek-adair** [comment]
Better logging/error handling is necessary for mail things throughout it would seem.  In particular it fails in other ways when you do not configure smtp.

For example;

1. $> ghost install local
2. $> ghost start
3. Navigate to localhost:2368/ghost and finish the install
4. Add a staff member
5. UI hangs indefinitely
![Screenshot from 2023-07-20 10-17-31](https://github.com/TryGhost/Ghost-CLI/assets/847236/a1ca9532-bcb1-4159-b90d-d568c3f49ae4)

7. App reports invite is sent
8. invite is never received. 

----
valid solutions to this problem would include validating a working smtp install OR more thorough logging/error handling.
