### ISSUE TITLE
Ability to output more info during `ghost install`

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#177]
`ghost install` is the way to do a production install and setup.

It would be preferable to be able to output more information about what is happening at each step.

E.g. MySQL step - input server username and password and a database name and the database will be created for you.

I also think this needs a confirm step at the very beginning, explaining that this is a production install etc etc are you ready? [Y/n].

This issue is for the general ability to output more info wherever we need it - would be good to add a couple of examples, link them here with how to add more info if needed.

#181 - a bit related to it, because of more prompts
#188 - related to it, because it prints more information the user needs

**Comment by kirrg001** [comment]
I am closing this issue, because every custom issue e.g. #191, #190 or #189 describe the prompt output already and reference back to this issue.
