### ISSUE TITLE
Installation Issues - Blinking at Step 4 & 5

### ISSUE THREAD

**Issue by IamAbhiMishra** [TryGhost/Ghost-CLI#1777]
OS: Ubuntu 22.04 LTS
EC2

Trying to install Ghost as per the documenation. After running `ghost install` command, it's stuck step 4 & 5. It's not proceeding after that. No error produced.

<img width="852" alt="image" src="https://github.com/TryGhost/Ghost-CLI/assets/37270760/9ea6e689-db1b-4504-834a-2ee67713f479">

**Comment by daniellockyer** [comment]
That's strange! Can you re-run with `DEBUG=* ghost install`?

**Comment by IamAbhiMishra** [comment]
> That's strange! Can you re-run with `DEBUG=* ghost install`?

I apologise for responding too late. I'm new here, so still understanding how it works.

Today, I created new EC2 instance with the same configuration and tried both way with DEBUG=* and without it. Without debug mode, it's stuck at step 4 and with debug it's stuck at step 5. Please find the screenshot with debug.
<img width="949" alt="image" src="https://github.com/TryGhost/Ghost-CLI/assets/37270760/b7ed20fa-f89c-4fa7-8fc3-6078c0d7823f">

Please guide me in resolving this. I'm not able to understand why everything is going smooth when I follow the exactly steps (as described in documentation) on azure or local machine, but stuck at ec2 instance with same configuration as of azure.
