### ISSUE TITLE
latest ghost-cli start crashing on freebsd stable/14

### ISSUE THREAD

**Issue by jostreff** [TryGhost/Ghost-CLI#1794]
/usr/local/lib/node_modules/ghost-cli/node_modules/systeminformation/lib/osinfo.js:275
          const logofile = util.getLogoFile(distro);
                                ^

TypeError: util.getLogoFile is not a function
    at /usr/local/lib/node_modules/ghost-cli/node_modules/systeminformation/lib/osinfo.js:275:33
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12)

Node.js v18.18.0

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org

**Comment by vikaspotluri123** [comment]
https://github.com/TryGhost/Ghost-CLI/pull/1796 should resolve this issue, the systeminformation dependency has a typo in the version the CLI is using: https://github.com/sebhildebrandt/systeminformation/compare/v5.21.10...v5.21.11

@jostreff  in the meantime you can probably hack systeminformation by applying this patch (specifically the `lib/osinfo.js` chunk): https://github.com/sebhildebrandt/systeminformation/commit/9e78a7108221f5686cc6eb135ff63e1cedb2f1a2.patch

**Comment by jostreff** [comment]
Thanks! This fixed my problem.

**Comment by technomaji** [comment]
> #1796 should resolve this issue, the systeminformation dependency has a typo in the version the CLI is using: [sebhildebrandt/systeminformation@v5.21.10...v5.21.11](https://github.com/sebhildebrandt/systeminformation/compare/v5.21.10...v5.21.11)
> 
> @jostreff in the meantime you can probably hack systeminformation by applying this patch (specifically the `lib/osinfo.js` chunk): https://github.com/sebhildebrandt/systeminformation/commit/9e78a7108221f5686cc6eb135ff63e1cedb2f1a2.patch

How can I check or even get notification once this fix has been merged and published? I'm not familiar with that part of the git workflow.

**Comment by vikaspotluri123** [comment]
@technomaji GitHub supports subscribing to the releases of a repository through the "watch" button. 
On the [Ghost CLI repository home](https://github.com/TryGhost/Ghost-CLI), click the watch button (I think it's near the top right of the page), then select "custom", check "releases", then click "apply". If you want email notifications, you'll need to check your "Subscriptions --> Watching" at https://github.com/settings/notifications - be sure email is checked.

**Comment by daniellockyer** [comment]
Dependency has been bumped and released in v1.25.3 of Ghost-CLI 🙂
