### ISSUE TITLE
Local Ghost Installation Permission Issue

### ISSUE THREAD

**Issue by ManaSiWibi** [TryGhost/Ghost-CLI#1809]
### Summary

`ghost start` gives permission error. I just posting this in case it's a ghost-related issue, I'm not quite sure if it's my environment that is causing the problem.

Related issue: #1606 

### Steps to Reproduce

1. `ghost install local`
2. `ghost stop`
3. `ghost start`

Note: starting using `ghost restart` able to make `ghost` run. I installed `node` via `nvm`.

### Log file

```
✖ Checking system Node.js version - found v18.18.2
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Checking binary dependencies
One or more errors occurred.

1) SystemError

Message: The directory /home/user/ is not readable by other users on the system.
This can cause issues with the CLI, you must either make this directory readable by others or install node and Ghost-CLI in another location.
```

### Technical details

```
Debug Information:
    OS: Fedora Linux, v39
    Node Version: v18.18.2
    Ghost Version: 5.74.0
    Ghost-CLI Version: 1.25.3
    Environment: development
    Command: 'ghost start'
```

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by ManaSiWibi** [comment]
Related issue: #1606

**Comment by puresick** [comment]
Can we reopen this please? This is still an issue and makes setting up development environment for themes hard.
