### ISSUE TITLE
Clearer explanation for `ghost start` vs `ghost run`

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#185]
```
    restart                         Restart the Ghost instance
    run                             start a managed ghost process
    service <command> [args...]     run a service-defined command
    setup [options]                 setup an installation of Ghost (after it is installed)
    start                           starts an instance of Ghost
    stop [options]                  stops a named instance of Ghost
```

The difference between run and start isn't very clear. Although `start`/`stop`/`restart` follows the normal pattern, so it's reasonably obvious which one I should use, but I almost think `run` doesn't need help output?

Surely the only people who ever need `run` are people developing process managers?

**Comment by acburdine** [comment]
Note to myself when I add this later - `ghost run` is useful for debugging in some cases - so it might be a good idea to make it more clear that it's used for process manager developers or for debugging the ghost instance itself.
