### ISSUE TITLE
SSL handling

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#190]
This issue stems from comments in #188, and will hopefully help address #176.

**One of the most likely issue that users are going to run into is trying to set up SSL _before_ they have adequately configured their domain's DNS record to point to the current server's IP.**

This DNS setup is a *required* pre-requisite of setting up ssl for ghost, which we can write in documentation; however, ghost-cli should first do a bit more checking to prevent confusing errors.

Before running the actual letsencrypt cert provisioning command, the CLI should do a DNS check (using node's built in dns module) to ensure proper setup. If a proper DNS record is not found, the CLI should exit with a message telling the user to first setup the DNS entry correctly, then run the `ghost nginx-ssl` command to finish setting up SSL. The CLI should finish any additional setup after presenting that error.

**We need to prompt the ssl handling, see #177.**
**Ensure we tell the user that we are going to generate a letsencrypt for him**

**Comment by acburdine** [comment]
An initial version of this has been completed in #259, however there will be a more complex (but better and more thorough) solution introduced after 1.0.0

**Comment by acburdine** [comment]
With #507, there were some additional checks implemented that handles the "ip is pointing to the wrong server IP" error.

Going to close this now, we can reopen in the future if we decide we need better checks.

**Comment by arvindvenkataramani** [comment]
My domain is correctly setup (A, CNAME) and I'm still getting this error:

Message: Your domain name is not pointing to the correct IP address of your server, please update it and run `ghost setup ssl` again

**Comment by argais** [comment]
Issue persists, ghost cli 1.11.0, dns has been set for hours, and is resolving correctly to the IP it should be and still failing with the same message...
