### ISSUE TITLE
Mysql User Creation

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#191]
To simplify and secure the mysql handling in the CLI and in Ghost itself, it is a good idea to configure Ghost with a mysql user that only has privileges for the exact database that Ghost requires. 

What Ghost-CLI will need to do is prompt (see #177) for the mysql _root_ username and password as well as a database to use for Ghost itself (it already does this), but after doing that run raw mysql commands to create that database and another database with a `_backup` suffix (to be used as a part of #153), then create a `ghost` mysql user that only has permissions for those two databases on localhost. The password for this ghost user will be an auto-generated random alphanumeric string (it will be put in `config-<env>.json` so if the user wants to know what the password is, it will be there).

This should hopefully ensure a good, secure solution for the mysql connection.

Questions:
- what if the user doesn't have the root credentials?
- what if people want to use their own user name -> probably just detect if user name is root and continue?

Later:
- we won't implement the backup feature itself, we just create the table

**Comment by ErisDS** [comment]
FYI - I sorta ran into this again. 

Not sure how readable this is - but this is my strategy for getting from Ubuntu 16 to running Ghost-CLI: https://gist.github.com/ErisDS/0edb9c2bca72f99b6a428ae9f17cb747

There are other steps for security, but these are the most relevant ones to ghost-cli.

Note that I create a DB and mysql user for ghost and pass these deets in.

Note also that I create a user for ghost that I'm not really using yet, cos I'm not sure what I should do here / vs what the cli is going to do, which is more relevant to #189.

**Comment by PaszaVonPomiot** [comment]
I've read through yml it would be good to have an option to enter webroot path for ghost instance and database name because if someone would like to have multiple instances he would probably go for something like /var/www/domain1-com, /var/www/domain2-com, ...

**Comment by kirrg001** [comment]
We won't create the backup table now. We can also do that later.

The MySQL extension will do the following:
- it first checks if it can connect to the MySQL database with the entered credentials from the configuration step
- it checks if the username is root and if so, we prompt the user if the CLI should create a custom ghost mysql user with a random, strong password (this user has a limited access to the ghost database)
- if the username is not root, we just proceed with the installation
- we ensure that the config get's updated if we create a custom mysql user
