### ISSUE TITLE
Programmatic use of Ghost-CLI

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#194]
Ghost-CLI's interactive UI is super-crazy-awesome for users in the most common use-cases, which is doing a 1 time install on either a new or existing server.

However, in certain cases, it's desirable to be able to call ghost-cli programmatically, rather than manually & interactively. Ordinarily, I'd say it was up to the consumer to figure out how to do this, however the way that ghost-cli's interactive UI works by rewriting the prompt makes it very hard to answer the prompts programatically with something like [expect](https://linux.die.net/man/1/expect).

Therefore, I'd like to introduce a path-of-least-resistance workaround, which is to make it possible to pass in enough arguments that ghost-cli knows what you want it to do and doesn't output any further prompts.

To achieve this with the current features of Ghost-Cli I propose two additional arguments for the CLI install/setup commands:

- `sslemail`, e.g. `--sslemail=me@mine.com`, toggle SSL setup with this address
- `start`, e.g. `--start` or `--start=false`, toggles whether or not Ghost should be started

**Comment by acburdine** [comment]
Going to close this for now as the two merged PRs have fixed this issue temporarily - Further improvements upon this will happen as a part of #179
