### ISSUE TITLE
Cleanup of old Ghost versions

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#201]
Opening this issue for discussion and ideas.

Currently whenever a Ghost installation is updated using the CLI, the old version is left in the `versions` folder so that the user can rollback to the previous version should something go wrong. However, none of the older versions beyond that one previous version are ever cleaned up. My initial thought is that Ghost-CLI should keep 1 (maybe 2) previous releases just in case, and on update clear out anything older than that, but am curious if there's any other use-cases for keeping more than 2 versions around that I haven't thought about.

**Comment by acburdine** [comment]
@ErisDS gonna ping you for thoughts on this one - as Ghost itself is ramping up to a faster release cycle this will probably become more important.

**Comment by ErisDS** [comment]
I would keep 5, it's what I've seen in other places that use this pattern of symlinking to the current version. Not sure that I have a good usecase other than it matches and feels like a nice number 😬 

Keeping 1 or 2 seems unnecessarily stringent

**Comment by acburdine** [comment]
5 sounds like a good idea. Might add the option to disable cleaning up old versions in the `.ghost-cli` file - e.g. if "keepOldVersions" is true, keep all.

**Comment by ErisDS** [comment]
I wouldn't add that unless it gets requested by people after the cleanup is in place. More options are just more maintenance overhead.

**Comment by digitaltoast** [comment]
Is it safe to manually delete older versions? I've only got the last 4 versions installed

**Comment by heyakyra** [comment]
Wondering the same thing as @digitaltoast

**Comment by vikaspotluri123** [comment]
When deleting older versions, you run the risk of not being able to roll back, but outside of that, there should be little risk for manually deleting older versions.

**Comment by acburdine** [comment]
what we might be able to do is reduce the number of old versions we keep. right now we keep 5 but we could reduce that to 2 maybe, since we can always reinstall older versions.
