### ISSUE TITLE
Bug: Incorrect Status

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost-CLI#214]
So I have started using ghost-cli again for the first time in a long time.

I created a local install which is working nicely then created another instance in a different directory just to see what happens.

The result was 3 ghost instance with apparently 2 instances using port 2368.

So I guess at one point I killed the the old ghost service manually or restarted laptop etc but it report its status of still running.

For testing purposes I killed a new process (that was running on port 2369) and created a new ghost instance on the same port.

Here is a screenshot: https://puu.sh/wopYj/2afff4f46c.png

Note: It is possible to navigate to the correct directory and use ghost stop but we probably should determine the status in a  different manner

**Comment by acburdine** [comment]
@cobbspur some of this will be solved by #207

**Comment by cobbspur** [comment]
Ah I didn't notice that issue
