### ISSUE TITLE
ghost log - number of lines in log file vs. output

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost-CLI#221]
If the `n` is bigger than number of lines in log file there will be no output at all. eg.
```
ghost log -n 1 test-pl
INFO [2017-06-21 21:41:26] "GET /public/404-ghost.png?v=348c30487d" 200 2ms
ghost log -n 10000000 test-pl
[no output]
```

**Comment by acburdine** [comment]
Note to self: Switching to using https://github.com/alexbbt/read-last-lines instead of slice-file _should_ fix the problem.

**Comment by PaszaVonPomiot** [comment]
One more thing. The first command works, but the second doesn't:
```
ghost log -n 10 <pname> 
ghost log -f <pname>
```
