### ISSUE TITLE
Default location of generated config files and symlink

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#223]
We would like to move generated config files into the install directory of ghost and then symlink to correct places.

**For now, It's about the nginx template file and the systemd template file.**

**Comment by acburdine** [comment]
Note for myself: What should happen is a `template` method (name TBD) should be added to the `System` class which handles generation of templates & other such things.

**Comment by acburdine** [comment]
Oops, forgot to close this issue by commit, but this was fixed in #238

**Comment by acburdine** [comment]
Here's a more long-form explanation of the solution to this issue (that is currently implemented in the CLI):

1. Nginx or systemd wants to generate a config file (either based on a _template_ that's in the ghost-cli codebase OR a string with the config file contents)
2. nginx/systemd tells the CLI it wants to generate a config file, gives it the string contents of the file and the location it wants to put the config file on the system (e.g. /etc/nginx/sites-available, etc)
3. The CLI then asks the user what they want to do with the config. The user has 4 choices: 1 - write the config file, 2 - don't write the config file, 3 - View the contents of the config file (at which point the same question is re-asked, and 4 - edit the config file inline using vim or whatever the EDITOR env var is, before it's written to disk
4. Assuming the user _doesn't_ say no to generating the config file, the actual hard file is written to disk in a subfolder of the _Ghost_ install (e.g. the specific install folder, can have multiple ones per system) - the current files location is `/path/to/whatever/install/folder/system/files`
5. Ghost-CLI will run a sudo command to link the file in the ghost install to the right place on the system
6. the user can then edit the config files from within the specific ghost installation, and it will be persisted as it's symlinked into the right place
