### ISSUE TITLE
Feature: command to handle changing domain/url

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#224]
We need a method of changing the URL for a site which ensures that the change is fully handled, including:

- Setting the new config
- Generating nginx setup
- Generating an SSL setup if one is needed
- Restarting Ghost

This should be provided via a new command: `ghost url <new url>`.

This command will need to do something along the lines of:

- look up and parse the old url
- parse the new url
- detect one of the following cases:
    - Case 1: Only the protocol has changed from http -> https
    - Case 2: Only the protocol has changed from https -> http
    - Case 3: The domain has changed, no https
    - Case 4: The domain has changed, with https
    - Case 5: Only the subdirectory has changed

Each case likely needs slightly different handling, but in general this is an alias for running

- `ghost config url <new url>`
- `ghost setup nginx [ssl]`
- `ghost restart`

All cases which result in using an HTTP URL (particularly CASE 2) should show a warning message that HTTPS is recommended as per https://github.com/TryGhost/Ghost-CLI/issues/863.

TODO once this ships:

- [ ] Update the "How do I change my configured site URL?" FAQ to use this command
- [ ] Add an update to old forum posts which list the old way

**Comment by acburdine** [comment]
Just as this is on my mind - the only feasible way I could think for this to work is if it was done on `ghost config` -> e.g. during `ghost config url <newurl>`. We'd have to say that changing the url manually by editing the json file wouldn't trigger the same behavior

**Comment by ErisDS** [comment]
I have updated this issue with a spec.

**Comment by acburdine** [comment]
can potentially tackle this in CLI v2
