### ISSUE TITLE
Theme Updates

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#225]
There's a task run during the install step that copies the Casper theme shipped with the initially installed Ghost version out into the `/content/themes/` folder (see code [here](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/commands/install.js#L27-L35), including the lovely TODO comment 🙈). This step is necessary because any uploaded themes will be stored outside of the actual running Ghost version, and therefore not be lost during an upgrade.

When this step was added, Ghost 1.0 was still in the alpha stage, and Casper hadn't undergone many updates since the start of 1.0 development, so the initial concern of handling Casper updates wasn't taken into account. However, now that Ghost is in beta, and Casper 2.0-beta has been released, there needs to be a solution for updating the theme). Now, we could just copy out the new Casper version every time Ghost is updated, but if a user has made any customizations to the default Casper theme, those updates would be overwritten. Also, if Casper has increased by a major version (such as going from 1.0 -> 2.0), we wouldn't want to force a new redesign on the user, regardless if they've added any customizations. Thus, there needs to be a better solution to this problem.

### Short Term Solution

Because Ghost 1.0-beta.2 is shipping with Casper 2.0-beta, there needs to be a quickly implemented solution for updating themes, and this will just copy out the new theme on update, overwriting any changes that might be made to the default Casper theme. This will be implemented and released with a new alpha version of the CLI.

### Long-term solution

Due to the problem outlined above, the short-term solution won't work as the CLI progresses towards 1.0 status. My idea for a long-term solution involves three changes, one on install and two on update:

- On install, copy casper out of the Ghost folder instead of moving it. That way, a copy of the shipped version of Casper remains in the installed version folder.
- On update, compare the running version of casper (the one that was copied out initially) and the one left in the version folder (the one that ships with Ghost) and see if there are any differences
  - If there are any differences, _or if there are no differences and Casper has increased by a major version_, leave the existing theme in its place, and then copy the new version of Casper out to a different folder (maybe `casper-<version>`?). Then maybe hook into Ghost's notifications system somehow and let the user know that there is a new version of Casper available.
  - If there are no differences between the two and the Casper version difference is a minor or patch version bump, then overwrite the existing version with the new version.

---

- [x] Short-term overwrite solution
- [ ] replace move step with copy step
- [ ] add casper theme diff step
- [ ] add intelligent update step

**Comment by ErisDS** [comment]
I have a potentially viable simpler solution for 1.0:

On install, Instead of copying OR moving the Casper files out of Ghost into content/themes, create a symlink to casper in the version folder.

On update, if the symlink is there, update it to point to the latest version folder. If the symlink is gone, do nothing.

This behaviour can then be documented, and we could also leave a README folder in content/themes to explain. The UI will not overwrite the Casper theme, so if the symlink is gone this means someone has manually removed it.

>  If Casper has increased by a major version (such as going from 1.0 -> 2.0), we wouldn't want to force a new redesign on the user, regardless if they've added any customizations.

I thought that the decision was that if users are still using the default theme, then we can assume they do want any and all updates. Worth checking this directly with @JohnONolan.
