### ISSUE TITLE
User can disable verify prompts (e.g. --nointeractive)

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#233]
We are going to prompt the user as much as possible (e.g. for system user creation or for mysql user creation), see #177. But we would like to add a flag to disable verify prompts.

e.g. `ghost install --nointeractive`

**Comment by acburdine** [comment]
Part of this is being addressed by #227

**Comment by ErisDS** [comment]
Not sure what this applies to exactly, I am currently using the following commands:

`ghost install --no-setup`

`ghost setup --url=https://{{ server_domain }} --db=mysql --dbhost=localhost --dbuser=ghost --dbpass={{ mysql_ghost_password }} --dbname=ghost --sslemail={{ letsencrypt_email }} --start`

Both of these currently result in zero prompts. 
I'm fine with updating the commands but I do need a way to accomplish these tasks without a prompt being shown.

**Comment by ErisDS** [comment]
2 Qs

Question 1:

Should the name of this be `--nointeractive` or `--noninteractive` or `--no-interactive` or `--no-interactive`?

Given how yargs works, I would assume `--no-interactive` is most consistent.

Which leads me on to 

Question 2:

how do --no-prompt and --no-interactive relate to one another?

**Comment by acburdine** [comment]
> Given how yargs works, I would assume --no-interactive is most consistent.
Yup 👍 

> how do --no-prompt and --no-interactive relate to one another?
--no-prompt is a solution I added in so that any programmatic usage that ended up resulting in a prompt wouldn't just sit there, instead it would error out with a message along the lines of "you're probably missing some command line args"

Would be 👍 with renaming `--no-prompt` to `--no-interactive` and extending the current error out behavior with a disabling of verification prompts.

**Comment by acburdine** [comment]
soo...all of this functionality has been implemented under the `--no-prompt` flag. Now that I've implemented it I think `--no-prompt` is better as it covers _all_ prompts rather than just the verify ones.

**Comment by acburdine** [comment]
I'm _fairly_ certain this is closed by #338 and whatever final changes are part of #313 . We can reopen this later if we need to.
