### ISSUE TITLE
Nginx log file access and location

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#234]
The idea here is that _if the CLI sets up nginx for you_, it would be great to help the user finding the nginx log file e.g. in case nginx can't communicate with your instance somehow. Or ssl doesn't work or whatever.

So we could set the `error_log` property in the nginx template and set the location to the current Ghost installation folder e.g. `/path/to/ghost/folder/content/logs/nginx_error.log`. And then if an error occurs (e.g. a general CLI start error), we can tell the user that he can look into this file.

**Comment by acburdine** [comment]
a general CLI start error wouldn't actually have anything in the `nginx_error` log unfortunately.
