### ISSUE TITLE
Working directory is not a valid Ghost installation

### ISSUE THREAD

**Issue by rchampagneca** [TryGhost/Ghost-CLI#236]
The **ghost update** cli command reports:

`Woking directory is not a valid Ghost installation. Please run 'ghost update' again within a valid Ghost installation.`

Installation details:

- Ghost Version: 0.11.10
- Ghost CLI Version 1.0.0-alpha.19

**Comment by acburdine** [comment]
@rchampagneca Ghost-CLI is only designed to work with Ghost versions 1.0.0 (including betas and such) and above. Sorry!
