### ISSUE TITLE
Installing multiple blogs with the same URL on the same server results in a broken nginx config

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#247]
This is an edgecase, but I bumped into it whilst testing if the CLI did the right thing.

What I did:

- I had 2 folders /var/www/ghost and /var/www/ghost2 both on a VPS running ubuntu 16.
- I installed Ghost in /var/www/ghost and set it up, using localhost. It all worked fine but skipped the nginx setup...
- As I was testing behaviour, I wanted to run the installer again. This time I used the url http://<server_ip> and skipped ssl.
- Next, I stopped Ghost, moved to /ghost3/ and ran the install process again, with http://<server_ip> and skipping ssl
- This time, I got a 502 from nginx.

Nginx error logs showed:

> 2017/06/28 12:03:12 [error] 9344#9344: *31 connect() failed (111: Connection refused) while connecting to upstream, client: <client_ip>, server: <server_ip>, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:2369/", host: "<server_ip>"

Viewing ghost ls showed that my blog in ghost was stopped as expected, and the one in ghost2 was running on port 2368 not 2369. 

Viewing the nginx vhost file for my install, I could see that both the root (not required) and port was incorrect. 

Fixing these issues made the blog work again.

Ideally, the CLI would be able to not get confused :)

**Comment by ErisDS** [comment]
Note: the workaround for this is to call `ghost uninstall` on the existing install before installing a new one.

The problem is mainly to do with using the same url twice.

**Comment by ErisDS** [comment]
^ Note: I've been playing around this evening on beta.4 and ended up with 2 different port numbers in my nginx config again after running setup multiple times.

Also, ended up getting this warning:

```
ghost restart
Running sudo command: systemctl restart blog-name
☱ Restarting GhostWarning: blog-name.service changed on disk. Run 'systemctl daemon-reload' to reload units.
✔ Restarting Ghost
```

This is to do with the file changing underneath systemd ... even though actually my config is the same as it was before so the file is the same 🤔

**Comment by acburdine** [comment]
I'm fairly certain this issue should be resolved by recent changes. We can reopen it if we determine that this issue still exists.
