### ISSUE TITLE
Ghost doesn't start when nginx setup and systemd not

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost-CLI#262]
When setting up Ghost via the CLI and I chose to configure nginx and say 'no' when promted for systemd, Ghost won't start:

![image](https://user-images.githubusercontent.com/8037602/27827588-30a88f70-60e2-11e7-9e83-8a031daeae81.png)

OS: Ubuntu 16
Ghost-CLI: 1.0.0-beta.3

**Comment by acburdine** [comment]
Yeah I realized this might happen as I was testing yesterday, will add a check to make sure a better error is thrown 👍

**Comment by AileenCGN** [comment]
I'm gonna reopen this issue, as I ran into it again with the current changes:

![image](https://user-images.githubusercontent.com/8037602/27848548-1d25c0ba-6170-11e7-8b61-fe86ce47c004.png)

**Comment by acburdine** [comment]
That error message is much more intentional and helpful, so going to keep this closed as there's no real way to run systemd if you haven't set it up.
