### ISSUE TITLE
Ghost config uses wrong environment in local install

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#265]
Running:

`ghost install local`

Followed by 

`ghost config key value`

Results in a `config.production.json` file being created and the key value pair being added there.

I was expecting it to add the key value pair to the existing `config.development.json` file. 

Not a major issue, I can workaround by editing manually.

**Comment by acburdine** [comment]
This is a quick, one or two line fix - will add

**Comment by ErisDS** [comment]
I've just experienced this same issue with `ghost config --mail=x`, so using flags rather than key-value.
