### ISSUE TITLE
Default config review

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#267]
Before shipping an RC candidate, I think it would be a very good idea to review all the default config, that is nginx, systemd aaaaand Ghost itself.

To start with, here are a few questions that came to my mind:

Nginx:
- What _is_ the default config ssl/non-ssl - I don't think this is anywhere as a template / easy to find
- Should we serve any files as static from nginx? etc
- Should it have inline docs?

Systemd:
- Are all the fields as sensibly filled out as they can be for a unit file?
- This is probably straightforward, I already fixed the documentation field 👍 

Ghost:
- Should log rotation be on by default?

@kate & @sebgie I think a quick call / chat / checkin whilst writing the docs for these may turn up some small 1-line style changes that will make lives easier 😬

**Comment by kirrg001** [comment]
Will can talk about these questions on Friday.

**Comment by kirrg001** [comment]
> Should log rotation be on by default?

This is enabled by default and the argument of keeping it enabled is that `bunyan` keeps by default 10 log files and removes old ones to keep the disk space low.

**Comment by kirrg001** [comment]
> Are all the fields as sensibly filled out as they can be for a unit file?

We have all minimum requires fields in there and the values look correct.

The only field i've found which we could add is the `Alias` field for the `Install` section. We can define aliases for calling the service. 

> Provides a space-separated list of additional names for the unit. Most systemctl commands, excluding systemctl enable, can use aliases instead of the actual unit name.

Right now the service name is e.g. `ghost_kate-ghost-2-acburdine-me` (which you definitely have to copy, because it's hard to remember this name). So you have to run `systemctl status ghost_kate-ghost-2-acburdine-me`....but if we would put an alias like `ghost-kate-1` (ghost-[user]-[number]), that would be much easier. But sounds more like an enhancement than required.

From https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Unit_Files.html#ftn.idp8541352.

**Comment by ErisDS** [comment]
> if we would put an alias like ghost-kate-1 (ghost-[user]-[number]), that would be much easier. But sounds more like an enhancement than required.

definitely enhancement level

>>Should log rotation be on by default?

> This is enabled by default and the argument of keeping it enabled is that bunyan keeps by default 10 log files and removes old ones to keep the disk space low.

I'm sorry, my original question came from the fact there was no config for logging, and I assumed that it was disabled by default. I definitely think it should be on! Next question is how much logging is enough. Keeping in mind that, we are the people likely to bump into this the most when people report errors.

**Comment by kirrg001** [comment]
> I'm sorry, my original question came from the fact there was no config for logging, and I assumed that it was disabled by default. 

Ah i seeeee. It get's merged with from nconf and it's enabled by default in Ghost 👍

**Comment by kirrg001** [comment]
> if we would put an alias like ghost-kate-1 (ghost-[user]-[number]), that would be much easier. But sounds more like an enhancement than required.

> definitely enhancement level

I will raise an issue and then close this issue.

**Comment by ErisDS** [comment]
> > This is enabled by default and the argument of keeping it enabled is that bunyan keeps by default 10 log files and removes old ones to keep the disk space low.

> How much logging is enough. Keeping in mind that, we are the people likely to bump into this the most when people report errors.

Are we happy that 10 days is really enough? 

I think the default settings also need to be added to our documentation, because this is very difficult to find out and does not exist anywhere in any Ghost config file.
