### ISSUE TITLE
Pre fill custom configuration values

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#268]
What i have experienced is that, if you run `ghost setup` and you already have a custom `config.production.json`, the CLI always shows the default values. I was always confused what my current configuration values are.

Instead it would be useful to load the existing `config.production.json` file and pre fill the values.

So instead of showing

> ? Enter your MySQL username:

It would show (if the config has a configured user already)

> ? Enter your MySQL username (root)

**Comment by ErisDS** [comment]
I've run into this a couple of times, would be awesome to have it pull the existing config out
