### ISSUE TITLE
optimise how we detect that nginx is installed

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#282]
Right now we detect if nginx is installed like this:

`dpkg -l | grep nginx`

But if you remove nginx with `sudo apt-get remove nginx`, the CLI won't detect that nginx is not installed anymore and you will run into a `connection refused` error in the browser.

Even `sudo service nginx restart` doesn't show any error.

We should extend the nginx installation check by adding e.g. `which nginx` or `nginx -t`.
But we have to ensure that this extra check works on none ubuntu systems.

**Comment by SixBytesUnder** [comment]
Hi
I have CentOS 7 with nginx/1.10.2 installed but while installing Ghost I get:

> ? Do you wish to set up Nginx? Yes
> Nginx is not installed. Skipping Nginx setup.
>  Setting up Nginx [skipped]
> Task ssl depends on the 'nginx' stage, which was skipped.
>  Setting up SSL [skipped]

Since I'm on CentOS I obviously don't have `dpkg`. Will you add a different way of detecting if nginx exists on the server?

**Comment by acburdine** [comment]
@sixbytesunder does `which nginx` return anything?

As stated in the issue - there is a proposed switch from dpkg to `which nginx` - just need to make sure it works on non-Debian/ubuntu systems.

**Comment by SixBytesUnder** [comment]
`which nginx` on my CentOS 7.3.1611  (Core) returns
`/usr/sbin/nginx`
On my old server with CentOS 6.9 (Final) returns also
`/usr/sbin/nginx`

Hope that helps

**Comment by kirrg001** [comment]
Closing in favour of https://github.com/TryGhost/Ghost-CLI/issues/460.
We need to extend how we detect that nginx/mysql are installed.
