### ISSUE TITLE
Ghost doesn't work when systemd not setup

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost-CLI#291]
While testing this case from #216 

> test installing the CLI without nginx/ssl - ensure you are getting prompt and you answer with "no" for both services:

I ran into these issues:

![image](https://user-images.githubusercontent.com/8037602/27899262-b2313700-6253-11e7-89fc-6b0c325195f1.png)

1. ssl gets skipped, when replying ‘no’ to nginx
2. systemd gets skipped but is required in the end
3. Command then says to run `ghost setup systemd`, but this requires to run `ghost setup linux-user` first.
4. Blog not accessible because no nginx?

**Comment by kirrg001** [comment]
I see the same.
