### ISSUE TITLE
Ghost pretends to be running but isn't and can't be stopped

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost-CLI#292]
After installation and the log, that ghost is running, `ghost stop` doesn’t work:

![image](https://user-images.githubusercontent.com/8037602/27902231-29a5b1ac-625f-11e7-9ed9-f28656b5b3cf.png)

**Comment by kirrg001** [comment]
This is a permission problem.

Systemd log tells me

>   Process: 26166 ExecStart=/root/.nvm/versions/node/v6.10.3/bin/node /root/.nvm/versions/node/v6.10.3/bin/ghost run (code=exited, status=203/EXEC)

Running `ghost run` directly works, but `ghost start` fails because of systemd permissions.

**Comment by kirrg001** [comment]
Can be closed, caused by:

1. Having node installed under root only
2. Installed Ghost inside /root

We will add this to the troubleshoot section.

**Comment by kirrg001** [comment]
@acburdine 

One thing i wonder about this issue. Why does the CLI say that Ghost was successfully started, but in fact it wasn't? I wonder if the error handling for systemd is incomplete.

**Comment by rv-aburdine** [comment]
@kirrg001 so there's a bit of a long story to that - in short it's a bug in systemd that I ran into
