### ISSUE TITLE
Ghost folder & file permissions

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#294]
In an ideal world, we'd set the folder permissions to be 774 and the file permissions to be 664 for everything inside a ghost directory:

e.g.

`find /path -type d -exec chmod 774 {} \;`
`find /path -type f -exec chmod 664 {} \;`

For now they have been set to 774 as a shortcut to a good, if not the best, solution.

This would need to be done on initial install, and probably rechecked/rerun on version folders after an install.

**Comment by sebgie** [comment]
Update, after reading through https://www.cyberciti.biz/tips/understanding-linux-unix-umask-value-usage.html the correct permission for directories is `775`. Using `775` on files would make all files executable for every user which is unwanted.

Correct commands:

```
find /path -type d -exec chmod 775 {} \;
find /path -type f -exec chmod 664 {} \;
```

**Comment by kirrg001** [comment]
@acburdine Isn't that solved already?

**Comment by acburdine** [comment]
No, I left this open b/c we need a way to repair directory permissions (maybe as a part of ghost doctor or something)

**Comment by kirrg001** [comment]
Can we add this as subtask to #317 or https://github.com/TryGhost/Ghost-CLI/issues/47?

**Comment by AileenCGN** [comment]
Note for later: We can detect incorrect permissions inside the ghost installations like this:

- `find ./ -type d \! -perm 775`
- `find ./ -type f \! -perm 664`

This can be implemented in a `ghost doctor` check.

**Comment by AileenCGN** [comment]
Really good explanation (for me): https://www.linux.org/threads/file-permissions-chmod.4124/

**Comment by AileenCGN** [comment]
The current state of the CLI is, that everything except for the `versions` folder gets installed with the correct permissions as requested in this issue.

With the `ghost doctor` improvements in #613 we will check for those file and folder permissions on `update` and `start` now and let the user know, how and if those need fixing.

**Comment by AileenCGN** [comment]
After some testing with the new permission checks, it turned out that Ghost itself creates files with a `644` permission (e. g. log files). We decided to change the checks and allow `644` and `665` for files, and `775` and `755` for directories. The recommendation to the user is - in both cases - to change it to the stricter one.
