### ISSUE TITLE
Prompt with "No" to ssl parameter file generation

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#305]
If i setup ssl and i answer with **"No"** to the prompt:

> Ghost-CLI would like to generate a ssl parameters file

I am getting this:

![screen shot 2017-07-06 at 23 10 33](https://user-images.githubusercontent.com/1160712/27933168-a0fcfff8-62a0-11e7-8a90-2af97b1a91e5.png)

---

Then i have to execute the workaround again:
```
rm -rf ~/.acme/my-domain
rm system/files/my-domain.conf
ghost setup nginx ssl
```

And then answer the question with "Yes" this time and you can continue.

I am not sure if we should prompt this step.
And i think the question could be more specific like `Ghost-CLI would like to generate nginx ssl parameters file`.

**Comment by acburdine** [comment]
Closed by #338
