### ISSUE TITLE
You are able to skip systemd, but you are actually not

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#308]
If you run `ghost install` and you skip systemd setup, you won't be able to start Ghost, as linux & systemd setup is required, because you will run into

> Message: Systemd process manager has not been set up. Run `ghost setup linux-user systemd` and try again.

[you have to use `--process local` explicit if want to use the local process manager]. 

Should we remove the prompt for systemd? Or change the prompt to e.g. "Are you ready to setup systemd?". Or any other ideas?

I am still confused about this step. Both @AileenCGN and @cobbspur find that confusing as well.
It was also mentioned, that people might not even know what systemd means.

**Comment by vikaspotluri123** [comment]
This should be fixed w/ #1311 - process manager is reverted to `local` if user says no to setting up systemd
