### ISSUE TITLE
Mysql setup check

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#314]
All the other extensions, etc, have setup checks I believe, except mysql

`ghost doctor` needs to output information about whether mysql is available or not.
`ghost install` should abort if mysql is not available and `--db=sqlite3` was not passed

It should tell the user to either try running with `--db=sqlite3`, or to use `ghost install local`.

**Comment by acburdine** [comment]
One of the problems with this is that a user can potentially specify a mysql database that is on an external server, and this technically would still be fine under the recommended system stack. If we do move the system stack checks to an earlier place (#312), then the user has no chance to specify a different mysql server name.

**Comment by ErisDS** [comment]
Totally valid point.

Perhaps we could use the same pattern as the linux check? 

"Local MySQL install not found. You can ignore this if you are using a remote MySQL host. \n
Alternatively you could: a) install MySQL locally, b) run `ghost install --db=sqlite3` to use sqlite3 in production, or c) use `ghost install local` to perform a non-production install with sqlite3."
Continue anyway? [N/y]

**Comment by acburdine** [comment]
👍

**Comment by acburdine** [comment]
Closed by #318

**Comment by beta4better** [comment]
MySQL check failed on FreeBSD11.1, I installed MySQL but `ghost install` failed to detect it.

**Comment by kirrg001** [comment]
@beta4better For sure related: https://github.com/TryGhost/Ghost-CLI/issues/460
If not, please share more information :)
