### ISSUE TITLE
SSL tries to generate certificates even when it has detected it can't

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#331]
There is a logic error somewhere :)

The ssl task runs a DNS check (and other checks) before even trying to run the letsencrypt command. 

It can correctly detect that my DNS is not setup yet, and says [skipping]

However, the letsencrypt and ssl tasks still run, and eventually fail.

See this gist for a far clearer picture of what's happening:

https://gist.github.com/ErisDS/8f3f11065bc7d5765998e06a1e4ae1e5

Relevant excerpt:

```
[12:47:02] Setting up SSL [started]
  | [12:47:02] Checking DNS resolution [started]
  | Uh-oh! It looks like your domain isn't set up correctly yet. Because of this, SSL setup won't work correctly. Once you've set up your domain and pointed it at this server's IP, try running `ghost setup ssl` again.
  | [12:47:02] Setting up SSL [skipped]
  | [12:47:02] Checking DNS resolution [completed]
  | [12:47:02] Preparing Nginx for Let's Encrypt SSL certificate creation [started]
  | [12:47:02] Preparing Nginx for Let's Encrypt SSL certificate creation [completed]
  | [12:47:02] Restarting Nginx [started]
  | Running sudo command: service nginx restart
  | [12:47:02] Restarting Nginx [completed]
  | [12:47:02] Getting SSL Certificate [started]
  | [12:47:09] Getting SSL Certificate [failed]
```

**Comment by ErisDS** [comment]
@acburdine is the best way to fix this, to use a nested listr, or to pass around some skip parameter (like userExists in the linux extension).

Just wondering what the preferred pattern is, cos I think I can fix this

**Comment by acburdine** [comment]
Ah I see what the issue is -> passing around the `skip` parameter is the preferred pattern.
