### ISSUE TITLE
Can not set up SSL

### ISSUE THREAD

**Issue by ladit** [TryGhost/Ghost-CLI#350]
I have tried several times to set up SSL, but I get the same error everytime, I can not Google a suitable answer to it. The log file is:

Debug Information:
    Node Version: v6.11.0
    Ghost-CLI Version: 1.0.0-rc.2
    Environment: production
    Command: 'ghost install'
Error occurred running command: '/bin/sh -c /var/www/ghost/system/acme.sh --issue --domain XXXX.com --webroot /var/www/ghost/system/nginx-root --accountemail XXXX@XXX.com --key-file /var/www/ghost/system/letsencrypt/privkey.pem --fullchain-file /var/www/ghost/system/letsencrypt/fullchain.pem'

Exit code: 1

--------------- stdout ---------------
[Wed Jul 12 13:24:56 CST 2017] Registering account
[Wed Jul 12 13:25:06 CST 2017] Registered
[Wed Jul 12 13:25:08 CST 2017] Update success.
[Wed Jul 12 13:25:08 CST 2017] ACCOUNT_THUMBPRINT='ihmPdwU_07_DJ50qKeh7fYxbWvCxppPaZqzT56fSnh0'
[Wed Jul 12 13:25:08 CST 2017] Creating domain key
[Wed Jul 12 13:25:08 CST 2017] The domain key is here: /home/ubuntu/.acme.sh/XXXX.com/XXXX.com.key
[Wed Jul 12 13:25:08 CST 2017] Single domain='XXXX.com'
[Wed Jul 12 13:25:08 CST 2017] Getting domain auth token for each domain
[Wed Jul 12 13:25:08 CST 2017] Getting webroot for domain='XXXX.com'
[Wed Jul 12 13:25:08 CST 2017] Getting new-authz for domain='XXXX.com'
[Wed Jul 12 13:25:10 CST 2017] The new-authz request is ok.
[Wed Jul 12 13:25:10 CST 2017] Verifying:XXXX.com

--------------- stderr ---------------
touch: cannot touch '/home/ubuntu/.acme.sh/account.conf': No such file or directory
grep: /home/ubuntu/.acme.sh/account.conf: No such file or directory
grep: /home/ubuntu/.acme.sh/account.conf: No such file or directory
/var/www/ghost/system/acme.sh: 1816: /var/www/ghost/system/acme.sh: cannot create /home/ubuntu/.acme.sh/account.conf: Directory nonexistent
grep: /home/ubuntu/.acme.sh/account.conf: No such file or directory
[Wed Jul 12 13:25:18 CST 2017] XXXX.com:Verify error:Invalid response from http://XXXX.com/.well-known/acme-challenge/ZoVaPg4A5UUOe8_p9nGBt4metCovgKFY9xwowHw1d77: 
[Wed Jul 12 13:25:18 CST 2017] Please add '--debug' or '--log' to check more details.
[Wed Jul 12 13:25:18 CST 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by kirrg001** [comment]
Hey @ladit!

You are getting the error:

> Verify error:Invalid response from http://XXXX.com/.well-known/acme-challenge/ZoVaPg4A5UUOe8_p9nGBt4metCovgKFY9xwowHw1d77:

Can you please read our [troubleshooting guide](https://docs.ghost.org/docs/troubleshooting-guide#section-ssl-problems)?

It looks like your domain does not point to the correct ip address. Please check our domain settings.

Please re-open if you can't resolve your problem.
