### ISSUE TITLE
`ghost ls` as none folder owner

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#357]
I have a user `kate` and i've installed Ghost via `kate`. If i run `ghost ls` with my root user in the installation folder, the CLI shows only the headers.

> Name │ Location │ Version │ Status │ URL │ Port │ Process Manager

When i switch to my user, it shows the correct instance. I wonder if we can improve this by logging a warning. I found that confusing.

**Comment by acburdine** [comment]
I understand that it's confusing; however, I don't know of a good way to do warn other than to check folder ownership (which only works on mac/linux) and then warn if the current user is not the owner of the installation folder?

**Comment by kirrg001** [comment]
@acburdine yeah something like that 👍

**Comment by TomChantler** [comment]
Do you think that it should show all running instances to which the calling user has access? What I mean is, should `ghost ls` run as `root` show everything? Whereas `ghost ls` run as somebody with insufficient permissions would say `There are these instances which may or may not be running: foldername, foldername2, etc` or even `sorry dude, I have no access to anything. Try running as a ghost user or as root`

**Comment by acburdine** [comment]
My thought for a fix on this issue:

1. If on windows, do nothing (no easy way to accomplish this on windows that I know of)
2. If on mac/linux and `ghost ls` is run inside a ghost install directory, we can check the ownership of that particular folder and log a warning saying "this instance was installed with user x, please run `ghost ls` as that user to get running instances"
3. If on mac/linux and command is _not_ run inside a ghost install directory, there's really not much we can do I think. The only possible solution I could think of is to iterate through all of the user home directories (/Users/*/ on mac, /home/* on linux) and see if there are any files.

Number 3 is _definitely_ overkill though - my initial reaction is to not attempt 3 unless running `ghost ls` outside of the install directory as a different user becomes a huge issue.

**Comment by vikaspotluri123** [comment]
RE: 3. @acburdine what if there was a flag for that? That way if a root user is trying to find as many instances as possible, they would be able to. I can't really see many use cases for this, but just thinking out loud...

**Comment by acburdine** [comment]
@vikaspotluri123 yeah I'm not _against_ adding it, but it is a lot of extra logic to add. It also means more maintenance overhead, so I'm reluctant to add it unless there's a good enough use-case for it 😄

**Comment by TomChantler** [comment]
I haven't looked at the code yet to see what it does when I *do* run it as a ghost user, but I know that it works from any directory under those circumstances. I presume it looks through the file at `~/.ghost/config` and takes it from there. So we could certainly look through `/home` and see what was there.

**Comment by acburdine** [comment]
@TomChantler yeah that works on Linux, on mac the logic would have to be different. Again, even though it might not be _too_ difficult to add, it's probably not worth it unless the use-case is great enough.

At the moment, I think no. 2 (warning if ghost install was created by a different user) is the best solution.

**Comment by TomChantler** [comment]
Yes, sorry. I should have mentioned that. I agree that the pragmatic approach appears to be solution 2 in the first instance: "give a warning when running `ghost ls` inside a ghost installation which was created by a different user". It could later be enhanced to find all instances to which it had access if desired.
