### ISSUE TITLE
Able to run command "ghost run" properly, but "ghost start" give me 502 Bad gateway

### ISSUE THREAD

**Issue by ripzery** [TryGhost/Ghost-CLI#361]
I'm able to access the blog properly with command  **ghost run**. When I use **ghost start** the console printing log "You can access your blog at my-blog-url", but when I visited it return **502 Bad gateway**. I saw troubleshooting guide about "**The CLI says Ghost was started, but ghost ls shows it's stopped**". I entered command **sudo systemctl status service-name** then it's print log like screenshot below.

![image](https://user-images.githubusercontent.com/4509570/28252066-076cc68e-6ab6-11e7-8359-1d0d1414bf0a.png)

How to fix it?

**Comment by acburdine** [comment]
@ripzery based on the output here, the error is showing because you've installed node via nvm, specific to the `/root` folder, which won't work with the CLI - as noted in the docs [here](https://docs.ghost.org/docs/installing-ghost-via-the-cli#section-install-node-js).

**Comment by ripzery** [comment]
I deactivated nvm and I used node from /usr/bin/node and It's worked! Thanks @acburdine!.
