### ISSUE TITLE
$ghostdir/current/content/logs folder not empty after install

### ISSUE THREAD

**Issue by FLIPNEUS** [TryGhost/Ghost-CLI#362]
### This issue is a

* [X] Bug Report
* [ ] Feature Request

### Summary

After installing Ghost 1.0.0-rc1 in a folder, the default $ghostdir/current/content/logs has some stray log files (looks like from the laptop of one of the developers):

```
# ls -al ./current/content/logs/
total 244
drwxr-xr-x. 2 root root   4096 Jul 17 13:56 .
drwxr-xr-x. 8 root root   4096 Jul 17 13:56 ..
-rw-r--r--. 1 root root  78840 Jul 11 17:22 http___localhost_2368_production.error.log
-rw-r--r--. 1 root root 153830 Jul 11 17:23 http___localhost_2368_production.log
-rw-r--r--. 1 root root     87 Jul 11 14:40 README.md
```

```
# cat ./current/content/logs/http___localhost_2368_production.log
...
{"name":"Log","hostname":"Katharinas-MacBook-Pro-2.local","pid":52449,"level":40,"msg":"Ghost has shut down ","time":"2017-07-11T17:23:55.395Z","v":0}
{"name":"Log","hostname":"Katharinas-MacBook-Pro-2.local","pid":52449,"level":40,"msg":"Ghost has shut down ","time":"2017-07-11T17:23:55.395Z","v":0}
```

### Steps to Reproduce (for a bug report)

1. Create a clean directory to install Ghost
2. Run the Ghost-CLI installation
3. Browse to the Log folder of the "current/content" directory

I don't think that log files from Katharinas MacBook Pro should belong in a clean install ;).

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Red Hat Enterprise Linux 7.3
* Node Version: v6.10.3
* Ghost-CLI Version: 1.0.0-rc.2
* Environment: Production
* Command: ghost install --db sqlite3 --dbpath /srv/ghost/content/data/ghost.db

**Comment by acburdine** [comment]
Thanks for the report @FLIPNEUS - however this isn't a bug with the CLI, one of the Ghost developers accidentally published Ghost to NPM with the logs still in the folder.

This shouldn't affect ghost installs though because the logs are actually put in $ghostdir/content/logs rather than $ghostdir/current/content/logs, so I'm going to close this.
