### ISSUE TITLE
Local dev server does not shut down on correctly, throws fatal error on attempted restart.

### ISSUE THREAD

**Issue by triestpa** [TryGhost/Ghost-CLI#368]
### This issue is a

* [X] Bug Report
* [ ] Feature Request

### Summary:

`ghost restart` and `ghost stop`  fail to actually stop the server on a macOS local installation.  This causes a fatal error when attempting to restart Ghost after the first run, due to the port being in use by the original process.  The only way that I've found to shut down the server at this point is to manually find and stop the node process.

### Steps to Reproduce:

1. Set up a local environment using `ghost install local`.
2. Visit localhost:2368 to verify that ghost is running.
3. Run `ghost restart`.  You should see an error that the port is in use.
4. Run `ghost stop`.  You should see a message that no ghost instance is currently running.
5. Run `ghost start`.  You should see an error that the port is in use.
5. Visit localhost:2368 to verify that ghost is *still* running.

### Technical details:

OS: macOS 10.12.5

Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.0-rc.3
    Environment: development
    Command: 'ghost start'

**Comment by AileenCGN** [comment]
Hey @triestpa!

Thanks for the report! I can confirm this issue.
