### ISSUE TITLE
Cannot find module 'lodash/foreach'

### ISSUE THREAD

**Issue by MikaXII** [TryGhost/Ghost-CLI#37]
npm install -d somedir...
triggered this error : `Cannot find module 'lodash/foreach'`

I try this on my repo ` each = require('lodash/foreach'),` to ` each = require('lodash/forEach'),`
[line updated](https://github.com/MikaXII/Ghost-CLI/blob/master/lib/commands/doctor/index.js#L22)
and that work fine, I don't make a pr because I update somes others things.

**Comment by acburdine** [comment]
@MikaXII thanks! are you running this on Windows? It would make sense for this error if that is the case.

**Comment by MikaXII** [comment]
Archlinux, I agree I don't understand why.
I trying to build a docker image for rancher with this image [alpine-node](https://hub.docker.com/r/mhart/alpine-node/) and I have the same issue.
[my dockerfile](https://github.com/MikaXII/rancher-ghost/blob/master/Dockerfile)

**Comment by acburdine** [comment]
I think some systems are case-sensitive when it comes to file names. Archlinux is probably one of them. Bug should be fixed in the next Ghost-CLI release (which will be later today).
