### ISSUE TITLE
ghost install local  output a lot logs

### ISSUE THREAD

**Issue by fourcels** [TryGhost/Ghost-CLI#381]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

If this is a bug, double-check and make sure there's not already an existing issue for it, then provide a quick summary of what error is occurring.

If this is a feature request, use this section to describe what feature you would like to see in the CLI, as well as a quick summary of any benefits or drawbacks you can think of if this feature is implemented.

### Steps to Reproduce (for a bug report)

1. This is the first step
2. This is the second step, etc.
![screenshot_2017-07-26_14-40-06](https://user-images.githubusercontent.com/1042568/28607890-71d8221e-7210-11e7-8bdf-fe7bb66abbc0.png)

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Linux
* Node Version: 6.11.1
* Ghost-CLI Version: 1.0.0
* Environment: 
* Command: ghost install  local

**Comment by ErisDS** [comment]
Closing this as there is no explanation of what the bug is.
