### ISSUE TITLE
Adding i18n support to the CLI

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#382]
### Summary

One feature that would be incredibly neat to have in Ghost-CLI is i18n support, both for output and for checking error messages. While definitely not as much of a user-facing feature as adding i18n to Ghost itself, there are currently several problems that could happen in the CLI if the language of the server is set to something _other_ than English.

Ideally, adding i18n would be through a set of JSON files (one per locale), which the CLI would pull from to either output different languages or check system error messages against. The CLI can use [this module](https://github.com/sindresorhus/os-locale) to get the server locale and decide which message to display/check against.

**Comment by huuhaa** [comment]
You could probably add locale check at Ghost-CLI and give user information until this is fixed. Just saying cause have fighting against install issues also.
