### ISSUE TITLE
cant set mail.options.service as QQex or Yandex ...

### ISSUE THREAD

**Issue by bin16** [TryGhost/Ghost-CLI#383]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

I found service name from <https://github.com/nodemailer/nodemailer-wellknown/blob/master/services.json>, and typed it in `mail.options.service`, and run `ghost start`, then got an error ⤵️.

But it can be set as `QQ` to start server. After that I can edit config file and kill process to force it restart.

### Steps to Reproduce (for a bug report)

1. Set `config.mail.options.service` As `QQex` or `Yandex` (or other?)
2. Set the correct user and pass like it:
``` json
{
    "mail": {
        "transport": "SMTP",
        "options": {
            "service": "QQex",
            "auth": {
                "user": "xxxxx@xxxxx.xxxxx",
                "pass": "XXXXXXXXX"
            }
         }
    }
}
```
3. `ghost start` will got
```
✖ Validating config
A ConfigError occured.

Error detected in the production configuration.

Message: false
Configuration Key(s): mail.options.service
Current Value(s): QQex

Help:  Run `ghost config <key> <new value>` for each key to fix the issue.


Debug Information:
    Node Version: v6.9.0
    Ghost-CLI Version: 1.0.0
    Environment: production
    Command: 'ghost start'
```

4. But `ghost run` can start server, and successfuly send email.

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: 4.4.0-83-generic \#106-Ubuntu SMP Mon Jun 26 17:54:25 UTC 2017 i686 i686 i686 GNU/Linux
* Node Version: 6.9.0
* Ghost-CLI Version: 1.0.0
* Environment:  production
* Command: `ghost start`

**Comment by papand13** [comment]
I too have this issue but with FastMail. I am attempting to use the "FastMail" identifier, also found at https://github.com/nodemailer/nodemailer-wellknown/blob/master/services.json

**Comment by ErisDS** [comment]
There was a small bug that was causing QQEx to not work, I have submitted a PR for this.
FastMail was also missing along with a couple of others (not sure how).

`yandex` does work, but must be lowercase, not `Yandex`.

Official list of "Wellknown" services for NodeMailer that can be used with Ghost is here: https://github.com/nodemailer/nodemailer/blob/0.7/lib/wellknown.js - not the link in the above comment, as that is the list which is compatible with a version of NodeMailer that Ghost does not use.
