### ISSUE TITLE
`Starting Ghost` 1.0 fails with no error 

### ISSUE THREAD

**Issue by alexellis** [TryGhost/Ghost-CLI#384]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

If this is a bug, double-check and make sure there's not already an existing issue for it, then provide a quick summary of what error is occurring.

If this is a feature request, use this section to describe what feature you would like to see in the CLI, as well as a quick summary of any benefits or drawbacks you can think of if this feature is implemented.

### Steps to Reproduce (for a bug report)

Building and running Ghost 0.11.x works fine on Docker, but 1.0 says Starting Ghost then fails silently with no error. Please advise.

```
FROM node:6.11.1-alpine

ENV NPM_CONFIG_LOGLEVEL warn

USER root
WORKDIR /root/

WORKDIR /var/www/
RUN npm install -g ghost-cli

RUN addgroup www-data
RUN adduser ghost -G www-data -S /bin/bash
RUN chown ghost:www-data .

USER ghost
WORKDIR /var/www/
RUN mkdir -p ghost
WORKDIR /var/www/ghost

RUN ghost install local --no-start

EXPOSE 2368
EXPOSE 2369

ENV NODE_ENV production

CMD ["ghost", "start"]
```
### Technical details (will be automatically output by Ghost-CLI if an error occurs):

Ghost 1.0 - Node 0.6.11 - Alpine Linux

```
sudo docker rm ghost ; sudo docker run -e DEBUG=ghost:* -p 2368:2368 --name ghost -ti alexellis2/ghost:1.0 ghost start --debug --process=local
ghost
✔ Validating config
✔ Starting Ghost
You can access your blog at http://localhost:2368/

Ghost uses direct mail by default
To set up an alternative email method read our docs at https://docs.ghost.org/docs/mail-config
```

**Comment by acburdine** [comment]
Right, so if you're using Docker `ghost start` is not the right command to use.

With a local install `ghost start` will start up the Ghost subprocess, then exit and leave it running in the background.

Try changing the command to `CMD ["ghost", "run", "--development"]` -> it should work then.

**Comment by acburdine** [comment]
Going to close this as it's not an actual bug with Ghost-CLI itself, rather an issue with how it's used in docker.

**Comment by alexellis** [comment]
I can't see a way to open up the IP to 0.0.0.0? even passing `--ip 0.0.0.0` doesn't seem to work. Can you point me at the right docs? I'm looking but can't see it.

**Comment by ErisDS** [comment]
Wait wait - where is everyone getting the idea to use `ghost install local` for docker?! 

We keep seeing this crop up and it's horribly wrong. I'd like to make sure we point people in the right direction. I've asked this a few times now. 

No one should be using `ghost install local` and definitely not `ghost run --development` for a production install.

They should be using `ghost install --process=local` SURELY?

**Comment by acburdine** [comment]
That is also true, my mistake.

I can come up with a recommended Dockerfile here in a few if that would help.

**Comment by ErisDS** [comment]
I think it would be a good idea yeah... although it's not part of the official stack, the official stack can be used with Docker, and I'd rather cover this with a correct example in the docs than keep seeing this same thing pop up.

@alexellis I think it was you on Slack who I asked before - where did the idea to use `ghost install local` come from? I've seen it so many times now that I'm assuming there's a blog post somewhere.

**Comment by acburdine** [comment]
So as it stands, `ghost install local` is the _only_ way to get it running in Docker right now - there's a bug I discovered in that there's no way to disable setting up the ghost linux user without the `--local` option.

HOWEVER `ghost install local` is still not recommended for docker - I will open an additional issue for the bug I found.

**Comment by alexellis** [comment]
`ghost install local` failed to work in Docker. I'm really not sure why you guys didn't publish instructions for Docker or if you did - why they weren't easy to find?

**Comment by alexellis** [comment]
This was the error - I didn't find a way to pass a force flag through. @ErisDS 

```
System checks failed with message: 'Linux version is not Ubuntu 16'
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? (y/N) 
```

**Comment by alexellis** [comment]
Do you know why I get `Starting Ghost` despite passing `--no-start` ?

**Comment by ErisDS** [comment]
> I'm really not sure why you guys didn't publish instructions for Docker 

I was really hoping to avoid having to deal with "officially" it as my personal feelings for it are less than positive. The aim behind ghost-cli as well as making it easier for people to install Ghost, is to introduce a recommended stack to reduce the team's support overhead and get people to either use our recommended stack, or self-solve. 

However, I don't see us getting away from docker, so I think having a recommended approach will help keep support overhead down.

@alexellis For now I think you're going to need to hold off trying to install with Docker until a couple of ghost-cli bugs are fixed. We will get there but this is never going to be our number 1 use case.

**Comment by jwarkentin** [comment]
Some sort of support for docker would be good. It's just not feasible or desirable to switch all tooling and infrastructure away from using docker and try to manage things with the new CLI tool.

**Comment by acburdine** [comment]
@jwarkentin We're not asking that everyone do that 😄  The recommended system stack is simply saying what the Ghost Core Team will provide support for. That being said, based on the fact that Docker is very widely used in the community, I am working on a Ghost 1.0 docker image over at https://github.com/docker-library/ghost

**Comment by jwarkentin** [comment]
Perfect! I will keep an eye out for the update over there. I was just a little worried that those of us using Docker might get left behind. Thanks for your work!
