### ISSUE TITLE
what about Node.js 8? (next LTS)

### ISSUE THREAD

**Issue by moebiusmania** [TryGhost/Ghost-CLI#387]
### This issue is a

* [ ] Bug Report
* [X] Feature Request

### Summary

In about 3 months it will become the new LTS version for Node.js ( https://github.com/nodejs/LTS ), givin the time that Ghost 1.0 has come out I would expected support for both versions 6 and 8 rather than 4. Can you share some roadmap? thanks

**Comment by acburdine** [comment]
@moebiusmania Ghost (and therefore Ghost-CLI) only supports the node LTS versions. Once node 8 officially becomes an LTS version, we will support it. You can read our supported node versions docs here: https://docs.ghost.org/docs/supported-node-versions#section-why-follow-lts-
