### ISSUE TITLE
[Question] Add --silent for install/config

### ISSUE THREAD

**Issue by MikaXII** [TryGhost/Ghost-CLI#39]
Hello,

I wanna make a dynamic config without user interactions exemple : 

```
ghost install -d blog --ip ${GHOST_IP} --port ${GHOST_PORT} --db ${GHOST_DB} \
        --dbhost ${GHOST_HOST} --dbuser ${GHOST_DB_USER} --dbpass ${GHOST_DB_PASS} \
        --dbname ${GHOST_DB_NAME} --url ${GHOST_URL} --silent ${GHOST_VERSION}
```
What is expected its an auto-install without prompt and not automatic launch of ghost.

I work on this but my code it's pretty dirty (I'm not a big fan of JS^^).
It's possible to implement this feature for futur releases ?

EDIT : I forget 'url' should be add as parameter

**Comment by acburdine** [comment]
@MikaXII this is definitely planned - going to go ahead and close this as I'm writing up a more detailed issue which covers this and other things 😄 Thanks for the submission though!

**Comment by acburdine** [comment]
New issue - #46
