### ISSUE TITLE
Ghost install fails when setting up systemd

### ISSUE THREAD

**Issue by sebastiaanluca** [TryGhost/Ghost-CLI#397]
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

Running `ghost install` on a fresh Ubuntu 16.04 server with all prerequisites installed fails because it cannot setup systemd due to a missing `ghost` user (which is present).

### Steps to Reproduce

1. Follow the installation instructions by creating a new folder, installing yarn, making sure the user owns the directory, etc
2. Install the ghost-cli binary using `sudo yarn global add ghost-cli`
3. Run `ghost install` in that empty new folder and watch it install Ghost while inputting data along the way:

```
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking operating system
✔ Checking MySQL is installed
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v1.1.0
✔ Finishing install process
? Enter your blog URL: http://www.ghost.example
? Enter your MySQL hostname: localhost
? Enter your MySQL username: root
? Enter your MySQL password: [hidden]
? Enter your Ghost database name: ghost
✔ Configuring Ghost
✔ Setting up instance
Running sudo command: chown -R ghost:ghost /home/sebastiaan/ghost-blog-test/content
✔ Setting up "ghost" system user
? Do you wish to set up Nginx? Yes
✔ Creating nginx config file at /home/sebastiaan/ghost-blog-test/system/files/www.ghost.example.conf
Running sudo command: ln -sf /home/sebastiaan/ghost-blog-test/system/files/www.ghost.example.conf /etc/nginx/sites-available/www.ghost.example.conf
Running sudo command: ln -sf /etc/nginx/sites-available/www.ghost.example.conf /etc/nginx/sites-enabled/www.ghost.example.conf
Running sudo command: service nginx restart
✔ Setting up Nginx
? Do you wish to set up SSL? No
ℹ Setting up SSL [skipped]
? Do you wish to set up "ghost" mysql user? Yes
✔ Setting up "ghost" mysql user
? Do you wish to set up Systemd? Yes
The "ghost" user has not been created, please run `ghost setup linux-user` first
ℹ Setting up Systemd [skipped]
✔ Running database migrations
? Do you want to start Ghost? Yes
✔ Validating config
```

4. Watch it fail when starting the ghost service:

```
A SystemError occured.

Message: Systemd process manager has not been set up. Run `ghost setup linux-user systemd` and try again.
```

I can verify the ghost user has been created by running `cat /etc/passwd` which gives me:

```
ghost:x:997:997::/home/ghost:
```

Running `ghost setup linux-user` again:

```
Running sudo command: chown -R ghost:ghost /home/sebastiaan/ghost-blog-test/content
✔ Setting up "ghost" system user
```

And `ghost setup systemd`:

```
The "ghost" user has not been created, please run `ghost setup linux-user` first
ℹ Setting up Systemd [skipped]
```

### Technical details

* OS: Ubuntu 16.04
* Node Version: v6.11.1
* Ghost-CLI Version: 1.0.0
* Environment: production
* Command: 'ghost install'

No idea where to go from here. All requirements are met and I followed the installation instructions to the letter multiple times.

**Comment by ErisDS** [comment]
Hey @sebastiaanluca, eek - seems something's gone a bit wrong with the detection of your `ghost` user. Not sure what or why, but to try to get you moving again:

Can you run the following commands, and then provide the output here?
- `id -u ghost` 
- `stat /home/sebastiaan/ghost-blog-test/content`

Once you've done that, you can try doing this command:

`sudo chown -R ghost:ghost /home/sebastiaan/ghost-blog-test/content`

And then try the `ghost setup systemd`

**Comment by sebastiaanluca** [comment]
`id -u ghost`:
```
997
```

`stat /home/sebastiaan/ghost-blog-test/content`:
```
File: '/home/sebastiaan/ghost-blog-test/content'
Size: 272             Blocks: 0          IO Block: 4096   directory
Device: 2dh/45d Inode: 114         Links: 1
Access: (0755/drwxr-xr-x)  Uid: ( 1000/ sebastiaan)   Gid: ( 1000/ sebastiaan)
Access: 2017-07-29 17:26:59.000000000 +0000
Modify: 2017-07-29 17:24:34.000000000 +0000
Change: 2017-07-29 17:24:34.000000000 +0000
Birth: -
```

But I think I figured out the issue 😅 Directory was linked using NFS so ghost-cli couldn't change its permissions or owner, therefore it kind of silently failed where it did. I've manually created a regular folder and everything went well installing Ghost in there. Now I need to somehow figure out how to enable folder sync with a different user as owner.

Thanks and sorry for the trouble!
