### ISSUE TITLE
Install ghost-cli on webfaction

### ISSUE THREAD

**Issue by reyman** [TryGhost/Ghost-CLI#405]
### This issue is a

* [X ] Bug Report
* [ ] Feature Request

### Summary

I'm trying to install the new ghost cli on webfaction hosting, which have special configuration for npm running : https://docs.webfaction.com/software/nodejs.html

### Steps to Reproduce (for a bug report)

a) going to /webapps/yourghostwebsite/
b) run npm i -g ghost-cli
c) create and enter into /webapps/yourghostwebsite/ghost/ folder
d) running "ghost install"

```
[reyman64@web564 ghost_seb]$ cd ghost/
[reyman64@web564 ghost]$ ghost install
✔ Checking system Node.js version
✖ Checking current folder permissions
A SystemError occurred.
```

return this error message : 

```
Message: The path /home/reyman64/webapps/ is not readable by other users on the system.
This can cause issues with the CLI, please either make this directory readable by others or install in another location.
```

I sent a message to webfaction admin, but we don't found were is the problem. 
Any idea to solve this ?

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Centos 7
Node Version: v4.8.3
Ghost-CLI Version: 1.0.1
Environment: production
Command: 'ghost install'

**Comment by ErisDS** [comment]
I've taken webfaction off the official list in the [hosting guide](https://docs.ghost.org/v1.0.0/docs/hosting) for now. I think this probably counts as "shared" hosting and won't work.

**Comment by rv-aburdine** [comment]
There is still a partial fix for this in #409 -> in that PR the directory permissions check gets skipped if `--no-setup-linux-user` is passed to `ghost install`.

**Comment by rodrigosaling** [comment]
WebFaction one-click installer now installs Ghost 1.5.1 with support to ghost-cli. I am already using it and did the update to version 1.6.0 using the command line. References: https://community.webfaction.com/questions/21130/installing-ghost-10-or-above-and-updating-it and https://community.webfaction.com/questions/21122/how-should-i-upgrade-ghost-v-1x-to-newest-version

**Comment by therealpecus** [comment]
updating via ghost-cli (specifically on webfaction) might leave you in a situation in which you cannot restart ghost, due to the permission checks.

to fix, add `--no-setup-linux-user` to `ghost start`, e.g.:

`ghost start --no-setup-linux-user`
