### ISSUE TITLE
Running `ghost install` with `--no-prompt` option fails if mysql is not installed

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#410]
See https://github.com/TryGhost/Ghost-CLI/pull/318#issuecomment-319064657

We should throw an error and exit rather than prompt if `--no-prompt` is passed as an option.

**Comment by mathiasjakobsen** [comment]
@acburdine, throwing an error is not corresponding with the UI message?
> Local MySQL install not found. You can ignore this if you are using a remote MySQL host.

In my case I'm actually running a remote database, which should cause the setup too fail.

**Comment by acburdine** [comment]
oooh ok, yeah that's a good point - will add that check in.
