### ISSUE TITLE
$ ghost update all?

### ISSUE THREAD

**Issue by crakila** [TryGhost/Ghost-CLI#413]
### This issue is a

* [ ] Bug Report
* [x] Feature Request

### Summary

I would like to see a `--all` flag for `ghost update`. At the moment, you need to `cd` into the location of the ghost blog and update each one. It would be nice to invoke `ghost update all` and for it to `cd` into those directories itself and do the updates. 

Obviously not everyone wants to update all their instances at once (Due to theme updates or other code-breaking reasons) but for people that are using `casper` unmodified, it would be a nice addition

Thank you in advance for reading this FR. :)

**Comment by acburdine** [comment]
Definitely worth considering 😄
