### ISSUE TITLE
ghost start doesn't work on Windows

### ISSUE THREAD

**Issue by softcraftsman** [TryGhost/Ghost-CLI#415]
# Issue Summary

After working through the basic installation issues on installing on Windows using "ghost install local", I keep getting these errors when running "ghost start"

# Steps to Reproduce

Windows 10 using Administrator command prompt.
npm install ghost-cli -g
ghost install local
ghost start (as part of the install or afterwards)
Technical details:

C:\Ghost\ghost3>ghost install local
√ Checking system Node.js version
√ Checking current folder permissions
i Checking operating system [skipped]
i Checking MySQL is installed [skipped]
√ Checking for latest Ghost version
√ Setting up install directory

Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.\ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.| Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages./ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.- Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.\ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.| Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages./ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.- Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.\ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.| Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages./ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.- Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.\ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.| Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages./ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.- Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.√ Downloading and installing Ghost v1.2.0
√ Finishing install process
√ Configuring Ghost
√ Setting up instance
√ Running database migrations
√ Validating config
× Starting Ghost
A GhostError occurred.
Message: Ghost process exited with code: 1

Debug Information:
Node Version: v6.11.1
Ghost-CLI Version: 1.0.3
Environment: development
Command: 'ghost install local'

Additional log info available in: C:\Users\John.ghost\logs\ghost-cli-debug-2017-08-01T14_11_46_230Z.log

Debug Information:
Node Version: v6.11.1
Ghost-CLI Version: 1.0.3
Environment: development
Command: 'ghost install local'
Message: Ghost process exited with code: 1
Stack: Error: Ghost process exited with code: 1
at ChildProcess.cp.on (C:\Program Files (x86)\Nodist\bin\node_modules\ghost-cli\lib\utils\local-process.js:47:24)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by acburdine** [comment]
@softcraftsman would you mind running `ghost run --development` and let me know what the output of that is?

**Comment by softcraftsman** [comment]
That did successfully start the blog while displaying output in the console window.

Regards,

John Brown
Tritium Consulting, Inc.

**Comment by constantx** [comment]
I ran into the same issue, ran `ghost run --development` and got this:

```
  ☯ ghost run --development
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
[2017-08-13 05:34:29] ERROR

NAME: DatabaseIsNotOkError
CODE: MIGRATION_TABLE_IS_MISSING
MESSAGE: Please run knex-migrator init

level:normal

If knex-migrator is not installed, please run "npm install -g knex-migrator"
Read more here: https://github.com/TryGhost/knex-migrator
```

After installed knex-migrator, and ran `knex-migrator init`, got:
```
Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/constantx/.config/yarn/global/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/constantx/.config/yarn/global/node_modules/bunyan/lib/bunyan.js:79:18)
```

**Comment by ErisDS** [comment]
As far as I'm aware from additional context on slack, this last comment was not running on Windows, and the first error was happening due to having swapped from sqlite3 to mysql without running `ghost setup migrate`.

**Comment by acburdine** [comment]
@softcraftsman are you still having this issue?

**Comment by kirrg001** [comment]
@softcraftsman didn't came back for a reply. I assume it's solved. Closing for now.

We can always re-open the issue.
