### ISSUE TITLE
Use sslemail if already present in .ghost-cli

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#416]
If I run `ghost setup nginx ssl` or `ghost setup ssl` and there is already an email in .ghost-ci, please can we use this?

IMO if I explicitly provide --sslemail= with that command, it should update the record in .ghost-cli and use that instead, i.e. be an override.

Sorry if this is already tracked somewhere.

**Comment by acburdine** [comment]
Per the refactor to let Acme deal with SSL renewal, we don't actually store the emails in `.ghost-cli` anymore (the only reason we did in the first place is to make renewal work)

Am willing to bring saving the email back if it's wanted though.

**Comment by ErisDS** [comment]
I think acme.sh removed their storage of the email address as well? Can close this for now and revisit if more people ask for it :)
