### ISSUE TITLE
[Bug Report] Cannot use UNIX socket via ghost start

### ISSUE THREAD

**Issue by Magentaize** [TryGhost/Ghost-CLI#417]
I'm using nginx in CentOS, if I use `NODE_ENV=production node current/index.js` to start ghost, all things work properly, but if I use `ghost start` to start ghost, I cannot access my site and nginx says it cannot connect to socket (using the same config file).

nginx log:
[error] 146151#146151: *720369 connect() to unix:/home/wwwroot/magentaize.net/blog/ghost.sock failed (111: Connection refused) while connecting to upstream, client: 49.*.*.*, server: blog.magentaize.net, request: "GET /ghost/ HTTP/2.0", upstream: "http://unix:/home/wwwroot/magentaize.net/blog/ghost.sock:/ghost/", host: "blog.magentaize.net", referrer: "https://blog.magentaize.net/ghost/"

**Comment by acburdine** [comment]
This is an error I've not seen before :/ Just to make sure I understand correctly - your nginx config is the same as the CLI auto-generates? I've never seen Nginx try to connect to Ghost over a socket before - normally it's just configured to connect via reverse-proxy.

**Comment by Magentaize** [comment]
Thanks for your reply -P
My nginx config is not as the same as the CLI auto-generates,  I use socket as a upstream in nginx as the saying goes in docs.ghost.org
>Ghost can also be configured to listen on a unix socket by changing the server config to something like:
"server": {
    "socket": "path/to/socket.sock"
}

**Comment by ErisDS** [comment]
@Magentaize can you please also provide your nginx config? No one can reproduce what you're seeing if you don't provide the key information about how you got it.

As this is a non-recommended setup (CentOS, sockets, etc) it's low priority for us, therefore if you want to see a fix, you need to be more forthcoming & helpful.

**Comment by ErisDS** [comment]
@Magentaize can you please also provide your nginx config? No one can reproduce what you're seeing if you don't provide the key information about how you got it.

As this is a non-recommended setup (CentOS, sockets, etc) it's low priority for us, therefore if you want to see a fix, you need to be more forthcoming & helpful.

**Comment by Magentaize** [comment]
@ErisDS Ok, sorry, it's my fault.

My nginx config:
```nginx
upstream ghost_upstream {  
    server unix:/home/wwwroot/ghost/ghost.sock;
    keepalive 64;
}

server{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name blog.magentaize.net;
    root /home/wwwroot/ghost;
    # some SSL config

    location / {
        proxy_set_header Accept-Encoding ""; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_pass http://ghost_upstream;
    }
}
```

And my ghost config:
```json
"server": {
    "socket": "/home/wwwroot/ghost/ghost.sock"
}

**Comment by juan-g** [comment]
I've just commented on a workaround and proposed an enhancement for this use case:

[Ghost-CLI: Add Unix socket support to `ghost start` and `ghost restart` - Ideas - Ghost Forum](https://forum.ghost.org/t/ghost-cli-add-unix-socket-support-to-ghost-start-and-ghost-restart/758)
