### ISSUE TITLE
Improve logging output

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#42]
Right now ghost-cli starts development mode and production mode in background by spawning a child process.

I am working on logging for ghost and i wonder how this can look like with ghost-cli.
We can create a command like `ghost log`, which is aware of where the log rotated files are and makes a tail of the newest file. Not sure about development mode, because usually we log in development to stdout/stderr only. That would mean `ghost start name=development` would not start the process in background and pipes the stdout/stderr to current process.

**Comment by acburdine** [comment]
So the design of the CLI is that each process manager is responsible for starting and spawning its own ghost process, which includes managing logs and other things. (kind of works similar to the storage adapters in ghost itself).

My thought here is to add better logging output to the `local` process manager and then possibly a `ghost log` command that also integrates with the process manager to return the log.

As far as logging directly to stdout/stderr in development mode, that's probably best left to the process managers themselves - might be willing to add that to the `local` process manager but thinking about it it might not be within the scope of the CLI. IMO Ghost-CLI should be used to install ghost for production or locally for development of themes/apps/adapters/etc, but if Ghost core itself is actuallly being worked on the CLI shouldn't be used to install it.

**Comment by ErisDS** [comment]
IMO `ghost install` will always use production mode, and `ghost install local` will do a simpler install for development mode using the `local` process manager.

The intended use for `ghost install local` is theme & app development, so whatever logging solution is designed should consider this usecase - what to theme / app developers need?

I think they will want to be able to view any error output they generate whilst developing?

**Comment by acburdine** [comment]
This will also likely be addressed by #66
