### ISSUE TITLE
ghost install local with specific version

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#423]
This use case only occurred to me today as we broke local installs of 1.4.0 in Ghost.

It currently doesn't seem to be possible to force a local install to a particular version.

None of these seem to work as expected, the `--version` and `--local` flags are ignored.

`ghost install local 1.3.0`
`ghost install --local --version=1.3.0` 
`ghost install local --version=1.3.0`

**Comment by acburdine** [comment]
The only real way to get it to work at the moment is `ghost install 1.3.0 --local --db sqlite3 --no-setup-linux-user --no-stack`. Obviously that isn't the best solution - will update so that `ghost install 1.3.0 --local` works as a solution for this.
