### ISSUE TITLE
Improvements / changes for `ghost log`

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#432]
The `ghost log` command is a really great idea to make interfacing with the bunyan logs easier, however I think the current behaviour is a bit confusing.

Currently, `ghost log` seems to only output the access log. The problem with this is that most people, when accessing their logs, need the error log. Especially in terms of us trying to debug various people's issues, I want the output of `ghost log` to result in the user finding what's wrong 😉 

I think first things first we should straight-up change `ghost log` to output error logs instead.

Better would be the full log merged... but that seems like it would be significantly heavy duty for a minimal improvement so maybe `ghost log --access` or `ghost access-log` could be used to fetch the standard log?

**Comment by acburdine** [comment]
`ghost log` will output both currently - the non-error log contains both normal logs _and_ error logs, due to the way ghost-ignition (and bunyan underneath it) is set up.

Because of this, it might make more sense to have an `--error` flag that will _only_ show the error messages?
