### ISSUE TITLE
Reinstall ghost via cli

### ISSUE THREAD

**Issue by maks123** [TryGhost/Ghost-CLI#433]
I'm having problems with reinstalling Ghost via CLI
My actions:
1. installing ghost with mysql database dbhome_db and user dbhome_user. Everything worked.
2. I decided to reinstall ghost with new parameters: db:  dbh_prod_db, user: dbh_user (used ghost uninstall before install)
The installation with migration passed without errors.
But when you open the site there is an error
500
ER_DBACCESS_DENIED_ERROR: Access denied for user 'dbhome_user' @ 'localhost' to database 'dbhome_db'

These are old database parameters.
The old database with the user was deleted before ghost install

Where does the installer store the old values?

Thanks for the answer.

* OS: Centos 7
* Node Version: v6.11.1
* Ghost-CLI Version: ghost-cli@1.0.3
* Environment: 
* Command:

**Comment by acburdine** [comment]
Hmm...it seems like the config values didn't get set correctly during install.

Can you double check and make sure that the value for your database name in `config.production.json` is correct?

**Comment by maks123** [comment]
Hi.
My config:
![image](https://user-images.githubusercontent.com/506071/29222662-416e89ec-7ee5-11e7-8450-11129c7b165d.png)

**Comment by acburdine** [comment]
Hmm... can you try running these commands for me?
1. `ghost stop`
2. `ghost setup migrate`
3. `ghost start`

and see if that fixes your issue?

**Comment by maks123** [comment]
Hi.


```
[ghost@SKRS1358 ghost]$
[ghost@SKRS1358 ghost]$ ghost stop
Running sudo command: systemctl stop ghost_www-dbhome
✔ Stopping Ghost
[ghost@SKRS1358 ghost]$ ghost setup migrate
✔ Running database migrations
[ghost@SKRS1358 ghost]$ ghost start
✔ Validating config
Running sudo command: systemctl start ghost_www-dbhome
✔ Starting Ghost
You can access your blog at https://www.dbh

Ghost uses direct mail by default
To set up an alternative email method read our docs at https://docs.ghost.org/docs/mail-config
[ghost@SKRS1358 ghost]$

```
The problem was not fixed.

**Comment by acburdine** [comment]
@maks123 is this still an issue? There was some migration changes added in Ghost-CLI 1.3.0 - if you're still having the problem let me know :)

**Comment by kirrg001** [comment]
@maks123 didn't come back. Closing.

We can always re-open.
