### ISSUE TITLE
Setting mysql database details using connection string

### ISSUE THREAD

**Issue by prashanthmadi** [TryGhost/Ghost-CLI#434]
Can we set ghost config using connection string instead of providing all details manually as in https://docs.ghost.org/v1.0.0/docs/cli-config
 
https://github.com/TryGhost/Ghost/issues/4021

* OS: All
* Node Version: All
* Ghost-CLI Version: 1.0.3
* Command: ghost config

**Comment by prashanthmadi** [comment]
Can I use below, would it work ?
> ghost config database '{ "client": "mysql", "connection": process.env.connectionString}'

**Comment by acburdine** [comment]
@prashanthmadi that approach wouldn't work, no. Gonna close this issue though as it's related to Ghost and knex-migrator itself, see https://github.com/TryGhost/knex-migrator/pull/74.
