### ISSUE TITLE
ghost-cli throwing errors when attempting to interface with a blog

### ISSUE THREAD

**Issue by fahy** [TryGhost/Ghost-CLI#435]
### Summary

OK, so I encountered the same error as #354 last night.

```
vampiricpadraig@titan  /home/web/padraig.blog  ghost start
/usr/local/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:1079
      else throw err
           ^

Error: failed

    at module.exports.sync (/usr/local/lib/node_modules/ghost-cli/node_modules/execa/index.js:298:26)
    at handleShell (/usr/local/lib/node_modules/ghost-cli/node_modules/execa/index.js:100:9)
    at Function.module.exports.shellSync (/usr/local/lib/node_modules/ghost-cli/node_modules/execa/index.js:307:43)
    at SystemdProcessManager.isRunning (/usr/local/lib/node_modules/ghost-cli/extensions/systemd/systemd.js:61:19)
    at Instance.get running [as running] (/usr/local/lib/node_modules/ghost-cli/lib/instance.js:61:27)
    at StartCommand.run (/usr/local/lib/node_modules/ghost-cli/lib/commands/start.js:27:21)
    at Function._run (/usr/local/lib/node_modules/ghost-cli/lib/command.js:198:48)
    at Object.handler (/usr/local/lib/node_modules/ghost-cli/lib/command.js:117:22)
    at Object.self.runCommand (/usr/local/lib/node_modules/ghost-cli/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:990:30)
    at Object.Yargs.self.parse (/usr/local/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:532:23)
    at Object.run (/usr/local/lib/node_modules/ghost-cli/lib/bootstrap.js:165:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/bin/ghost:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

```

When I do `ghost start`, ghost ls` or something similar, it will always return the above error. 
On other blogs that I have installed (Note, I have 4 installed), I can only `ghost start` them but nothing more than that.

I can `ghost install` in a new directory but trying to interface with it afterwards throws the above error.

---

To get around this in the meantime, I have opened up a tmux session and ran `ghost run` which will work for now, but obviously not ideal.

**My question is: Is there a way to re-install `ghost-cli` and does it affect sites that is already there or what can I do to resolve this?**

Thanks in advance.

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Debian 9.1
* Node Version: v6.9.1
* Ghost-CLI Version: 1.0.3
* Environment: production
* Command: 'ghost install'

**Comment by acburdine** [comment]
Will look at this today - my guess is Debian's version of systemd returns a different response for `systemd is-enabled ghost_service`

**Comment by tmack8001** [comment]
I'm getting a similar error on my raspbian setup (another non supported installation stack).

**Comment by fahy** [comment]
Right after playing with this, breaking it and unbreaking it and screaming "WTF" about a million times, I have "rednecked" this to get it working.

First of all, make sure ALL the files are owned by `ghost:ghost` (including the hidden `.ghost-cli` file)
Secondly, check that `.ghost-cli` and adjust the cli version to the version that you have installed (In my case it was `1.1.1`)

Now, it may not be necessary, but I renamed the `config.production.json` to `config.production.json.backup` and ran `sudo ghost update`

It WILL update, and it WILL give you and error about not finding the DB (This is ok cause the config.production.json is empty)

```
> sudo ghost update
✔ Checking for latest Ghost version
✔ Downloading and updating Ghost to v1.6.2
ℹ Stopping Ghost [skipped]
✔ Linking latest Ghost and recording versions
Running sudo command: -E -u ghost /usr/local/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /home/web/wrestling.irish-ghost/current
✖ Running database migrations
A ConfigError occurred.

Error detected in the production configuration.

Message: Invalid database username or password
Configuration Key(s): database.connection.user / database.connection.password
Current Value(s):  /

Help: Run `ghost config <key> <new value>` for each key to fix the issue.


Debug Information:
    Node Version: v6.9.1
    Ghost-CLI Version: 1.1.1
    Environment: production
    Command: 'ghost update'
```

Renamed the `config.production.json` back, ran `ghost start` and it complained about a file permission. 
At this point, while it complains about the file permissions, it STARTS and it WORKS! But I wanted ZERO errors. So I had to kill the service (`sudo systemctl status ghost_<blog-name>.service`) and then `sudo ghost start` which produced ZERO errors and is now working.

Have I put myself into trouble with permissions? Probably!

**While this method 'works', it is not an official fix and thus, execute at your own discretion.**

**Comment by tmack8001** [comment]
The way that I got around this is via correctly setting up the systemctl files as this process is different on Ubuntu vs Debian linux distributions.

 Here is the command I executed to set up the systemd services for debian and after this ghost-cli commands to interact with a running ghost blog just worked and no more of these yargs.js errors.

```
sudo ln -sf /var/www/ghost/myblog.com/system/files/ghost_myblog-com.service /etc/systemd/system/ghost_myblog-com.service
```

_**obviously** replacing /var/www/host/myblog.com with the path to your ghost installation_

**Comment by DeastinY** [comment]
Hey,
just wanted to chime in. I'm running into the exact same errors (on Debian as well), but did not get any of the solutions to work yet :disappointed:

**Comment by AileenCGN** [comment]
Closing this for now as it doesn't seems to appear on the [recommended stack](https://github.com/TryGhost/Ghost-cli#recommended-stack) and therefore is not high priority to fix. Community PRs are always welcome!
