### ISSUE TITLE
Ghost Cli throw error `Config file is not valid JSON`

### ISSUE THREAD

**Issue by ittus** [TryGhost/Ghost-CLI#436]
### This issue is a

* [x] Bug Report

### Summary

Ghost doctor throw `Config file is not valid JSON`, while `config.production.json` is valid
```
{
	"url": "http://*****.com",
	"server": {
		"port": 2368,
		"host": "127.0.0.1"
	},
	"database": {
		"client": "mysql",
		"connection": {
			"host": "localhost",
			"user": "ghost-657",
			"password": "prodpassword",
			"database": "proddatabase"
		}
	},
	"mail": {
		"transport": "SMTP",
		"options": {
			"service": "Mailgun",
			"auth": {
				"user": "postmaster@sandboxb20cf1391a9c744b72a320e83022f4.mailgun.org",
				"pass": "5ca2eff1231ee123fe2f96333199502b3aa96ac"
			}
		}
	},
	"logging": {
		"transports": [
			"file",
			"stdout"
		]
	},
	"process": "systemd",
	"paths": {
		"contentPath": "/var/www/ghost/content"
	}
}
```

### Steps to Reproduce (for a bug report)

1. Install ghost 1.5.2 in /var/www/ghost
2. Run ghost in production mode
3. Run `ghost doctor startup`
4. Receive error:
```
✖ Validating config
A ConfigError occurred.

Error detected in the undefined configuration.

Message: Config file is not valid JSON

Debug Information:
    Node Version: v6.11.2
    Ghost-CLI Version: 1.0.3
    Environment: production
    Command: 'ghost doctor startup'
```

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04
* Node Version: 6.11.2
* Ghost-CLI Version: 1.0.3
* Environment: production
* Command: ghost doctor startup

**Comment by acburdine** [comment]
@ittus does this occur on `ghost start`, or just when you run `ghost doctor startup`?

**Comment by acburdine** [comment]
Can confirm.

**Comment by ittus** [comment]
Just `ghost doctor startup`, `ghost start` works fine
