### ISSUE TITLE
Install loading state

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost-CLI#446]
Is a loading bar / static loading line possible? Cause this is a little crazy :) 
![image](https://user-images.githubusercontent.com/120485/29284896-746fcdce-8124-11e7-8cfd-314ad990c65f.png)

**Comment by acburdine** [comment]
@JohnONolan a bar isn't super possible as it depends on several different tasks running - makes it pretty complex to implement.

The reason this is occurring is because your terminal width is too short - I'll see if I can't find a better way to avoid this issue in the future.
