### ISSUE TITLE
ghost install default database name causes installations to share a database instance

### ISSUE THREAD

**Issue by TomChantler** [TryGhost/Ghost-CLI#453]
### This issue is a

* [x] Bug Report
* [x] Feature Request

### Summary

If you run `ghost install` (to do a production installation) then it prompts you to create a mysql database called `ghost_production`.

If you run another installation, it also suggests the same database name. When I accepted the default twice in a row, I ended up with two blog installations sharing the same database and chaos ensued.

I reckon it would be better to include some kind of identifier in the default database name, so I can (probably) accept the defaults. Given the point in time at which the default prompt values are calculated, it's best to use the local folder name. e.g. if you are installing in `/var/www/tom` then the database name should be `ghost_production_tom`.

I have already fixed this in my branch.

### Steps to Reproduce (for a bug report)

1. run `ghost install` and accept the default database name
2. repeat without changing the database name.

I reckon this is *kind of* a bug. It's certainly kinder if we offer a default name which is more likely to be unique. Making it definitely be unique is quite complicated and is a possible future enhancement.

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: 
* Node Version:
* Ghost-CLI Version: 
* Environment: 
* Command:

**Comment by acburdine** [comment]
Sounds like a good solution 👍  care to make another PR for it?
