### ISSUE TITLE
Can't install in production only in local

### ISSUE THREAD

**Issue by Hiobi** [TryGhost/Ghost-CLI#456]
### This issue is a

* [X] Bug Report

### Summary

The command `ghost install` return the following errors, that doesn't appear in local install.

### Steps to Reproduce (for a bug report)

1. command: `ghost install` for production

Logs: https://gist.github.com/Hiobi/21d7c8ae1439fcfb05544fe61465afba

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Debian 8
* Node Version: 6.11.2
* Ghost-CLI Version: 1.1.1
* Environment: production
* Command: ghost install

Thanks ! :)

**Comment by ErisDS** [comment]
ECONNREFUSED 127.0.0.1:3306

This is telling you that it cannot connect to your MySQL server. I have added an explanation and recovery steps to the [troubleshooting guide](https://docs.ghost.org/v1/docs/troubleshooting#section-error-connect-econnrefused-127-0-0-1-3306).

**Comment by Hiobi** [comment]
Hi Hannah,
I already checked my MySQL connection, all seems ok. For proof, in "local installation" mode, it's works. the blog is online and I can access to it.

**Comment by ErisDS** [comment]
Local installs use sqlite3, not mysql, which is why you don't get errors from MySQL.

**Comment by Hiobi** [comment]
oh ok ! In local, it's asking for MySQL infos  too, I was dubbed. 
But my MySQL server run, it's accessible with the same credentials I use for Ghost installation.

**Comment by Hiobi** [comment]
oh ok ! In local, it's asking for MySQL infos  too, I was dubbed. 
But my MySQL server run, it's accessible with the same credentials I use for Ghost installation.
