### ISSUE TITLE
Request: logging without special characters

### ISSUE THREAD

**Issue by SparkyDoosan** [TryGhost/Ghost-CLI#457]
* [X ] Feature Request

### Summary

Called from a (crontab) shell script, verbose logging provides details on the result of a command like `ghost start -V --no-prompt` but extra (ANSI?) characters clutter the log file:

`~\~T Starting Ghost`

The log would be easier to review if --no-prompt (or another switch) suppressed the extra characters.

### Steps to Reproduce (for a bug report)

#!/bin/bash
LOGFILE=ghost.log
exec 1>>${LOGFILE} 2>&1
ghost start -V --no-prompt

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Linux 
* Node Version: 6.11.1
* Ghost-CLI Version: 1.1.0
* Environment: nvm 0.33.2
* Command: ghost start -V --no-prompt

... small stuff but on my mind this morning, thanks!

**Comment by ErisDS** [comment]
I totally understand where you're coming from on this. As it's non-critical, it's unlikely to be prioritised by us, but it is 100% the kind of thing that we'd love to see PRs for 😁

**Comment by vikaspotluri123** [comment]
This is on my radar but I'm not sure when I will be able to get to it. This is what I'm thinking needs to be done: 

-  Add global option (--no-color) which defaults to false
-  Pass info to UI constructor ([line 175](https://github.com/TryGhost/Ghost-
CLI/blob/master/lib/command.js#L175))
-  Add color property to UI class
-  Check if should be colorful ([line 245](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/ui/index.js#L245))

**Comment by vikaspotluri123** [comment]
So it turns it [chalk](https://www.npmjs.com/package/chalk#chalksupportscolor) (the upstream library ghost-cli uses to colorfully log) already supports this - add the `--no-color` flag, and you shouldn't have any extraneous characters. Can you verify this is works and achieves what you're trying to do @SparkyDoosan?
