### ISSUE TITLE
Unable to install with DS_Store on OSX

### ISSUE THREAD

**Issue by CyberStrike** [TryGhost/Ghost-CLI#459]
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

Unable to install in a `"empty"` directory on OSX. 

```bash
~/P/ghost ❯❯❯ ls -al                                                                                                                                                            
.
..
.DS_Store
~/P/ghost ❯❯❯ ghost install local

A SystemError occurred.

Message: Current directory is not empty, Ghost cannot be installed here.

```

### Steps to Reproduce (for a bug report)

1. Create a folder and wait a few minutes or access it using finder. OSX will createa .DS_Store file.
2. `ghost install local`

Installer should ignore .DS_Store files for system OSX.

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: OSX Sierra ( 10.12.6 )
* Node Version: 6.9.5
* Ghost-CLI Version: 1.1.1
* Environment: Production
* Command: 'ghost install local'

**Comment by acburdine** [comment]
So the only time a .DS_Store file is created is if you access it via Finder - it caches the thumbnails for all the items in the directory. Windows has a similar Thumbs.db file.

I'm hesitant to special-case that file though - I'm not sure if .DS_Store and Thumbs.db are the only two system-level files or if there are more that would have to be added to the check.

A fix is to remove that .DS_Store file manually using the command line. Also in the future, if you run `ghost install local --dir /path/to/intended/install/dir`, it will create the empty install folder for you if it doesn't exist, meaning you don't have to create it through Finder.

**Comment by acburdine** [comment]
Gonna close this as a wontfix for now - if enough people have this issue then we can reopen.
