### ISSUE TITLE
ghost doctor fails to recognize alternate SES settings

### ISSUE THREAD

**Issue by alikuru** [TryGhost/Ghost-CLI#467]
Transferring issue here from [#8952](https://github.com/TryGhost/Ghost/issues/8952).
--
I noticed this error when I wanted to test my config after I upgrading to 1.8.0.

```
✖ Validating config
A ConfigError occurred.

Error detected in the production configuration.

Message: Invalid mail transport
Configuration Key(s): mail.transport
Current Value(s): SES

Help: Run `ghost config <key> <new value>` for each key to fix the issue.


Debug Information:
    Node Version: v6.9.2
    Ghost-CLI Version: 1.1.1
    Environment: production
    Command: 'ghost doctor startup'
```

My SES config is as follows;

```
"mail": {
  "from": "'John Doe' <john@doe.com>",
  "transport": "SES",
  "options": {
    "AWSAccessKeyID": "AWSACCESSKEY",
    "AWSSecretKey": "/AWS/SECRET"
  }
}
```

I'm using `pm2` to run Ghost and everything, including emails, seem to work. So, I assume this must be an issue with the `doctor`.

**Comment by adriaan-pelzer** [comment]
Is there any way ghost can be started without running ghost doctor?
I want to use SES, and it works, but I can't start ghost because of this issue.

**Comment by luizkowalski** [comment]
same issue here:

```
A ConfigError occurred.

Error detected in the production configuration.

Message: Invalid mail transport
Configuration Key(s): mail.transport
Current Value(s): SES

Help: Run `ghost config <key> <new value>` for each key to fix the issue.


Debug Information:
    Node Version: v6.11.2
    Ghost-CLI Version: 1.1.2
    Environment: production
    Command: 'ghost start'
```

**Comment by adriaan-pelzer** [comment]
I've had to fix it as follows:
In lib/commands/config/advanced.js: find the array: ['smtp', 'sendmail', 'direct'] and add 'ses', to make it ['smtp', 'sendmail', 'direct', 'ses']
