### ISSUE TITLE
Ghost start is lacking env flags

### ISSUE THREAD

**Issue by BiosElement** [TryGhost/Ghost-CLI#470]
I'm attempting to setup a dev environment on Cloud9 and cannot pass the proper env flags to Ghost through the Ghost CLI, nor can I set a variable via JSON as it requires a numerical value to be valid JSON.

While this situation is unique to me, I can't imagine I'm the only one that needs to launch Ghost using various configuration flags and as far as I can tell simply npm start no longer works, although perhaps I'm doing something wrong.

**Comment by ErisDS** [comment]
@BiosElement Can you please explain your problem in more detail, giving a reproduction case and the technical details requested in the issue template?

**Comment by acburdine** [comment]
@BiosElement if you look at the docs [here](https://docs.ghost.org/v1/docs/config#section-running-ghost-with-config-env-variables), it explains how to run ghost with environment variables. I'm not sure what issue you're running into with that - as was said please provide more information :)

**Comment by BiosElement** [comment]
Looks like I was being a tad slow. Thanks for the help!
