### ISSUE TITLE
Let user choose between nginx and caddy or just make caddy as default

### ISSUE THREAD

**Issue by fakeid30** [TryGhost/Ghost-CLI#473]
### This issue is a

- [x] Feature Request

### Summary

I propose to integrate [Caddy](https://caddyserver.com/) as a reverse proxy or use Caddy as the main server for ghost-cli installation. It [can already be done](https://github.com/sayem314/Ghost-over-Caddy) on the LTS branch. And it removes the need to install and configure certbot. 

Please do think about it!

**Comment by acburdine** [comment]
@fakeid30 While Caddy does seem like a neat project, it's not something we'll pull into the core of Ghost-CLI. The recommended system stack was chosen for a reason, as is outlined in the docs [here](https://docs.ghost.org/docs/hosting#section-why-this-stack-). For Caddy specifically, there does not appear to be a defined and "officially supported" way of setting it up in production. There are unofficial ways yes, which may work fine - but the main issue is that for non-technical users they would have to download & install caddy, then download and set up the systemd script for caddy and get that going, all before actually running `ghost install`. For nginx, all you have to run (on ubuntu at least) is `sudo apt-get install nginx`.

All that said, it is possible to build CLI extensions (though they're not well documented). There's a couple of examples [here](https://github.com/vikaspotluri123/ghost-cli-supervisor) and [here](https://github.com/acburdine/ghost-cli-pm2), and the extensions directory inside the ghost-cli codebase itself has examples of extensions. It should be fairly simple to create a caddy extension that works with the CLI.

(As a sidenote too - Ghost-CLI doesn't require installing/configuring certbot, it uses acme.sh which has far fewer setup requirements)
