### ISSUE TITLE
Installing v1.1.1 throws `two version of Node` error

### ISSUE THREAD

**Issue by lersh** [TryGhost/Ghost-CLI#476]
### This issue is a

* [x] Bug Report

### Summary

Tried installing v1.1.1 in a vagrant environment using nvm and node v6.11.1 today and causes the following error:

[08:11:36] Checking system Node.js version [started]
[08:11:37] Checking system Node.js version [failed]
[08:11:37] → The version of Ghost-CLI you are running was not installed with this version of Node.
This means there are likely two versions of Node running on your system, please ensure
that you are only running one global version of Node before continuing.

### Steps to Reproduce (for a bug report)

1. sudo mkdir -p /var/www/ghost
2. sudo chown ghost:ghost /var/www/ghost
3. cd /var/www/ghost
4. ghost install

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: ubuntu 16.10
* Node Version:v6.11.1
* Ghost-CLI Version: 1.1.1
* Environment: production
* Command: 'ghost install'

**Comment by lersh** [comment]
ghost@vultr:/var/www/ghost$ npm bin -g
/usr/bin
ghost@vultr:/var/www/ghost$ npm root -g
/usr/lib/node_modules
ghost@vultr:/var/www/ghost$ which ghost
/usr/local/bin/ghost
ghost@vultr:/var/www/ghost$ ll /usr/local/bin/ghost 
lrwxrwxrwx 1 root root 39 Sep 13 08:01 /usr/local/bin/ghost -> ../lib/node_modules/ghost-cli/bin/ghost*
ghost@vultr:/var/www/ghost$

**Comment by acburdine** [comment]
@lersh looking at it it _does_ look like you have two versions of Node installed, if you use nvm globally with a system-installed version of Node then things have the tendency to not work correctly.

My guess is the system-installed (e.g. `apt-get install nodejs`) version is what's currently active, as `npm bin -g` returns /usr/bin - but ghost-cli was installed with the nvm-installed version of node (because its binary is currently in `/usr/local/bin`).

Can you try removing nvm and running `ghost install` again?

**Comment by lersh** [comment]
@acburdine I tried to reinstall `ghost-cli v1.0.3`,it works!
I will try to remove nvm and running `ghost install` tomorrow.
thank you for replying.

**Comment by lersh** [comment]
@acburdine I tried to remove nvm,but it told me there is no nvm.
`root@vultr:~# apt remove nvm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nvm`

**Comment by acburdine** [comment]
right, so the reason ghost 1.0.3 works is the check for multiple Node versions was added in ghost-cli 1.1.0 😉 

so something you might also try doing is running `/usr/local/bin/npm uninstall -g ghost-cli`. That will (probably) uninstall the nvm-managed version of ghost-cli and allow you to then run `npm install -g ghost-cli` to install Ghost-CLI in the right place.

(As to why you can't "remove" nvm - it's a bash script and not installed via apt)

**Comment by acburdine** [comment]
@lersh it does look like you ran into the error as it was intended to occur - you installed ghost-cli with a different version of node than what you're running it with.

If the change I suggested previously doesn't work, you might try swinging by our [slack channel](https://slack.ghost.org) and asking for help there. If we find that this is an issue with the CLI and not a system-specific issue, then we can reopen this 😄
