### ISSUE TITLE
Cannot set port with ghost install

### ISSUE THREAD

**Issue by karltk** [TryGhost/Ghost-CLI#479]
### This issue is a

* [x] Bug Report

### Summary

The `--port` option to `ghost install` appears to be ignored.

### Steps to Reproduce (for a bug report)

1. Run `ghost install --port 8080`
2. Look inside the `config.production.json`, where the port is always set to 2368

I would expect the `port` attribute in the `server` section to be set to 8080. Same behaviour whether I enable configuration of `nginx` or not. 

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04 LTS
* Node Version: v6.11.3
* Ghost-CLI Version: 1.1.1

(No error occurred).

**Comment by acburdine** [comment]
Good catch! I can definitely confirm this, will fix in the next version.
