### ISSUE TITLE
ghost update tries to restart Ghost

### ISSUE THREAD

**Issue by ePirat** [TryGhost/Ghost-CLI#481]
### This issue is a

* [ ] Bug Report
* [x] Feature Request

### Summary

Currently there seems no way to use `ghost update` without it trying to restart ghost.
In my setup this can't work as ghost cli does not correctly work with systemd on debian (neither do I want it to mess around with it anyway, but manage it all myself)

Therefore an option like for `ghost install`, which has (`--no-start`), would be really useful for `ghost update` too.

**Comment by acburdine** [comment]
My initial response is to say build a ghost-cli extension so that `ghost start`/`ghost stop` can integrate with whatever process manager you're using.

However, this isn't a bad idea - I'll work on implementing it and getting it into the next version 😄

**Comment by MertcanGokgoz** [comment]
Hello

i use systemd based ghost service but every update command error this and this section needs to be automated

```
Message: Port '2368' is in use.
Configuration Key(s): server.port
Current Value(s): 2368
```

why it is not automatic this `systemctl restart ghost_site.service` 

full log

```
root@local:/var/www/ghost# ghost update
✔ Checking for latest Ghost version
✔ Downloading and updating Ghost to v1.9.1
ℹ Stopping Ghost [skipped]
✔ Linking latest Ghost and recording versions
Running sudo command: -E -u ghost /usr/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-09-26 17:45:56] INFO Finished database migration!
✔ Running database migrations
✖ Validating config
✖ Restarting Ghost
A ConfigError occurred.

Error detected in the production configuration.

Message: Port '2368' is in use.
Configuration Key(s): server.port
Current Value(s): 2368

Help: Run `ghost config <key> <new value>` for each key to fix the issue.


Debug Information:
    Node Version: v6.11.3
    Ghost-CLI Version: 1.1.1
    Environment: production
    Command: 'ghost update'

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
root@local:/var/www/ghost# systemctl restart ghost_mertcangokgoz-com.service
```

**Comment by imzhengfei** [comment]
I meet the same problem on **CentOS 7** with **Ghost-CLI v1.2.0**

```shell
[root@web ghost]# ghost -v
Ghost-CLI version: 1.2.0
Ghost Version (at /home/www/ghost): 1.16.0
[root@web ghost]# ghost update
Process manager 'systemd' will not run on this system, defaulting to 'local'
✔ Checking for latest Ghost version
✔ Downloading and updating Ghost to v1.17.0
ℹ Stopping Ghost [skipped]
✔ Linking latest Ghost and recording versions
Running sudo command: /usr/local/share/.config/yarn/global/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /home/www/ghost/current
✔ Running database migrations
✖ Validating config
✖ Restarting Ghost
A ConfigError occurred.

Error detected in the production configuration.

Message: Port '2368' is in use.
Configuration Key(s): server.port
Current Value(s): 2368

Help: Run `ghost config <key> <new value>` for each key to fix the issue.


Debug Information:
    Node Version: v6.11.5
    Ghost-CLI Version: 1.2.0
    Environment: production
    Command: 'ghost update'

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
[root@web ghost]# ghost stop
A SystemError occurred.

Message: No running Ghost instance found here.

Debug Information:
    Node Version: v6.11.5
    Ghost-CLI Version: 1.2.0
    Environment: production
    Command: 'ghost stop'

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

**Comment by abhinavdasin** [comment]
Atlast Ghost-Cli is updated and ssl issues are fixed at promptly, [wishes](wishes.in.net) to the team who put this effort to bring best experiences to ghost users.

**Comment by acburdine** [comment]
Added a `--no-restart` option to `ghost update` that will be released with the next version 👍

**Comment by ePirat** [comment]
Thanks!

**Comment by ePirat** [comment]
So I've just tried that and it does not really behave as I would expect… I get:

```
Running sudo command: systemctl is-active ghost_foo
```

It should not do that, IMHO, when I supply no-restart, as I want to handle all of that myself, ghost-cli should not try to talk to what it thinks is the service manager that I use, but instead let me take care of starting/stopping ghost.

I get ghost-cli tries to automate all the things but it would be great if I could manage the whole service stuff myself, please. (I do not want to write my own ghost-cli extension to make it integrate with the way I manage my services)
