### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by aswordok** [TryGhost/Ghost-CLI#484]
OS:centos 7 x64
Node Version: v6.9.5
Ghost-CLI Version: 1.0.0-beta.1
ghost version:v1.8.6
mysql:mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

Before update to 1.10.0,it work well.

[root@xxx ghost]# ghost update
Process manager 'systemd' does not exist, defaulting to 'local'
✔ Checking for latest Ghost version
All up to date!
[root@xxx ghost]# ghost version
Ghost-CLI version: 1.0.0-beta.1
Ghost Version (at /mnt/myData1/ghost): 1.10.0
[root@xxx ghost]# ghost start
Process manager 'systemd' does not exist, defaulting to 'local'
✔ Validating config
✖ Running database migrations
An error occurred.
Message: 'Please provide a file named MigratorConfig.js in your project root.'

Debug Information:
    Node Version: v6.9.5
    Ghost-CLI Version: 1.0.0-beta.1
    Environment: production
    Command: 'ghost start'

Additional log info available in: /root/.ghost/logs/ghost-cli-debug-2017-10-02T16_49_42_639Z.         log
[root@xxx ghost]# reboot
[root@xxx ghost]# ghost start
Process manager 'systemd' does not exist, defaulting to 'local'
✔ Validating config
✖ Running database migrations
An error occurred.
Message: 'Please provide a file named MigratorConfig.js in your project root.'

Debug Information:
    Node Version: v6.9.5
    Ghost-CLI Version: 1.0.0-beta.1
    Environment: production
    Command: 'ghost start'

Additional log info available in: /root/.ghost/logs/ghost-cli-debug-2017-10-02T16_52_08_339Z.         log
[root@xxx ghost]# cat /root/.ghost/logs/ghost-cli-debug-2017-10-02T16_52_08_339Z.         log
cat: /root/.ghost/logs/ghost-cli-debug-2017-10-02T16_52_08_339Z.: No such file or directory
cat: log: No such file or directory
[root@xxx ghost]#

**Comment by aswordok** [comment]
After use --force:
ghost update --force
Now it work again.

**Comment by acburdine** [comment]
it looks like you're on an old version of the CLI - would you mind updating to the latest version and seeing if it fixes your issue?

(You'll also have to go through some more steps - see the docs [here](https://docs.ghost.org/v1/docs/upgrade#section-upgrading-ghost-installs-that-used-ghost-cli-1-0-0))

**Comment by aswordok** [comment]
when I use:
npm i -g ghost-cli@latest
update to 1.1.1,it can't work well,it give a error:
✖ Running database migrations
An error occurred.

Now I have rollback to Ghost-cli v1.0.0-beta.1+ghost v1.10.0,and it work well again.

**Comment by acburdine** [comment]
@aswordok so Ghost-CLI 1.0.0-beta.1 had _many_ changes before Ghost-CLI 1.0.0 final - so much so that you'll likely have to re-create your installation. (which should have been output when you ran `ghost update`).

As such, I'm going to close this issue. If you still run into issues with the current version of Ghost-CLI (on an install created with Ghost-CLI 1.0.0RC.1 or later), then we can reopen this 😄
