### ISSUE TITLE
Nginx dhparam file is generated each time

### ISSUE THREAD

**Issue by bery** [TryGhost/Ghost-CLI#487]
### This issue is a

* [x ] Feature Request

### Summary

Dhparam file for nginx SSL configuration is generated each time when SSL certificate is issued for a site installed using ghost cli which takes a huge amount of time

### Steps to Reproduce (for a bug report)

1. Install multiple sites without using SSL
2. Enable SSL support per site

Proposal: Create one dhparam file and use it across all the sites, for example `/etc/ssl/dhparam.pem`

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04
* Node Version: 6.x
* Ghost-CLI Version: 1.1.1 
* Environment: Production
* Command: ghost setup ssl --sslemail={{ ghost_letsencrypt_user }} --no-prompt

**Comment by acburdine** [comment]
@bery yup this makes sense - I originally had thought that it was better, security-wise, to have a unique dhparam for each site, but after reading some more into it it looks like it's fine to only generate it once.

I'll take care of this alongside #469.
