### ISSUE TITLE
Adapter Installs

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#49]
With Ghost 0.10 came an update in how storage adapters were handled. The update made it a requirement that all storage adapters for Ghost extend from a base adapter. However, there is no set standard way to install a ghost storage adapter - the only requirement is that it be in the `/content/storage` folder and have some config parameters be set up.

With Ghost-CLI comes an opportunity to standardize adapter installs, as well as provide for additional benefits such as prompting for various config parameters upon install.

While the standard for adapter installation is still a bit of a WIP, the each storage adapter will need to follow these standards for sure:
- The adapter **MUST** be a published npm module
- The adapter **MUST** extend the Ghost Base Storage adapter (whether or not it will need to have a separate ghost storage adapter npm module as a dependency is still TBD)

`ghost install-adapter <adapter-name>` will download and setup a particular adapter. It will initially add it to the config as the configured storage adapter, and there will (likely) be a hook that each storage adapter can use to prompt for different config variables upon install, and check the existence of on `ghost start`.

**Comment by acburdine** [comment]
Gonna start playing around with an implementation of this over at https://github.com/acburdine/ghost-cli-adapter-install

**Comment by acburdine** [comment]
this might still be useful for CLI v2

**Comment by ErisDS** [comment]
Nah, it's a huge feature with absolutely zero demand :)
