### ISSUE TITLE
Node.js version check is not compatible with yarn installation

### ISSUE THREAD

**Issue by vilic** [TryGhost/Ghost-CLI#497]
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

https://github.com/TryGhost/Ghost-CLI/blame/b5f9c448976f6c753d95c925db70be88b542cf44/lib/commands/doctor/checks/install.js#L42

In my case, `npm bin -g` is `/usr/bin` while `yarn global bin` is `/usr/local/bin`

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04
* Node Version: 6.11.4
* Ghost-CLI Version: 1.1.3
* Environment: 
* Command: `ghost-cli install`

**Comment by imzhengfei** [comment]
@vilic 
You can try to use this command to change yarn global bin:
```shell
yarn config set prefix /usr
```
and then:
> [root@web blog]# yarn global bin
> /usr/bin

This method solved my installing problem about the "two node version ...".

**Comment by acburdine** [comment]
Gonna close this issue as some changes in Ghost-CLI 1.3.0 removed the need for the "two versions of node" check, and thus the error.

If you're trying to use ghost-cli extensions then a yarn install won't work (unless you set the prefix to `/usr`), but for most cases it should work fine.
