### ISSUE TITLE
Current issues with updating

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#50]
Warning, I'm not sure of the status of these 2 bugs, they might be fixed in the unreleased master?

1. I get the following error when trying to run `ghost update` in a folder where I've already updated:

![](https://puu.sh/rwpWh.png)

2. @frantzypants is getting this error when trying to update:

![screen shot 2016-10-03 at 12 07 20 pm](https://cloud.githubusercontent.com/assets/101513/19044538/aa808164-898c-11e6-99c5-4bf556755170.png)

Would be awesome if these are fixed before alpha.3 as both of us are stuck ;)

**Comment by acburdine** [comment]
The first one is a known issue and will be fixed by #48. The second is an issue I haven't seen before but know what's causing it and will implement a fix in alpha 3

**Comment by acburdine** [comment]
Reopening because this wasn't actually fixed :/
