### ISSUE TITLE
ProcessError occurred running database migrations to v1.13.0 and SQLite

### ISSUE THREAD

**Issue by Vadorequest** [TryGhost/Ghost-CLI#500]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

I'm running a `ghost update` inside a Docker container.

```bash
root@vps312528:~# docker exec -it blog bash
bash-4.3# ghost update
✔ Checking for latest Ghost version
✔ Downloading and updating Ghost to v1.13.0
ℹ Stopping Ghost [skipped]
✔ Linking latest Ghost and recording versions
✖ Running database migrations
A ProcessError occurred.

Error occurred running command: 'undefined'

Debug Information:
    Node Version: v6.11.4
    Ghost-CLI Version: 1.1.2
    Environment: production
    Command: 'ghost update'
```

Maybe it's related to the fact I'm using SQLite? Or Docker?  (it shouldn't be related to Docker)

I still get this message in my dashboard, even though there is no visible bug yet.

> Ghost 1.13.0 is available! Hot Damn. Click here to upgrade.

**Comment by kirrg001** [comment]
@acburdine FYI: I've tested the migration from 1.12 to 1.13 using sqlite.

**Comment by Vadorequest** [comment]
I tried something else, instead of updating my previous version of Ghost through the CLI, I tried installing the latest ghost:1.13.0-alpine docker image, and load it with my sqlite DB from Ghost 1.12.1. It fails.

`Undefined binding(s) detected when compiling SELECT query: select "clients".* from "clients" where "clients"."slug" = ? limit ?`

![image](https://user-images.githubusercontent.com/3807458/31494872-7a60de1c-af55-11e7-819d-7e915065cf19.png)

I guess I should run a migration of the DB first? How do I do that?

**Comment by acburdine** [comment]
@Vadorequest can you try this again with the latest ghost-cli? there were some migration fixes in that version that should hopefully fix your issue.

Ultimately I'm gonna close this though - as if it doesn't work after that it's likely related to the fact that you're trying to update ghost within a docker image, which (technically) isn't supported. Instead you should likely swap out the image for the updated image, at which point migrations will be automatically run on container start.
