### ISSUE TITLE
ENOENT: Error occurred running command: 'yarn info ghost versions --json'

### ISSUE THREAD

**Issue by DiegoRBaquero** [TryGhost/Ghost-CLI#504]
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

Received a yarn error while using npm. I do not have yarn and I don't plan to use it.

### Steps to Reproduce (for a bug report)

Install Ghost CLI, install ghost locally using `ghost install local`

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

Error
```
A ProcessError occurred.

Error occurred running command: 'yarn info ghost versions --json'

Exit code: ENOENT
```

* OS: Mac OS Sierra
* Node Version: v6.11.4
* Ghost-CLI Version: 1.1.2
*  Environment: development
*  Command: 'ghost install local'

Full log:

```
ghost install local
✔ Checking system Node.js version
✔ Checking current folder permissions
ℹ Checking operating system [skipped]
ℹ Checking MySQL is installed [skipped]
✖ Checking for latest Ghost version
A ProcessError occurred.

Error occurred running command: 'yarn info ghost versions --json'

Exit code: ENOENT


Debug Information:
    Node Version: v6.11.4
    Ghost-CLI Version: 1.1.2
    Environment: development
    Command: 'ghost install local'

Additional log info available in: /[...].log

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

**Comment by DiegoRBaquero** [comment]
Solved reinstalling CLI npm module: `npm uninstall -g ghost-cli && npm install -g ghost-cli@latest`

**Comment by vikaspotluri123** [comment]
FYI the CLI uses yarn to install ghost in the background 😄

**Comment by DiegoRBaquero** [comment]
@vikaspotluri123 I know, but it is a dependency of the CLI, users are not required to have it (See https://github.com/TryGhost/Ghost-CLI/issues/160#issuecomment-282129636). However, I was being required to have it (for some reason). Reinstalling the global CLI module fixed it :)

**Comment by alexxsanchezm** [comment]
Just to for further users that may come up with this issue. I solve this issue in basically 5 steps

1. Uninstalling ghost-cli.
2. Removing cmdtest `sudo apt remove cmdtest`
3. Instaling yarn, [see for installing yarn](https://yarnpkg.com/en/docs/install)
4. Installing ghost-cli: `sudo npm i -g ghost-cli@latest`
5. Install ghost as usual `ghost install`, sudo is optional here.

**Comment by mikkqu** [comment]
In my case /home/user/.config was not accessible from my user for some unknown reason.
So, this command fixed it for me:

`sudo chown -R user:user /home/user/.config`

**Comment by xobs** [comment]
The documentation is incorrect.  https://docs.ghost.org/docs/install#section-install-ghost-cli

As others have mentioned, you also need to install yarn.  The documentation should be updated to mention this, as simply doing `sudo npm i -g ghost-cli` is not enough.

**Comment by vikaspotluri123** [comment]
> As others have mentioned, you also need to install yarn. 

Yes, yarn is required for the CLI to function, but you don't need to explicitly install it - it's a dependency for the CLI, so when you run `sudo npm i -g ghost-cli@latest` it will be installed. This boils down to yarn doesn't need to explicitly be installed. In fact, there are multiple (I would guess a supermajority, but I have no data to back that up) self-hosted ghost installations (both local and production) which just use the CLI's dependency of yarn and work flawlessly, especially in the reccommended stack

> The documentation is incorrect

I don't think the installation documentation is incorrect. However, this might be useful in the [troubleshooting section](https://docs.ghost.org/docs#section-yarn-errors-while-running-ghost-install-or-ghost-update-) - feel free to suggest edits!

**Comment by xobs** [comment]
My issue was caused by something in ~/.cache/ that was causing Yarn to fail.  Removing that directory and re-running the command fixed the issues.

**Comment by boovius** [comment]
Fix for me was updating permissions as outlined in the following post: 

https://stackoverflow.com/questions/49529696/yarn-error-eaccess-permission-denied-scandir-home-ubuntu-config-yarn-link
