### ISSUE TITLE
Ghost update does not check for operation success before setting version flags

### ISSUE THREAD

**Issue by Windyo** [TryGhost/Ghost-CLI#514]
### This issue is a

* [X] Bug Report
* [ ] Feature Request

### Summary

Running ghost update tries to update ghost to the latest version.
If an error occurs during the update, ghost-cli will inappropriately set flags that the version is now the latest one, resulting in a partial update and multiple unique bugs depending on what was updated and what was not.

### Steps to Reproduce (for a bug report)

The easiest way to reproduce this is to cause an OoM error on upgrade.

1. Get a DigitalOcean droplet.
2. Start with the $5/month plan
3. Resize it to $20/month without increasing disk size
4. Install ghost as usual
5. Lower instance back to $5 a month
6. Start ghost. Ghost runs as expected with full functionality.
7. On new version release, run ghost update without resizing the disk
8. OoM error occurs (various errors can display, the most requent beeing yan install failed)
9. Run ghost update again
10. Ghost thinks it is at the latest version, even though it is only partially upgraded
11. There is no way to force a reinstall or update.

This will probably happen if anything interferes with the update process.
Could be solved by a --reinstall option.

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu
* Node Version: 6.11.2
* Ghost-CLI Version: 1.1.1 
* Environment: Nux
* Command: ghost update

**Comment by acburdine** [comment]
I can definitely see why this isn't ideal. However, there is a current way to achieve this with the current state of the CLI.

```sh
ghost update --rollback
ghost update --force
```

The first command will rollback to the last version you had before upgrading. The second will update again, forcing the update (which means it will remove the previously half-installed version.

**Comment by Windyo** [comment]
Ah cool. Could you add that to the "Troubleshooting" section of the wiki ? :) We can close this afterwards.

**Comment by vikaspotluri123** [comment]
@Windyo do you think this is [this](https://docs.ghost.org/docs/troubleshooting#section-general-update-error) enough? If not, feel free to suggest edits (there's a button / link near the top right of the page)!

**Comment by Windyo** [comment]
@vikaspotluri123 Seems to require a Readme account.

I would just change

> Update problems
If you upgraded with Ghost-CLI and something went wrong, you can always do
ghost update --rollback
To revert to the previous version, and get a working install again.

To

>Update problems
If you upgraded with Ghost-CLI and something went wrong, you can always do
ghost update --rollback
To revert to the previous version, and get a working install again.
You can always for the update again by using
ghost update --force
