### ISSUE TITLE
ghost-cli deleting config.production.json if mysql local root user is disabled

### ISSUE THREAD

**Issue by gompa** [TryGhost/Ghost-CLI#515]
### This issue is a

* [ x] Bug Report
* [ ] Feature Request

### Summary

when running ghost-run on a production install with mysql root password disabled 
the config.production.json gets wiped

which is an big issue when using auto generated ghost password , the password gets lost 

### Steps to Reproduce (for a bug report)

1. install and setup ghost with ghost-cli
2. run mysql_secure_installation
3. issue service ghost_installname stop
4. Issue ghost run in /var/www/ghost(or your install location)
5. wait for ghost to fail to start
6. cat config.production.json (in your ghost install directory)

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: ubuntu 16.04
* Node Version: v6.11.5
* Ghost-CLI version: 1.1.3

NAME: InternalServerError
CODE: ER_ACCESS_DENIED_ERROR
MESSAGE: The server has encountered an error.

**Comment by gompa** [comment]
hmm i cant reproduce this anymore, 
i think it was a combination of a dated node install and ghost-cli not being able to login as root

**Comment by kirrg001** [comment]
@gompa Thanks for coming back.

We can re-open this issue as soon as there is a new report and clear steps to reproduce.

@acburdine Feel free to re-open if you know how to reproduce or if you know what it is.
