### ISSUE TITLE
Git isn't documented as a prerequisite

### ISSUE THREAD

**Issue by paambaati** [TryGhost/Ghost-CLI#524]
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

If this is a bug, double-check and make sure there's not already an existing issue for it, then provide a quick summary of what error is occurring.

If this is a feature request, use this section to describe what feature you would like to see in the CLI, as well as a quick summary of any benefits or drawbacks you can think of if this feature is implemented.

### Steps to Reproduce (for a bug report)

1. Spin up new Ubuntu 16.04 box.
2. Follow all setup instructions to a tee.
3. Reach LetsEncrypt step.
4. See error —

    ```
    ✖ Setting up SSL
    A ProcessError occurred.

    Error occurred running command: '/bin/sh -c git clone https://github.com/Neilpang/acme.sh.git /tmp/acme.sh'

    Exit code: 127
    ```
I was able to complete installation after installing `git`. I think `git` should be included as an installation pre-requisite in the docs. If you guys need a PR, I will gladly send one!

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04
* Node Version: 8.9.1
* Ghost-CLI Version: 1.2.0
* Environment: production
* Command: 'ghost install'

**Comment by vikaspotluri123** [comment]
I think we could avoid the additional requirement by downloading the archive instead of cloning (so insted it would be `wget / curl {args} https://github.com/Neilpang/acme.sh/archive/master.tar.gz &&  tar {args}`. This could either be replacement functionality, or a catch to git failing.

**Comment by acburdine** [comment]
@vikaspotluri123 that's a good idea - can fix it in the next version
