### ISSUE TITLE
ghost-cli on Windows

### ISSUE THREAD

**Issue by mineiro** [TryGhost/Ghost-CLI#53]
Hi guys!

After installing `ghost-cli` on Windows 10 as pointed out on http://support.ghost.org/v1-0-alpha/, I have tried to execute the `ghost install` command without success.

It outputs the following:

```
PS C:\Users\user\Code\ghost-blog> ghost install
spawn C:\Users\user\AppData\Roaming\npm\node_modules\ghost-cli\node_modules\.bin\npm ENOENT
```

Am I doing something wrong?

I'm using:

```
PS C:\Users\user\Code\ghost-blog> node -v
v6.6.0
PS C:\Users\user\Code\ghost-blog npm -v
3.10.3
PS C:\Users\user\Code\ghost-blog>
```

Thanks!

**Comment by ErisDS** [comment]
Hi there @mineiro,

Windows works completely differently to unix based systems. The intended target for running `ghost install` is linux/ubuntu (the recommended production environment) and it is being developed on mac. Those two systems are close enough that I would expect it to work on both.

We do want it to work on Windows eventually, but at this early stage, no work has yet been done to test or to add handling for Windows, where both the file system and the way commands are run are quite different.

We'd love some help though, we'd love some PRs providing windows support 👍

**Comment by VeldMuijz** [comment]
Had a discussion earlier with @acburdine and we think it might be a path related issue. I'm not able to reproduce this error because I can't run npm on the box I have right now.

@acburdine will check this out.

**Comment by maelgrove** [comment]
@mineiro,

If you still want to use the **ghost-cli** on Windows 10, you can take advantage of the *Windows Subsystem for Linux* a.k.a.  Bash on Ubuntu on Windows available on Windows 10 Versions build > 14393.

For activating Ubuntu on Windows, follow the instructions here:

https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

Then you can simply install node.js, Python > 2.7 and finally the **ghost-cli** (you also might need the *build-essentials* for baking Python).

![ghostwin](https://user-images.githubusercontent.com/22428830/27427622-eb7545e8-573f-11e7-90c8-066010554189.png)

**Comment by wes-mitre** [comment]
> Hi there @mineiro,
> 
> Windows works completely differently to unix based systems. The intended target for running `ghost install` is linux/ubuntu (the recommended production environment) and it is being developed on mac. Those two systems are close enough that I would expect it to work on both.
> 
> We do want it to work on Windows eventually, but at this early stage, no work has yet been done to test or to add handling for Windows, where both the file system and the way commands are run are quite different.
> 
> We'd love some help though, we'd love some PRs providing windows support 👍

Then why does the documentation state: 

"Prerequisites
To install Ghost locally you will need the following:
A computer running MacOS, Windows or Linux ... "

If Windows is not truly supported, the Prerequisites should list the Linux Subsystem requirement for Windows.  The user shouldn't learn about this only after typing in "ghost install" for the first time.  It's a little late.
