### ISSUE TITLE
ghost uninstall: DO NOT DESTROY EVERYTHING

### ISSUE THREAD

**Issue by wookayin** [TryGhost/Ghost-CLI#531]
### This issue is a

* Feature Request

### Summary

`ghost uninstall` removes everything in the ghost directory, including `.git` or any other additional files that were not created by Ghost.

The uninstall command runs as follows. It is not supposed to remove any files that are not a part of ghost instance, mentioned nowhere.

```
WARNING: Running this command will delete all of your themes, images, data, and any files related to this Ghost instance!
There is no going back!
? Are you sure you want to do this? Yes
ℹ Stopping Ghost [skipped]
Running sudo command: rm -rf /path/to/ghost/installation/content
```

### Steps to Reproduce (for a bug report)

(In a ghost dir, e.g. `ghost install`)

```
$ ghost install
$ git init   # (and some data exists in .git, etc.)
$ ls .git
.git
$ ghost uninstall
```

It should keep `.git` and other files other than ghost installation (`content`, `versions`, etc.), if any,
INTACT.

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Linux
* Node Version: 4.8.4
* Ghost-CLI Version: v1.2.1 & Latest
* Environment: -

**Comment by kirrg001** [comment]
> WARNING: Running this command will delete all of your themes, images, data, and any files related to this Ghost instance!

I think the warning is quite clear, it removes everything in this folder including your content. You can backup your data before running uninstall.

> It should keep .git

What is the use case to transform the Ghost installation folder into a git folder?

**Comment by acburdine** [comment]
@wookayin so I can see only removing the folders that the ghost installation creates. But, folders like content/versions/system ARE part of the instance, hence why `ghost uninstall` removes them.

I second @kirrg001's question though - what's the use-case for storing a ghost instance in git?

**Comment by wookayin** [comment]
Hi all, thanks for your response.

> .git

I was using git to keep track of the changes of a ghost instance, including **the sqlite3 database file** and some miscellaneous contents (*configuration*, themes, etc.). I admit that this would be not a standard case, but why not :) ?

> WARNING: Running this command will delete all of your themes, images, data, and any files related to this Ghost instance!

Having said that, I first understood the warning message as it is going to remove all content related to the Ghost instance. I presumed that it wouldn't remove any other auxiliary data or files that had been **not** created by Ghost but in the directory (e.g. `.git` or any additional shell scripts, etc.).

**Comment by acburdine** [comment]
That's fair - feel free to submit a PR and I'll get to it when I get a chance.
