### ISSUE TITLE
SSL issue on New Ghost site 

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost-CLI#533]
### This issue is on Ghost CMS SSL Installation

- Bug Report

## SSL issue

Hey I found some issues on Let's Encrypt SSL
I Install Let's Encrypt SSL While installing Ghost but the ISSUE is it works fine on NON-WWW version & Display SSL Warning + NET::ERR_CERT_COMMON_NAME_INVALID Error 
SSL Working fine on NON-WWW Version 
Does it install SSL for given URL or for both WWW & NON-WWW?
Is there any solution to FIX this ISSUE?

### Technical details 

* OS: Ubuntu 16.04 LTS
* Node Version:6.12.0
* Ghost-CLI Version: 1.2.1

**Comment by ErisDS** [comment]
Hi @mskian,

Ghost-CLI will setup SSL certificates for the domain you configure as your Ghost domain. It does not setup SSL for any other domains or subdomains, therefore it would not setup an SSL certificate for `www.` or `mail.` or any other subdomain you might think of.

If you want certificates for any other domains you'll need to do configure them yourself. You can either do this using the [acme.sh](https://github.com/Neilpang/acme.sh) tool that [Ghost-CLI uses](https://docs.ghost.org/docs/cli-knowledge-base#section-ssl) or you can use Ghost-CLI to generate both the certificate and the base nginx config as described [in the knowledgebase](https://docs.ghost.org/docs/cli-knowledge-base#section-ssl-for-additional-domains).

**Comment by jamesfacts** [comment]
FYI, I wrote a quick tutorial explaining the process of manually issuing a www cert and configuring the redirect: https://jamesfacts.com/configuring-ghost-and-ssl-with-a-www-redirect/

**Comment by mskian** [comment]
@jamesfacts @ErisDS  thanks for your Quick response let me and Update here :)

**Comment by mskian** [comment]
Thanks a Lot Fixed :100:  :+1:

**Comment by jamesfacts** [comment]
You're welcome, I'm glad it helped!
