### ISSUE TITLE
sqlite3 does not get installed

### ISSUE THREAD

**Issue by esafak** [TryGhost/Ghost-CLI#539]
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

ghost-cli does not install sqlite3, preventing proper installation of ghost itself when sqlite3 is used. However, if I manually install sqlite3 (following a #442 [comment](442#issuecomment-336343249)) from the `/usr/lib/node_modules/ghost-cli/node_modules` folder ghost installs properly.

### Steps to Reproduce (for a bug report)

`sudo npm install -g ghost-cli`

`cd /usr/lib/node_modules/ghost-cli/node_modules`
`sudo npm install sqlite3`

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04.3
* Node Version: 8.9.1
* Ghost-CLI Version: 1.2.1
* Environment: fish
* Command:

**Comment by acburdine** [comment]
@esafak I added a fix that will be released in Ghost-CLI 1.3.0 here shortly that should fix this issue.

Going to close this for now, if after testing with Ghost-CLI 1.3.0 you still run into this issue let me know and we can reopen this :)
