### ISSUE TITLE
Cron SSL not working

### ISSUE THREAD

**Issue by OllieCo** [TryGhost/Ghost-CLI#554]
Hi, I am having issues with my site. I have received help from Slack which has been amazing, but we hit a snag with the cron SSL.

We did the SSL migration correctly, and I was told to raise a ticket with the following information: 

 ```
crontab -l
11 0 * * * "/home/ocoady/.acme.sh"/acme.sh --cron --home "/home/ocoady/.acme.sh" > /dev/null
```
```
sudo crontab -l
47 0 * * * "/home/ocoady/.acme.sh"/acme.sh --cron --home "/home/ocoady/.acme.sh" > /dev/null
```
```
ghost migrate
✔ Checking for available migrations
No migrations needed :)
```

The context of the original issue was that my SSL certificates were not migrating. This lead to a mass of issues including permission issues, ngnix bugs, the works. But this was all ultimately resolved. We resolved all the above issues however, we now have issues with SSL cron. I'm not sure of how this all works, so I am not sure what else to explain.

**Comment by kirrg001** [comment]
I installed a ssl blog with 1.1.3. Then updated to 1.3.0 and ran `ghost migrate`.

> kirrg001@dev-kate-01:/var/www/ghost$ crontab -l
27 0 * * * "/home/kirrg001/.acme.sh"/acme.sh --cron --home "/home/kirrg001/.acme.sh" > /dev/null

(`sudo crontab -l` shows the same)

And shouldn't this cron point to /etc/letsencrypt?

**Comment by AileenCGN** [comment]
@kirrg001 I tried to reproduce this case, using Ghost-CLI@1.1.3 and Ghost@1.18.0, then upgrading the CLI to 1.3.0 and the migration worked fine for me:

![image](https://user-images.githubusercontent.com/8037602/34976332-b15f56fa-fac8-11e7-8445-fc4c1d5372a3.png)

**Comment by kirrg001** [comment]
If i run the migration from 1.1.3 -> 1.3 and my root crontab looks like this before the migration

> kirrg001@dev-kate-01:/var/www/ghost$ crontab -l
47 0 * * * "/home/kirrg001/.acme.sh"/acme.sh --cron --home "/home/kirrg001/.acme.sh" > /dev/null

> kirrg001@dev-kate-01:/var/www/ghost$ sudo crontab -l
47 0 * * * "/home/kirrg001/.acme.sh"/acme.sh --cron --home "/home/kirrg001/.acme.sh" > /dev/null

Then it won't work. I run `ghost update`, it succeeds and the new cron job (with the new acme location) doesn't get added. 

Not sure why @acburdine, @OllieCo and me had the cronjob configured for root? Ghost < 1.3 wasn't make use of the root crontab.

If i run `ghost update` and i ensure that `sudo crontab -l` doesn't have a cronjob for acme, it works.

Somehow this feels like an edge case to me.

Maybe we can add a check to `ghost doctor`, which checks that your cronjob is configured correctly. cc @acburdine

**Comment by acburdine** [comment]
Oh hmm...I wonder if something got run as root accidentally prior to the migration? that might be the reason the root crontab is configured.

**Comment by kirrg001** [comment]
> I wonder if something got run as root accidentally prior to the migration

Yeah wondered as well. 

> Maybe we can add a check to ghost doctor, which checks that your cronjob is configured correctly. cc @acburdine

What do you think about this idea?
It might be good to check, if ssl is enabled, to check if the cronjob is configured correctly.

**Comment by acburdine** [comment]
@kirrg001 yeah that's not a bad idea - the `ghost doctor` command hasn't yet been configured to pull doctor checks from extensions though - that would have to be done first as SSL support is an extension.

**Comment by AileenCGN** [comment]
> I wonder if something got run as root accidentally prior to the migration?

I _think_ I know why we're having this issue.

To reproduce: I deleted my crontab as well as my root crontab and installed (after uninstall) Ghost@1.18.0 with Ghost-CLI@1.1.3 to check what exactly is happening.

Before 1.2.0 we were not running the acme scripts with `sudo`, after 1.2.0, we are.

See here before: https://github.com/TryGhost/Ghost-CLI/blob/9d502ef9cf0d1a1a2bb522568fc72d99fbc2fdff/extensions/nginx/index.js#L143
And here after: https://github.com/TryGhost/Ghost-CLI/blob/master/extensions/nginx/acme.js#L59

When I installed freshly, my crontabs looked like this:
```
aileen@dev-aileen-01:/var/www/ghost$ crontab -l
37 0 * * * "/home/aileen/.acme.sh"/acme.sh --cron --home "/home/aileen/.acme.sh" > /dev/null
aileen@dev-aileen-01:/var/www/ghost$ sudo crontab -l
no crontab for root
```

After the migration it looks like this:
```
aileen@dev-aileen-01:/var/www/ghost$ crontab -l
37 0 * * * "/home/aileen/.acme.sh"/acme.sh --cron --home "/home/aileen/.acme.sh" > /dev/null
aileen@dev-aileen-01:/var/www/ghost$ sudo crontab -l
13 0 * * * "/etc/letsencrypt"/acme.sh --cron --home "/etc/letsencrypt" > /dev/null
```

Deleting the crontabs again, uninstalling Ghost and install again with current master results in these crontabs:
```
aileen@dev-aileen-01:/var/www/ghost$ crontab -l
no crontab for aileen
aileen@dev-aileen-01:/var/www/ghost$ sudo crontab -l
40 0 * * * "/etc/letsencrypt"/acme.sh --cron --home "/etc/letsencrypt" > /dev/null
```

Not sure, if this makes sense, but I thought I throw it in here.

I also found this one https://github.com/Neilpang/acme.sh/issues/1120#issuecomment-355747939 which suggests to use the command `acme.sh --uninstall-cronjob` so when running this with the user and not `root` it'll remove the old cronjob.

**Comment by AileenCGN** [comment]
@kirrg001 Can we close this in favour of #47 ?

**Comment by kirrg001** [comment]
> @kirrg001 Can we close this in favour of #47 ?

Yeah i think so. If the doctor command detects wrong crons (for sudo or non sudo), then it will for now manually tell you what todo - no need to automate i think.
