### ISSUE TITLE
Show help output when `ghost update` fails

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#562]
If i run `ghost update` and the database migrations fail, i am not getting a hint to run

`ghost update --rollback`

It would be great to show a little hint on the bottom.

CLI: master
Ghost: latest

**Comment by kirrg001** [comment]
Will take a look.

**Comment by theflofly** [comment]
@kirrg001 Thanks for this issue, I was struggling because of a failed migration until I saw your comment about `ghost update --rollback` that solved the problem.
