### ISSUE TITLE
`ghost -v` breaks programatic upgrade

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#565]
If I run `ghost -v` I get:

```
You are running an outdated version of Ghost-CLI.
It is recommended that you upgrade before continuing.
Run `npm install -g ghost-cli@latest` to upgrade.

? Continue without upgrading? Yes
```

This forces a prompt.

If I do `ghost -v --no-prompt` it still prompts me.

I am using `ghost -v` to programmatically check if I need to update Ghost or Ghost CLI and I'm now unable to detect that or update blogs, because there's a message in the way that is telling me to update 🙈 .

**Comment by acburdine** [comment]
Yeah - I guess the update check should actually be moved further down into the CLI boot stack, so various commands can "opt out" of the check.

Will work on that soon :)

**Comment by ErisDS** [comment]
For clarity:

`ghost -v` `ghost --version` `ghost version` `ghost help` & `ghost --help` are all outputting this message, but `ghost` on it's own does not.

This is also related to https://github.com/TryGhost/Ghost-CLI/issues/563, in that not only should these commands not be outputting a prompt, but also `--no-prompt` is not respected so there's no way to programmatically interact.

I'm not really sure about the idea to have a prompt in the update check, except in `ghost upgrade` where you can break your install if you continue. I guess that explains why this is a rejection: https://github.com/TryGhost/Ghost-CLI/pull/558/files#diff-c013eae71412ed9b86e053b2d78ef711R29

However, IMO rejecting _only_ makes sense in the context of `ghost upgrade` to prevent breakages - and that's useful there because a bunch of people use `ghost upgrade` in a cron and their cron is now broken rather than their site.

However, any other command should be able to continue as nothing will break?
