### ISSUE TITLE
Latest update has broken Ghost

### ISSUE THREAD

**Issue by temabu** [TryGhost/Ghost-CLI#572]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

### This issue is a bug report (I think)

* [X] Bug Report

### Summary

* OS: Linux Ubuntu 16.04 LTS
* Node Version: 
* Ghost-CLI Version: 
* Environment: 
* Command: 

After running the last CLI update - ghost is now broken:

In my ghost directory /var/www/ghost I can run "ghost start" and all seems fine:

```
root@localhost:/var/www/ghost# ghost start
â Validating config
Running sudo command: systemctl start ghost_probablynotinteresting-com
â Starting Ghost
You can access your blog at https://probablynotinteresting.com

Ghost uses direct mail by default
To set up an alternative email method read our docs at https://docs.ghost.org/docs/mail-config
root@localhost:/var/www/ghost#
```
However I get 502 Bad Gateway when loading the webpage.

```
502 Bad Gateway
nginx/1.10.3 (Ubuntu)
```
So I try and run npm and start Ghost there:

```
root@localhost:/var/www/ghost# npm start --production
npm ERR! Linux 4.9.50-x86_64-linode86
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start" "--production"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! path /var/www/ghost/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/www/ghost/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/ghost/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/ghost/npm-debug.log
```
Any suggestions?
- How can I get Ghost working?
- Why is it looking for "package.json" and not "config.production.json"?
- How can I get the raw data backed up and then I will simply reinstall Ghost
- Why did this happen?

**Kate Note**
Relies on better logging for systemd (issue TBD). We first need to improve logging to figure out what's going on.

**Comment by ptallen63** [comment]
I had the exact same issue... 
Got some tips in the slack channel for a quick fix. This is what I did:

1) rolled it back w/ `ghost update --rollback`
2) updated npm install -g ghost-cli
3) forced the update with `ghost update --force`

This seemed to get me up and running again. Interested to hear what happened.

**Comment by vistaing** [comment]
I'm suffering from the same problem, after updated to 1.19.0. 
If I run `ghost update`, here it comes: 

✔ Checking for available migrations
Running sudo command: mkdir -p /etc/letsencrypt
Running sudo command: ./acme.sh --install --home /etc/letsencrypt
Running sudo command: /etc/letsencrypt/acme.sh --issue --home /etc/letsencrypt --domain enoshimadon.com --webroot /var/www/ghost/system/nginx-root --reloadcmd "nginx -s reload" --accountemail 632592761@qq.com
Running sudo command: nginx -s reload
Running sudo command: /root/.acme.sh/acme.sh --remove --home /root/.acme.sh --domain enoshimadon.com
✔ Migrating SSL certs
✔ Checking for latest Ghost version
All up to date!

Then I have to face the 502 problem as @temabu mentioned above. 
Great appreciate to @ptallen63 for the brilliant solution, it works.

**Comment by acburdine** [comment]
hmm...this seems to be an issue for several people, unfortunately I haven't been able to reproduce it myself yet 😕 

@temabu first off, `npm start --production` won't work with a Ghost-CLI install, if you want to run ghost in the current shell context, use `ghost run`.

Can you all provide information about your setup? Would be helpful to have these things:
1. What OS are you running?
2. Did you use a production install or a development install (if you ran `ghost install` initially, this will be production, you can also look and see if either a `config.production.json` or `config.development.json` file exists in your ghost install folder, if one exists that's the environment you're running in)
3. Are you using mysql or sqlite?

Hopefully with responses to the above I can reproduce this myself and get a fix in :)

**Comment by acburdine** [comment]
Possibly related: #573

**Comment by evilsupernasty** [comment]
I am having the same issue, though @ptallen63 fix did not work for me.

@acburdine 

1. Ubuntu 16.04.2 x64
2. Production
3. MySQL

**Comment by ericrange** [comment]
i dont know if there is a problem with sql.
but if u are using sqlite, the update process fails.
https://github.com/TryGhost/Ghost-CLI/issues/573
as i said, try to install ghost 1.0.0 with sqlite and then try to upgrade to 1.18.
you wont succeed.

**Comment by svikashk** [comment]
I had the same issue as well. Tried @ptallen63's solution, but didn't work at first. Tried it again few minutes later and it worked fine. Not sure what the route cause of the issue is though.
