### ISSUE TITLE
update ghost-cli but still its version is 1.1.1

### ISSUE THREAD

**Issue by savurself11** [TryGhost/Ghost-CLI#574]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

### This issue is a

* [v] Bug Report
* [ ] Feature Request

### Summary

If this is a bug, double-check and make sure there's not already an existing issue for it, then provide a quick summary of what error is occurring.

If this is a feature request, use this section to describe what feature you would like to see in the CLI, as well as a quick summary of any benefits or drawbacks you can think of if this feature is implemented.

### Steps to Reproduce (for a bug report)

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Also, if there is a log file generated (the CLI will output a message saying "Additional Log Info can be found at..."), please paste the contents of that log file here.

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: 
* Node Version: v6.11.3
* Ghost-CLI Version:  1.1.1
* Environment: production
* Command: sudo ghost update --force

`
bitnami@ip-172-31-23-211:/opt/bitnami/apps/ghost/htdocs$ sudo npm install -g ghost-cli@latest
npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
/opt/bitnami/nodejs/bin/ghost -> /opt/bitnami/nodejs/lib/node_modules/ghost-cli/bin/ghost
/opt/bitnami/nodejs/lib
└── ghost-cli@1.4.1 

bitnami@ip-172-31-23-211:/opt/bitnami/apps/ghost/htdocs$ sudo ghost version
Ghost-CLI version: 1.1.1
Ghost Version (at /opt/bitnami/apps/ghost/htdocs): 1.16.1
bitnami@ip-172-31-23-211:/opt/bitnami/apps/ghost/htdocs$ which ghost
/opt/bitnami/apps/ghost/bin/ghost
`
I recently update ghost-cli, but ghost version still ghost version indicate its version is 1.1.1

**Comment by acburdine** [comment]
@savurself11 looks like you have two versions of ghost-cli installed, which is why you're still getting 1.1.1 when you run `sudo ghost version`.

Gonna close this now as I'm 95% sure this is an issue with your setup, please swing by our slack channel (https://slack.ghost.org) so we can debug this further :) 

If it turns out that this is a bug with Ghost-CLI, we can reopen the issue.
