### ISSUE TITLE
ghost ls returns error

### ISSUE THREAD

**Issue by blagoeres** [TryGhost/Ghost-CLI#576]
The blog works just fine, but when I run `ghost ls` it returns this error. 

```
An error occurred.
Message: 'Path must be a string. Received undefined'

Debug Information:
    Node Version: v8.9.3
    Ghost-CLI Version: 1.4.1
    Environment: production
    Command: 'ghost ls'
```

The command I used to install Ghost was:
```
ghost install --pname=example.com --mail=SMTP --mailservice=Mailgun --mailuser=user --mailpass=password
```

- Ubuntu 16.04
- Node Version: v8.9.3
- Ghost-CLI Version: 1.4.1
- **Version** 1.19.0
- **Environment** production
- **Database** mysql
- **Mail** SMTP

**Comment by blagoeres** [comment]
I think using dot(.) in `--pname` causes this error. This is how my `~/.ghost/config` looks:

```
{
  "instances": {
    "example": {
      "com": {
        "cwd": "/var/www/ghost"
      }
    }
  }
}
```

**Comment by acburdine** [comment]
Yup - that would be the cause. Thanks for catching this!
