### ISSUE TITLE
Ghost install fails at database migrations

### ISSUE THREAD

**Issue by thekyriarchy** [TryGhost/Ghost-CLI#583]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

### This issue is a

* [ x ] Bug Report
* [ ] Feature Request

### Summary

install failure

### Steps to Reproduce (for a bug report)

1. set up prerequisites
2. run install

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Centos 7.3
* Node Version: 8.9.4
* Ghost-CLI Version: 1.4.2
* Environment: production
* Command: 'ghost install'

```
`✔ Setting up Systemd
Running sudo command: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
✖ Running database migrations
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#' -E -u ghost /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
/usr/bin/env: node: No such file or directory
```

**Comment by kirrg001** [comment]
> /usr/bin/env: node: No such file or directory

I assume that your node symlink is wrong. 
Please ensure that the location of `which node` is part of your `$PATH` variable.

Closing, not a CLI bug. Please swing by our [slack channel](https://slack.ghost.org) for further help.

**Comment by thekyriarchy** [comment]
```
$ which node
/usr/local/bin/node
$ $PATH
-bash: /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/me/.local/bin:/home/me/bin: No such file or directory
```
