### ISSUE TITLE
Cannot use CLI on Node v9.x

### ISSUE THREAD

**Issue by welkie** [TryGhost/Ghost-CLI#593]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

### This issue is a

* [ ] Feature Request

### Summary

*If this is a bug, double-check and make sure there's not already an existing issue for it, then provide a quick summary of what error is occurring.*

Checked and did not see issue reported already among open issues.

*If this is a feature request, use this section to describe what feature you would like to see in the CLI, as well as a quick summary of any benefits or drawbacks you can think of if this feature is implemented.*

I got the following error message when running the command ```yarn global add ghost-cli```:

```
error ghost-cli@1.4.2: The engine "node" is incompatible with this module. Expected version "^4.5.0 || ^6.9.0 || ^8.9.0".
error Found incompatible module
```

It looks like this is a case of ghost-cli not being supported on systems running Node 9.0.0 or greater. If this is the case, I would like to request this support, since it is inconvenient to have to run an outdated version of Node on your development machine, or use version switchers. If this isn't the case, perhaps this is a bug report instead.

### Steps to Reproduce (for a bug report)

1. Run the command ```npm install -g ghost-cli```

or

1. Install yarn
2. Run the command ```yarn global add ghost-cli```

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Antergos
* Node Version: 9.4.0
* Ghost-CLI Version: n/a
* Environment: ?
* Command: ```yarn global add ghost-cli```

**Comment by acburdine** [comment]
This is intentional, see https://docs.ghost.org/v1/docs/supported-node-versions.

**Comment by welkie** [comment]
@acburdine Thanks for the link, I see now why the version is pegged below 9.x.
