### ISSUE TITLE
Error related to MySQL when installing 2nd Ghost instance on a DigitalOcean server

### ISSUE THREAD

**Issue by hchouhan** [TryGhost/Ghost-CLI#596]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

### This issue is a

* [ ] Bug Report
* [ ] Feature Request

### Summary

After setting up the first site using Digital Ocean's Ghost installer, I tried to setup a 2nd Ghost installation. In the install process, I used the username and password of the mysql user "ghost" and the default database name suggested by Ghost. However, this did not work and I'm guessing due to some missing privileges.

```
✔ Setting up SSL
? Do you wish to set up "ghost" mysql user? Yes
MySQL user is not "root", skipping additional user setup
ℹ Setting up "ghost" mysql user [skipped]
? Do you wish to set up Systemd? Yes
✔ Creating systemd service file at /var/www/stretch/system/files/ghost_stretch-themeist-com.service
Running sudo command: ln -sf /var/www/stretch/system/files/ghost_stretch-themeist-com.service /lib/systemd/system/ghost_stretch-themeist-com.service
Running sudo command: systemctl daemon-reload
✔ Setting up Systemd
Running sudo command: /var/www/stretch/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/stretch/current
✖ Running database migrations
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#' -E -u ghost /var/www/stretch/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/stretch/current
[2018-01-25 08:44:47] ERROR

NAME: RollbackError
CODE: ER_DBACCESS_DENIED_ERROR
MESSAGE: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ghost'@'localhost' to database 'stretch_prod'

level:normal

OuterError: The server has encountered an error.
RollbackError: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ghost'@'localhost' to database 'stretch_prod'
```

If I run "ghost setup mysql" I get below response:

```root@mysite:/var/www/stretch# ghost setup mysql
MySQL user is not "root", skipping additional user setup
Setting up "ghost" mysql user [skipped]```



### Debug Information:

    Node Version: v6.12.3
    Ghost-CLI Version: 1.4.2
    Environment: production
    Command: 'ghost install'

**Comment by vikaspotluri123** [comment]
Hey @hchouhan 👋 Did you see the comment at the bottom of the DO Guide that said this? 

> It is easy, however the following might help you to succeed. As you install a fresh Ghost it is important to setup a fresh database and answer most questions with yes.

> The [user] while setting permission can be ghost
`sudo chown ghost:ghost: /var/www/newsite`
Make sure the domain of the blog is pointing already to the ip-address of the Droplet
For MySQL username use: root
The MySQL password for root can be found in /root/.digitalocean_password
`nano /root/.digitalocean_password`
Enter a unique Ghost database name: ie. ghost_newsite
Do you wish to set up Nginx? Yes
Do you wish to set up SSL? Yes
Do you wish to set up "ghost" mysql user? Yes
Do you wish to set up Systemd? Yes
Do you want to start Ghost? Yes
With this you can setup multiple Ghost sites on the same droplet.

Based on what you said, I think you're using the wrong database password

**Comment by hchouhan** [comment]
@vikaspotluri123,

I assumed I was using the wrong password, but after trying various things it did not work. At the end what worked was by manually assigning all privileges of the new database to the ghost user.

**Comment by acburdine** [comment]
@hchouhan Just to clarify, when you said you used the same "ghost" username and password, did you look in your config.production.json of your first ghost instance and get the username and password from there?

If so, that is the cause of your issue. Setting up the "ghost" mysql user only gives the user access to the database specific to that one ghost instance. If you wish to set up a second ghost instance on the same droplet, you'll need to use the original "root" user, and a new ghost mysql user will be created specific to your mysql instance.

**Comment by mesaquemota** [comment]
Olá...
Fiz tudo o que vocês disseram acima e não deu certo. 
Quando uso usuário "root" e sua respectiva senha, pede para usar o usuário "Ghost" e digo que sim. Mas ele dá erro e diz que não é suportado e precisa de atualizar o mysql.
Não estou conseguindo instalar um segundo "site ghost", me ajudem.
Abraço.
![image](https://user-images.githubusercontent.com/61563068/75485915-5d115f80-598a-11ea-8c7f-6398b35e4bf7.png)

**Comment by mesaquemota** [comment]
resolvi...
entrei no mysql e dei permição geral para usuário ghost
# sudo mysql
# GRANT ALL PRIVILEGES ON database_name.* TO 'username'@'localhost';
Depois basta instalar normalmente
# ghost setup
# Enter your blog URL: https://aquiaurlusada.com
# Enter your MySQL hostname: localhost
# Enter your MySQL username: ghost
# Enter your MySQL password: senha do ghost.
# Enter your Ghost database name: bdcriadopeloghost

Pronto, depois só confirmar tudo e ok.

Foi osso mas consegui!!!
