### ISSUE TITLE
linux ghost install fails on ghost user creation (probably locale-related)

### ISSUE THREAD

**Issue by nevez** [TryGhost/Ghost-CLI#601]
## This issue is a

* [x] Bug Report
* [ ] Feature Request

Please fill out this template, deleting where appropriate:

### Steps to Reproduce (for a bug report)

1. Run ghost install under linux in a non-english environment (i.e. spanish)
2. You get this error: ✖ Setting up "ghost" system user An error occurred. Message: 'id: «ghost»: no existe ese usuario

It could be related with the error message language. Looking at ghost-cli/lib/tasks/linux.js

`    try {
        execa.shellSync('id ghost');
        userExists = true;
    } catch (e) {
        if (!e.message.match(/no such user/i)) {
            return Promise.reject(e);
        }
    }
`
The spanish "no existe ese usuario" would not match the regular expression.

### Log file (for a bug report)

All errors end with "Additional log info available in: [filepath]".

Use the command `cat [filepath]` to read the log, then copy & paste the contents here:

```
Debug Information:
    Node Version: v8.9.4
    Ghost-CLI Version: 1.4.2
    Environment: production
    Command: 'ghost install'
An error occurred.
Message: 'id: «ghost»: no existe ese usuario
'

Stack: Error: id: «ghost»: no existe ese usuario

    at module.exports.sync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:303:26)
    at handleShell (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:105:9)
    at Function.module.exports.shellSync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:312:43)
    at SetupCommand.linuxSetupTask (/usr/lib/node_modules/ghost-cli/lib/tasks/linux.js:10:15)
    at Promise.resolve.then.then.skipped (/usr/lib/node_modules/ghost-cli/node_modules/listr/lib/task.js:168:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS (add version): Ubuntu 16.04.3 LTS
* Node Version: v8.9.4
* Ghost-CLI Version: 1.4.2
* Environment: production
* Command: 'ghost install'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in Slack & Docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by kirrg001** [comment]
@nevez Hey!

> The spanish "no existe ese usuario" would not match the regular expression.

Yeah this is not supported currently.
You would have to switch to your container language to english for now.

**Comment by acburdine** [comment]
Going to close this for now as it's related to #382. Will reopen later when we decide to work on/fix that issue.
