### ISSUE TITLE
Check if Ghost process died

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#61]
I am starting Ghost with `ghost start`. 
It shows me `✔ Starting Ghost instance`.
But Ghost is not running, because the process died.

Suggestion: Ensure process is alive for X and show Error if process died.

**Comment by acburdine** [comment]
Initial work for this has been done as a part of https://github.com/TryGhost/Ghost-CLI/commit/004169377d28fe550ddd4aa668ceb687fc652d83 - will close this when ghost has the ability to output process messages when it has started.

**Comment by acburdine** [comment]
Closed by #81
