### ISSUE TITLE
reconsider setting process.env.NODE_ENV

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#62]
See https://github.com/TryGhost/Ghost-CLI/pull/57/files#diff-0b441864c5280e9e0a69a0d9e97f7d86R57

**Comment by acburdine** [comment]
This _should_ be addressed by #66 I think.

**Comment by kirrg001** [comment]
👍

**Comment by acburdine** [comment]
Closing via https://github.com/TryGhost/Ghost-CLI/commit/004169377d28fe550ddd4aa668ceb687fc652d83
