### ISSUE TITLE
`ghost install` default behaviour

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#64]
The `ghost install` command is intended to create a fully-working production blog:

I think the main pieces to this are:
- [x] collect a URL to replace my-ghost-blog.com
- [x] Parse collected URL to ensure port is set correctly
~~- ensure logs go somewhere sensible (preferably /var/log/)~~ see #42 
- [x] use MySQL as the database 
- [x] use systemd to manage starting/stopping Ghost

Nice to haves:
- [ ] Provide for configuring nginx
- [ ] Provide for configuring SSL

**Comment by acburdine** [comment]
Note: https://github.com/Daplie/node-letsencrypt looks like a decent option for SSL
