### ISSUE TITLE
Consider yarn network timeouts

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#641]
Original slack thread: https://ghost.slack.com/archives/C04CUS2R3/p1518440412000159

A user on slack tried to install Ghost 1.0 but ran into network timeout errors from yarn. This happened on a raspberry pi, so counts as "other stack" but there are a few interesting things:

- We don't handle the error very well
- We don't expose a way to control the timeout for yarn
- This problem isn't raspberry pi specific

This could happen on a very slow ubuntu machine, and although there is a workaround for now, we should IMO consider improving error handling and also either extending or exposing the yarn config.

-----

Original details:

```
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@1.21.1: The engine "cli" appears to be invalid.
error An unexpected error occurred: "https://registry.yarnpkg.com/intl/-/intl-1.2.5.tgz: ESOCKETTIMEDOUT".
error https://registry.yarnpkg.com/sqlite3/-/sqlite3-3.1.13.tgz: ESOCKETTIMEDOUT

yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
... repeated many times ....
info If you think this is a bug, please open a bug report with the information provided in "/var/www/ghost/versions/1.21.1/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
... repeated again ...

Exit code: 1

Debug Information:
   OS: Raspbian, v9.3
   Node Version: v6.12.3
   Ghost-CLI Version: 1.5.1
   Environment: production
   Command: 'ghost install'

Additional log info available in: /home/pi/.ghost/logs/ghost-cli-debug-2018-02-12T12_47_48_928Z.log
```

The user managed to solve the problem themselves:

>  by installing yarn myself and increasing the default network-timeout value, like this:

```
cd /var/www/ghost
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install yarn
yarn config set network-timeout 180000
```

**Comment by GerDner** [comment]
Fixed the error for me by upgrading to node 8.x

**Comment by lizrodriguez** [comment]
Hello,
I'm facing this issue currently on my VPS with a fresh install of Ubuntu 16.04 and have tried both installing yarn with setting a larger network timeout, and ensuring I'm running node 8.11.4. Here's my debug info:

```✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v2.0.1
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@2.0.1: The engine "cli" appears to be invalid.
error Couldn't find the binary git

yarn install v1.9.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1


Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v8.11.4
    Ghost-CLI Version: 1.9.0
    Environment: production
    Command: 'ghost install'
```

Any ideas of what else I could try would be much appreciated!

**Comment by vikaspotluri123** [comment]
This migt be an issue with the latest release of Ghost - @lizrodriguez could you try installing ghost with `ghost install 2.0.0` and report back?

If it is, [this comment](https://github.com/yarnpkg/yarn/issues/2083#issuecomment-273520191) might be useful

**Comment by pascalandy** [comment]
I think this might be resolved with Ghost 2.0.2
https://github.com/TryGhost/Ghost-CLI/issues/792#issuecomment-414645868

**Comment by ekerstein** [comment]
I'm running into a related issue trying to update from 2.6.0 to 2.8.0.

```
 Checking system Node.js version
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking for available migrations
✔ Checking for latest Ghost version
✖ Downloading and updating Ghost to v2.8.0
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@2.8.0: The engine "cli" appears to be invalid.
warning Error running install script for optional dependency: "/var/www/ghost/versions/2.8.0/node_modules/knex-migrator/node_modules/sqlite3: spawn ENOMEM"
error An unexpected error occurred: "/var/www/ghost/versions/2.8.0/node_modules/jsonpath: spawn ENOMEM".
warning Error running install script for optional dependency: "/var/www/ghost/versions/2.8.0/node_modules/sharp: spawn ENOMEM"
warning Error running install script for optional dependency: "/var/www/ghost/versions/2.8.0/node_modules/sqlite3: spawn ENOMEM"
warning Error running install script for optional dependency: "/var/www/ghost/versions/2.8.0/node_modules/dtrace-provider: spawn ENOMEM"

yarn install v1.9.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info This module is OPTIONAL, you can safely ignore this error
info If you think this is a bug, please open a bug report with the information provided in "/var/www/ghost/versions/2.8.0/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info This module is OPTIONAL, you can safely ignore this error
info This module is OPTIONAL, you can safely ignore this error
info This module is OPTIONAL, you can safely ignore this error

Exit code: 1


Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.10.0
    Ghost-CLI Version: 1.9.8
    Environment: production
    Command: 'ghost update'
```

**Comment by acburdine** [comment]
@ekerstein your issue appears to be related to the system being out of available memory rather than network timeouts. Not that we can't improve that error messaging, but in the interrim you can try increasing your available memory by adding swap space.

**Comment by ekerstein** [comment]
@acburdine I cleared up some memory and it worked - thanks!

**Comment by lmuzquiz** [comment]
@ErisDS Today i got a similar problem, as the one @lizrodriguez https://github.com/TryGhost/Ghost-CLI/issues/641#issuecomment-414428740 

First i tried `ghost install` and got this output with the error:

`✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v2.15.0
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@2.15.0: The engine "cli" appears to be invalid.
error csv-parser@2.1.0: The engine "node" is incompatible with this module. Expected version ">= 6.14.0". Got "6.12.3"
error Found incompatible module

yarn install v1.12.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.12.3
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost install'

Additional log info available in: /home/lmuzquiz/.ghost/logs/ghost-cli-debug-2019-02-24T02_05_46_253Z.log`

Then i visited your [ghost releases github page](https://github.com/TryGhost/Ghost/releases) and tried to install all the latest versions, one by one to check which latest version i could install:

All these versions got me the same error described above:

- ghost install 2.14.3
- ghost install 2.14.2 
- ghost install 2.14.1 
- ghost install 2.14.0
- ghost install 2.13.2
- ghost install 2.13.1
- ghost install 2.13.0
- ghost install 2.12.0

And finally i could make a fresh ghost install with this version:

ghost install 2.11.1

My Ubuntu 16.04 was using at the time of the installation less than 59% of RAM memory and the disk usage was around 65%

**Before** i got these errors my Ubuntu 16.04 server had close to 80% RAM used, but i un-installed using ghost uninstall a lot of blogs i did not use. Then i tried to do ghost install (with my RAM now at 58%) and got the errors described above.

**Comment by vikaspotluri123** [comment]
@lmuzquiz The errors are different - the error Liz got related to one of Ghost's dependencies being hosted on github, but the system not having a suitable git client installed to download. Your error relates to your node version - 

> The engine "node" is incompatible with this module. Expected version ">= 6.14.0". Got "6.12.3"

What this means is you need to update your node version to the latest 6.x release. If you followed the installation guide, the should be as simple as running `sudo apt-get update && sudo apt-get install nodejs` (using install will only update nodejs, if you want to update any other packages, run `sudo apt-get upgrade`. After updating node, you should be fine until April, when the 6.x line of node will be deprecated and Ghost stops supporting it.

**Comment by lmuzquiz** [comment]
Thank you @vikaspotluri123 i had to pay more attention.

**Comment by shaped1** [comment]
Still facing this issue until I changed it in the `node_modules` where ghost is located to remove it. In retrospect, I probably should've just searched for it :smile:

**Comment by fvlasie** [comment]
I am seeing this error:
`✔ Checking system Node.js version - found v14.16.1
✔ Checking logged in user
✔ Checking current folder permissions
System checks failed with message: 'Linux version is not Ubuntu 16, 18, or 20'
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? Yes
System stack check skipped
ℹ Checking system compatibility [skipped]
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking free space
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v4.10.2
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress

yarn install v1.22.10


Debug Information:
    OS: Oracle Linux Server, v8.4
    Node Version: v14.16.1
    Ghost-CLI Version: 1.17.3
    Environment: production
    Command: 'ghost install'`

I have tried changing the yarn timeout as suggested above but it did not solve the problem.
