### ISSUE TITLE
GhostCLI creates remote mysql users with the wrong host

### ISSUE THREAD

**Issue by seafoodbuffet** [TryGhost/Ghost-CLI#642]
## This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary
GhostCLI creates remote mysql database users as
'ghost-xxx'@'db hostname' instead of 'ghost-xxx'@'web hostname' or 'ghost-xxx'@'%'

This causes connections from a remote web server to fail (e.g. during `setup migrate`).

### Steps to Reproduce (for a bug report)

1. Setup two servers, one with GhostCLI, another with MySQL. Have a remote mysql root user that can create users, databases, and has the GRANT option.
2. Run `ghost install` specifying the remote MySQL server and your remote-capable mysql root user.
3. The installation will fail with the following error:
```
[20:41:03] Running database migrations [failed]
[20:41:03] → Invalid database username or password
A ConfigError occurred.

Error detected in the production configuration.

Message: Invalid database username or password
Configuration Key(s): database.connection.user / database.connection.password
Current Value(s): ghost-872 / ***password hidden***
```
Running `ghost setup -V migrate` shows the following error
```
$ ghost setup -V migrate
[20:42:37] Running database migrations [started]
Running sudo command: /usr/share/nginx/html/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /usr/share/nginx/html/current
[20:42:38] Running database migrations [failed]
[20:42:38] → The database migration in Ghost encountered an error.
A ProcessError occurred.

Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error
--------------- stderr ---------------
[2018-02-13 20:42:38] ERROR

NAME: RollbackError
CODE: ER_DBACCESS_DENIED_ERROR
MESSAGE: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ghost-872'@'%' to database 'ghoster'

level:normal

OuterError: The server has encountered an error.
RollbackError: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ghost-872'@'%' to database 'ghoster'
```

### Workaround
To work around this issue, I manually modified the created user to 'ghost-872'@'%' and granted the user permissions to the GhostCLI-created ghost database. After that, `setup migrate` succeeded and I was able to start ghost.

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Ubuntu, v16.04
 * Node Version: v6.12.3
 * Ghost-CLI Version: 1.5.2
 * Environment: production
 * Command: 'ghost install'

I will admit I did not ask about this in Slack. Am I in an unsupported setup?

- [ ] Tried to find help in Slack & Docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by acburdine** [comment]
yeah - I can see where this would occur. Remote mysql databases are definitely supported, so this is a bug. Thanks for reporting!
