### ISSUE TITLE
 Removing old Ghost versions [skipped]

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost-CLI#646]
it got this below Message while removing an older version

```
 Removing old Ghost versions [skipped]
```
seems it does not fully removed/unlink the older versions
sites are working fine no issue & errors
it just want to confirm it is a bug or anything else

I check My setups and permissions all are fine

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Ubuntu 16.04.3
* Node Version:6.13.0
* Ghost-CLI Version:1.5.2
* Command:ghost update

**Comment by vikaspotluri123** [comment]
Hey @mskian 👋 this a question better suited for [slack](https://slack.ghost.org)!

That being said, there's nothing to worry about - the last 5 versions are kept just in case 😄

**Comment by AileenCGN** [comment]
Closing this, as it's not an issue with the CLI
