### ISSUE TITLE
Install UX & Handling multiple installs

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#65]
As I'm testing Ghost-CLI, I have a whole bunch of folders where I've used it to install Ghost.

Whenever I install a fresh version, or start one of my existing versions I don't get any information as to how I can go about accessing the version of Ghost that I just installed or started.

E.g. doing a fresh `ghost install local` outputs:

```
✔ System is running supported version of node
✔ Current folder is writeable
✔ Setting up the Ghost installation structure
✔ Downloading and installing Ghost
✔ Starting Ghost instance
Finished!
```

However, I don't now know how I can access Ghost (and in fact we don't really know if Ghost is running). This is in part due to the fact that the concept of multiple installs isn't really covered just yet.

E.g. because I know Ghost, I know that the version I just created is now running at `http://localhost:2368/`, and I can visit that and see my brand new blog 🎉 .

If I now test the cli again, in a new directory, running `ghost install local` again outputs the exact same thing. If I navigate to http://localhost:2368/, I see a blog, but I don't know which one. This has been a problem for me, not knowing where to go to run `ghost stop`!

I believe that in the current version, the 2nd (or 3rd..) blog won't start because the port is in use. My expectation as a user would be that the cli would start Ghost for me on an available port, and tell me what port it used. I realise that's probably not the simplest thing to implement, so lets start by improving the messaging and the bigger features can be implemented later.
- [x] When starting Ghost, output the URL that the blog can be accessed from
- [x] Correctly detect if the blog started (#61) if the blog failed to start due to an already running Ghost instance, output a sensible error message

Optimising for multiple-installs (to do later!!!!)
- [x] Ensure that when we run Ghost, we use a process name or some other way so that we can find where the managed instances come from (e.g. what folder they were installed in)
- [x] Add `ghost kill-all` as a command that will find all managed processes and kill them -> this is ghost stop
- [x] Implement port-finding when installing Ghost, cycling up from 2368 
- [ ] Optimise `ghost install` to only download ghost once and cache it
- [ ] Optimise `ghost install` to only download dependencies once (use Yarn?!?)

**Comment by moebiusmania** [comment]
+1 for the ```ghost kill-all```command!

I'm in a situation where I can't start Ghost instance beacuse port is in use and running the stop command tells me that there is nothing running...

**Comment by acburdine** [comment]
@ErisDS yarn does a pretty good job of caching dependencies on it's own, so the last couple of tasks on this are unnecessary imo.

**Comment by ErisDS** [comment]
👍  can revisit if it becomes more of a problem
