### ISSUE TITLE
Feature: Add option to disable check-directory for shared environments

### ISSUE THREAD

**Issue by gravesit** [TryGhost/Ghost-CLI#654]
In the 1.5.X update the  check-directory.js was added and this is causing the error:
```
✖ Checking current folder permissions
✔ Validating config
One or more errors occurred.

1) SystemError

Message: The path /home/username/ is not readable by other users on the system.
This can cause issues with the CLI, please either make this directory readable by others or run `ghost install` in another location.

Debug Information:
    OS: linux, v3.10.0-693.11.6.el7.x86_64
    Node Version: v8.9.4
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost start'
```

With 1.4.2 this issue does not occur and manually editing the file to bypass the check is a temporary work around. 

Please add an option in the start command to disable this check for those running in shared hosting and don't have access to change directory permissions.

**Comment by AileenCGN** [comment]
Hey @gravesit 

Sorry to hear that you're having trouble. We added this check, as the directories above the Ghost installation folder need to be readable for other users until the root directory. Is it possible for you to change the permissions of your `/home/username` folder (`sudo chmod o+r /home/username`)?

Nevertheless, we're still improving the `ghost doctor` commands and one of the improvements will be to add a `--skip` flag. See #47 to follow up on this.

I will close this issue, as we're tracking this feature request in the mentioned issue and your example is not happening on the recommended stack and installation process.
