### ISSUE TITLE
The database migration in Ghost encountered an error when upgrading Ghost

### ISSUE THREAD

**Issue by heshanfu** [TryGhost/Ghost-CLI#658]
When upgrading from 1.8.1 to v1.21.3 I encountered the following issue that I haven't seen before. I am now getting a 502 Bad Gateway .

[39m Downloading and updating Ghost to v1.21.3
[39m Stopping Ghost [skipped]
[39m Linking latest Ghost and recording versions
[39m Running database migrations
A ProcessError occurred.

Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error
Suggestion: ghost update --rollback

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.12.3
    Ghost-CLI Version: 1.5.2
    Environment: development
    Command: 'ghost update --force'

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting

**Comment by heshanfu** [comment]
ghost log
An error occurred.
Message: 'Cannot read property 'join' of undefined'


Debug Information:
    OS: linux, v2.6.32-042stab127.2
    Node Version: v6.13.0
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost log'

Additional log info available in: /home/heshanfu/.ghost/logs/ghost-cli-debug-2018-02-23T05_01_40_536Z.log

Try running ghost doctor to check your system for known issues.

**Comment by heshanfu** [comment]
cat /home/heshanfu/.ghost/logs/ghost-cli-debug-2018-02-23T05_01_40_536Z.log
Debug Information:
    OS: linux, v2.6.32-042stab127.2
    Node Version: v6.13.0
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost log'
An error occurred.
Message: 'Cannot read property 'join' of undefined'

Stack: TypeError: Cannot read property 'join' of undefined
    at LogCommand.run (/usr/lib/node_modules/ghost-cli/lib/commands/log.js:36:84)
    at precheck.then (/usr/lib/node_modules/ghost-cli/lib/command.js:159:52)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:613:11)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3

**Comment by heshanfu** [comment]
ghost log
An error occurred.
Message: 'Cannot read property 'join' of undefined'

Debug Information:
    OS: linux, v2.6.32-042stab127.2
    Node Version: v6.13.0
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost log'

Additional log info available in: /home/heshanfu/.ghost/logs/ghost-cli-debug-2018-02-23T05_12_00_150Z.log

Try running ghost doctor to check your system for known issues.

**Comment by heshanfu** [comment]
i try to change system os, update nodejs,update ghost-cli,update ghost,but cannot start ghost.help.

**Comment by AileenCGN** [comment]
Hey @heshanfu

Sorry to hear that you're having trouble. Did you actually try any of the suggestions? Like ` ghost update --rollback`?

Please swing by to our [Slack](https://slack.ghost.org) channel  to get support, as we use GitHub issues only to track actual bugs or feature requests, but not for support.

I will close this issue for now, but we can always reopen it, if it turns out to be an issue.

**Comment by heshanfu** [comment]
i try to ghost update --rollback

ghost update --rollback
An error occurred.
Message: 'No previous version found'


Debug Information:
    OS: linux, v2.6.32-042stab127.2
    Node Version: v6.13.0
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost update --rollback'

Additional log info available in: /home/heshanfu/.ghost/logs/ghost-cli-debug-2018-02-23T06_47_49_618Z.log

Try running ghost doctor to check your system for known issues.

**Comment by heshanfu** [comment]
cat /home/heshanfu/.ghost/logs/ghost-cli-debug-2018-02-23T06_45_55_380Z.log
Debug Information:
    OS: linux, v2.6.32-042stab127.2
    Node Version: v6.13.0
    Ghost-CLI Version: 1.5.2
    Environment: development
    Command: 'ghost start -D'
Message: An error occurred.
Stack: Error: An error occurred.
    at ChildProcess.cp.on (/usr/lib/node_modules/ghost-cli/lib/utils/local-process.js:63:35)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)

**Comment by heshanfu** [comment]
i try it ,but i cannot start ghost also.help me please

**Comment by AileenCGN** [comment]
> Please swing by to our [Slack](https://slack.ghost.org) channel  to get support, as we use GitHub issues only to track actual bugs or feature requests, but not for support.
