### ISSUE TITLE
Ghost CLI Validating config undefined.

### ISSUE THREAD

**Issue by techayu** [TryGhost/Ghost-CLI#660]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://slack.ghost.org/ 👫.

Docs: https://docs.ghost.org 📖.

Please be aware that the team behind the Ghost CLI only supports the recommended stack: https://github.com/TryGhost/Ghost-cli#recommended-stack.

## This issue is a

* [x] Bug Report
* [x] Feature Request

Please fill out this template, deleting where appropriate:

### Summary

Bugs reports: search GitHub for existing issues & check the docs: https://docs.ghost.org/docs/troubleshooting. If you're still stuck, please provide a quick summary of the problem, steps to reproduce, and full tech details including logs.

Feature requests: describe the feature and make a clear, detailed case for adding it.

### Steps to Reproduce (for a bug report)

I have installed ghost many times on my vps successfully without any error on same operating system. This time also i am using ubuntu 16.04 64 bit.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Log file (for a bug report)

All errors end with "Additional log info available in: [filepath]".

Use the command `cat [filepath]` to read the log, then copy & paste the contents here:

```
Paste log file here
aDebug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.13.0
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost install'
An error occurred.
Message: 'Command failed: /bin/sh -c systemctl is-active ghost_localhost
Failed to connect to bus: No such file or directory

'

Stack: Error: Command failed: /bin/sh -c systemctl is-active ghost_localhost
Failed to connect to bus: No such file or directory


    at makeError (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:169:9)
    at module.exports.sync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:338:15)
    at handleShell (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:116:9)
    at Function.module.exports.shellSync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:361:43)
    at SystemdProcessManager.isRunning (/usr/lib/node_modules/ghost-cli/extensions/systemd/systemd.js:88:19)
    at Instance.running (/usr/lib/node_modules/ghost-cli/lib/instance.js:120:34)
    at StartCommand.run (/usr/lib/node_modules/ghost-cli/lib/commands/start.js:28:22)
    at SetupCommand.runCommand (/usr/lib/node_modules/ghost-cli/lib/command.js:204:44)
    at ui.listr.then.then (/usr/lib/node_modules/ghost-cli/lib/commands/setup.js:192:42)
Code: 1
```

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS:
* Node Version:
* Ghost-CLI Version:
* Environment:
* Command:

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [Y] Tried to find help in Slack & Docs
- [Y ] Checked for existing issues
- [Y ] Attached log file
- [Y ] Provided technical details incl. operating system
![image](https://user-images.githubusercontent.com/31890891/36626357-4c7c2f9e-1957-11e8-883d-5141c2ebd257.png)

**Comment by kirrg001** [comment]
Re-open. I was just running into this with the latest release.

Any command showed:

> kirrg001@dev-kate-01:/var/www/ghost$ ghost doctor
> Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_clitest-kirrg-win

No further information in the debug log or in the journalctl.

`systemctl status ghost_clitest-kirrg-win` showed `failed`.

After playing a while with this state, **the only command** which fixed my situation was:

> systemctl restart ghost_clitest-kirrg-win

Then i was able to run CLI commands again. 

`ghost stop` worked.
`ghost ls` worked.
`systemctl` showed `inactive`.

`ghost start` failed again.

`journalctl` showed:

> Error: EACCES: permission denied, mkdir '/home/ghost'
> at System.writeErrorLog (/usr/lib/node_modules/ghost-cli/lib/system.js:352:12)
> EACCES: permission denied, open '/var/www/ghost/config.production.json''

`ghost doctor` is green.

I don't understand why the CLI tries to acces `/home/ghost` on `ghost start`.
I also don't understand why i am getting a permission error for my config file.
My permissions look good.

Maybe my setup is broken, but this definitely needs digging. I would like to know what's going on 😎

I'll leave my server as is. Maybe somebody has an idea.

**Comment by kirrg001** [comment]
Closing in favour of #689

**Comment by techayu** [comment]
I have solved this issue the problem was with vps because it was using old kernel version so it had some missing dependencies which are needed by ghost. So i managed to find all the missing packages and dependencies and then i installed them manually and it worked all fine.
