### ISSUE TITLE
Ghost Restart and Start command shows an error

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost-CLI#662]
Hi,
Why does `ghost restart` and `ghost start` does not work sometimes? It works most of the time but, it occasionally gives an error that says ghost could not be restarted, or started..

Issue:
![image](https://user-images.githubusercontent.com/9730242/36787777-492b83b8-1cc6-11e8-9f08-237a6761b36d.png)

Log file:
![image](https://user-images.githubusercontent.com/9730242/36787809-69faeab6-1cc6-11e8-8482-5d352379dba3.png)

---------------------------

The CLI pauses for a few seconds in the `Staring Ghost` or `Restarting Ghost` part but after that, it shows an error that shows occasionally.

**Comment by PhoenixPeca** [comment]
Manually executing `sudo systemctl start ghost_www-phoenixpeca-xyz` works well though..

**Comment by kirrg001** [comment]
@PhoenixPeca Can you please fill out our [issue template](https://github.com/TryGhost/Ghost-CLI/blob/master/.github/ISSUE_TEMPLATE.md) completely? Thanks.

**Comment by PhoenixPeca** [comment]
somehow, the issue no longer appears..
