### ISSUE TITLE
Cannot run database migrations

### ISSUE THREAD

**Issue by Magentaize** [TryGhost/Ghost-CLI#667]
## This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary
Processing a new & clean installation, ghost-cli cannot be installed properly.

### Steps to Reproduce (for a bug report)

1. cd into a empty dir
2. run `sudo npm install -g ghost-cli`
3. run `ghost install`
4. make some config its needs
5. error happens:
>✔ Setting up Systemd
Running sudo command: /mnt/wwwroot/blog/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /mnt/wwwroot/blog/current
✖ Running database migrations
A ProcessError occurred.
Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error

### Log file (for a bug report)
```
Debug Information:
    OS: Debian, v9.3
    Node Version: v6.13.1
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost install'
Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error
--------------- stderr ---------------
sudo: unable to execute /mnt/wwwroot/blog/current/node_modules/.bin/knex-migrator-migrate: Permission denied
```

`ghost doctor` log:
```
✔ Checking system Node.js version
✔ Checking current folder permissions
System checks failed with message: 'Linux version is not Ubuntu 16'
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? Yes
✔ Checking operating system
Local MySQL install not found. You can ignore this if you are using a remote MySQL host.
Alternatively you could:
a) install MySQL locally
b) run `ghost install --db=sqlite3` to use sqlite 
c) run `ghost install local` to get a development install using sqlite3.
? Continue anyway? Yes
✔ Checking MySQL is installed
✔ All install checks passed
```

### Technical details (for a bug report)

* OS:Debian, v9.3
* Node Version:v6.13.1
* Ghost-CLI Version:1.5.2
* Environment:production
* Command:'ghost install'

## Bug submission checklist

- [x] Tried to find help in Slack & Docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by Magentaize** [comment]
@AileenCGN Thanks for your reply.
But I have installed MySQL in another LAN machine, and use intranet address to access it (likes 192.168.2.142:3308).

**Comment by acburdine** [comment]
@Magentaize it looks like sudo isn't able to execute the migrate script inside your ghost install directory. Is your install directory an externally mounted/network drive? (reason I ask is it's inside `/mnt`). If so, that _might_ be the cause of the issue - it wouldn't be surprising that file permissions might be a bit weird on external drives.

**Comment by Magentaize** [comment]
@acburdine 
Thanks for your reply.

After I granted this folder a+x permission, ghost-cli throws another error:
```
✖ Running database migrations
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -E -u ghost /usr/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /mnt/wwwroot/blog/current
[2018-03-14 15:54:19] ERROR

NAME: InternalServerError
MESSAGE: Please provide a file named MigratorConfig.js in your project root.
```

**Comment by ccyuki** [comment]
I have a same problem;
`[yuki@ghost ghost]$ ll
total 16
-rw-rw-r-- 1 yuki  yuki   494 Sep 27 08:29 config.production.json
drwxrwxr-x 8 ghost ghost 4096 Sep 27 08:27 content
lrwxrwxrwx 1 yuki  yuki    30 Sep 27 08:28 current -> /var/www/ghost/versions/1.25.5
drwxrwxr-x 3 yuki  yuki  4096 Sep 27 08:29 system
drwxrwxr-x 3 yuki  yuki  4096 Sep 27 08:28 versions
[yuki@ghost ghost]$ pwd
/var/www/ghost
[yuki@ghost ghost]$ mysql -V
mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper
[yuki@ghost ghost]$ uname -a
Linux ghost 4.18.9-1.el7.elrepo.x86_64 #1 SMP Thu Sep 20 09:04:54 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
[yuki@ghost ghost]$ 
`
