### ISSUE TITLE
reading_time helper did not work with Chinese

### ISSUE THREAD

**Issue by xiaochunjimmy** [TryGhost/Ghost-CLI#670]
* [ ] Bug Report

### Steps to Reproduce (for a bug report)

1.Input about 2750 Chinese words in a new blog story.
2.In the published page you'll see the reading time area prints "< 1 min read".
but it should print 2750/275=10 min .
3.In put some 2750 English words in the blog story, and the published blog article prints 10min.
so it works with English.
4.In put about 2750 Chinese words and 2750 spaces in every words, and the published blog article prints 10min.

so the arithmetic of reading time function is just counting spaces????
there are so many languages do not use space, so this method is a little tricky.

**Comment by AileenCGN** [comment]
Hey @xiaochunjimmy 

The `{{reading_time}}` helper is currently not able to count non-latin languages like Chinese.

This would need input from the community. Feel free to open an issue with a solution in mind on how to solve this in the [Ghost repo](https://github.com/TryGhost/Ghost) (not Ghost-CLI).
