### ISSUE TITLE
Improve usability of `ghost help`

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/Ghost-CLI#679]
## This issue is a

* [ ] Bug Report
* [x] Feature Request

### Summary

The legibility (i.e. the overall usability) of `ghost help` needs to be improved: it's hard to scan the description of the commands, mostly because of the `[aliases...` additions. (It’s especially painful if the terminal window is small so that it breaks the broken lines into more lines.) The overall help could be further enhanced by applying color and layout details (to be specified).

### Steps to Reproduce (for a bug report)

1. Run `ghost help`

### Screenshot

<img width="671" alt="screen shot 2018-03-19 at 14 04 13" src="https://user-images.githubusercontent.com/353959/37641660-ee494552-2c1a-11e8-9acf-421e7738bc9a.png">

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [ ] Tried to find help in Slack & Docs (N/A)
- [x] Checked for existing issues
- [x] Attached log files (see screenshot)
- [ ] Provided technical details incl. operating system (N/A)

**Comment by acburdine** [comment]
Just so it's linked correctly, the aliases part of this was fixed by #677 😄

**Comment by vikaspotluri123** [comment]
Implementation of colors can probably be abstracted to [yargonaut](https://www.npmjs.com/package/yargonaut). The only thing we need to check is that there's no regression for the `--no-color` flag
