### ISSUE TITLE
Error: Cannot find any-observable implementation nor global.Observable.

### ISSUE THREAD

**Issue by duanemck** [TryGhost/Ghost-CLI#685]
## This issue is a

* [x] Bug Report
* [ ] Feature Request

Please fill out this template, deleting where appropriate:

### Summary

When trying to install a new ghost instance with the cli, I get the following error:
```
Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
```

### Steps to Reproduce (for a bug report)

1. Install CLI gobally
2. Change to the /var/www/ghost folder
3. CHOWN and CHMOD as in the install guide
4. Run ```ghost install```

### Log file (for a bug report)

```
/usr/lib/node_modules/ghost-cli/node_modules/any-observable/register.js:29
                throw new Error('Cannot find any-observable implementation nor' +
                ^

Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
    at loadImplementation (/usr/lib/node_modules/ghost-cli/node_modules/any-observable/register.js:29:9)
    at register (/usr/lib/node_modules/ghost-cli/node_modules/any-observable/loader.js:32:18)
    at Object.<anonymous> (/usr/lib/node_modules/ghost-cli/node_modules/any-observable/index.js:2:39)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Ubuntu 17.10
* Node Version: 6.11.0
* Ghost-CLI Version: 1.5.2
* Environment:
* Command: install

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [X] Tried to find help in Slack & Docs
- [X] Checked for existing issues
- [X] Attached log file
- [X] Provided technical details incl. operating system

**Comment by duanemck** [comment]
Nevermind, added some logging in the 'any-observable' register.js. Turned out to be a permission issue on the global cli install. Fixed that and now it works.

**Comment by hvassing** [comment]
@duanemck Could you please elaborate on what you did to fix this?

**Comment by duanemck** [comment]
@hvassing I'm trying to remember what I did now, was a while ago. I think I may have initially installed the CLI with the wrong (root) user and then tried to use it as the ghost user. There were some files in the node_modules that it wasn't allowed to access. Sorry, that's the best I can remember.

**Comment by gbonanome** [comment]
I got the same issue today on a `ghost update`

- OS: Ubuntu, v16.04
- Node Version: v6.11.2
- Ghost-CLI Version: 1.7.3
- Environment: production
- Command: 'ghost update'

At first I was looking for the same solution (a permission problem) but then I found this issue related to `listr` package https://github.com/okonet/lint-staged/issues/416

For me installing **`rxjs-compat`** under ghost-cli modules fixed the issue.
