### ISSUE TITLE
ghost restart with local process model does not validate config and rewrites config file

### ISSUE THREAD

**Issue by fehwalker** [TryGhost/Ghost-CLI#690]
## This issue is a

* [X] Bug Report
* [ ] Feature Request

### Summary

When using `local` process model, `ghost restart` with an invalid config.production.json causes ghost to rewrite the file to only contain a `paths` entry. 

### Steps to Reproduce (for a bug report)

1. Set process model to `local` and run `ghost start` with a working config
2. Add a syntax error to the config.production.json file - I added a new a key/value pair at the bottom of the config without adding a comma to the previous last line
3. Run `ghost restart`, see it errors out with
```
_ Restarting Ghost
A GhostError occurred.

Message: An error occurred.
[...]
```
Log entry with debug info is below.
4 . Observe that the config.production.json file now only contains the following.
```
{
  "paths": {
    "contentPath": "/var/www/ghost/content"
  }
}
```

I would expect that `ghost restart` would validate the config the same as `ghost start` and safely exit with a validation error, as it does using the `systemd` process model. Or, at the very least, it should never rewrite the config.production.json file.

### Log file (for a bug report)

```
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.0
    Ghost-CLI Version: 1.6.0
    Environment: production
    Command: 'ghost restart'
Message: An error occurred.
Stack: Error: An error occurred.
    at ChildProcess.cp.on (/usr/lib/node_modules/ghost-cli/lib/utils/local-process.js:63:35)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Ubuntu, v16.04
* Node Version: v6.14.0
* Ghost-CLI Version: 1.6.0
* Environment: production
* Command: 'ghost restart'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [X] Tried to find help in Slack & Docs
- [X] Checked for existing issues
- [X] Attached log file
- [X] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
I can work on fixing this Tuesday or Wednesday

**Comment by vikaspotluri123** [comment]
Notes:
- We need to add validations [here](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/utils/config.js)
- Error handling needs to be added. I'm thinking for non-global commands, the CLI errors, and for global commands, the CLI warns and skips

**Comment by vikaspotluri123** [comment]
Fixing this is a pretty delicate task 😬 I'm going to take my time to make sure nothing breaks 😃
