### ISSUE TITLE
Server installation fail: Command failed: yarn install --no-emoji --no-progress

### ISSUE THREAD

**Issue by aurabindo** [TryGhost/Ghost-CLI#696]
## This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

Following the steps in the official guide, installation fails at `ghost install` with the following message:

```
✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v1.22.1
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@1.22.1: The engine "cli" appears to be invalid.

yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...


Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.1
    Ghost-CLI Version: 1.6.0
    Environment: production
    Command: 'ghost install'
```

 Contents of log file:

```
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.1
    Ghost-CLI Version: 1.6.0
    Environment: production
    Command: 'ghost install'
Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@1.22.1: The engine "cli" appears to be invalid.

yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...

--------------- stdout ---------------
yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...


--------------- stderr ---------------
warning ghost@1.22.1: The engine "cli" appears to be invalid.
```

### Steps to Reproduce (for a bug report)

1. Fresh Ubuntu 16.04 installation
2. Follow official steps for installation

**Comment by AileenCGN** [comment]
I think this is related to #641, if not a duplicate.

**Comment by kirrg001** [comment]
> I think this is related to #641, if not a duplicate.

Yeah looks like it's the same.

@aurabindo Can you please install Ghost again? And if it's still not working, please reply in #641.

Thanks :)

**Comment by aurabindo** [comment]
@kirrg001 I'm no longer facing the error, after installing yarn and setting a larger network timeout. Thank you.

**Comment by GerDner** [comment]
Fixed the error for me by upgrading to node 8.x

**Comment by lizrodriguez** [comment]
Hello,
I'm facing this issue currently on my VPS with a fresh install of Ubuntu 16.04 and have tried both installing yarn with setting a larger network timeout, and ensuring I'm running node 8.11.4. Here's my debug info:

```✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v2.0.1
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@2.0.1: The engine "cli" appears to be invalid.
error Couldn't find the binary git

yarn install v1.9.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1


Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v8.11.4
    Ghost-CLI Version: 1.9.0
    Environment: production
    Command: 'ghost install'
```

Any ideas of what else I could try would be much appreciated!

**Comment by ajmalbinabdulaziz** [comment]
I am trying to install ghost for the first time in 2021 and this error keeps showing like the above. Searched every forum, still can't install node locally. I am having node 16.x, yarn 3.x.. I am gonna look for another headless cms since i can't install ghost.

**Comment by csolorzano** [comment]
Same here. Node v16.15.1, Ghost-CLI Version: 1.21.0

**Comment by Chewie-DT** [comment]
Same to;
OS: Ubuntu, v20.04.4 LTS
Ghost-CLI Version: 1.21.0
Ghost v5.2.3

✔ Checking system Node.js version - found v16.15.1
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking free space
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v5.2.3
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@5.2.3: The engine "cli" appears to be invalid.
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.33"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.34"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.3"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning " > bookshelf@1.2.0" has incorrect peer dependency "knex@>=0.15.0 <0.22.0".
warning " > mock-knex@0.4.9" has incorrect peer dependency "knex@> 0.8 < 2.1".

**Comment by fitwist** [comment]
For Jino server restarting 'ghost install' several times worked. It's may be somehow related to RAM.
