### ISSUE TITLE
`ghost update --rollback` needs to trigger a database rollback

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#699]
## This issue is a

* [x] Bug Report

Please fill out this template, deleting where appropriate:

### Summary

`ghost update --rollback` needs to trigger a database rollback.

### Steps to Reproduce (for a bug report)

1. You are on 1.21.7
2. You update to 1.22.1
3. Now you call `ghost update --rollback`
4. You are back on 1.21.7
5. But you have not rolled back the database.
6. You insert posts on 1.21.7, publish them
7. Now you call `ghost update` again
8. You are on 1.22, but the migration scripts are not re-triggered, because they ran already.
9. You will run into problems, you won't be able to serve the posts you've added in between, because multiple authors relationships were not created for those posts. Ghost could potentially ignore this error instead of throwing an error, but then we don't know that we are producing corrupt database states.

The migration scripts in `1.22` add a new table and migrate all posts to support multiple authors.

`knex-migrator rollback` has to be executed on the 1.22 installation folder.
Then you can switch back to 1.21.7.

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: any
* Node Version: any
* Ghost-CLI Version: latest
* Environment: any
* Command: any

### TODO

- [x] execute db rollback in the CLI at all (trigger knex-migrator)
- [x] extend knex-migrator's feature set (rollback to specific version) (https://github.com/TryGhost/knex-migrator/pull/110)

**Comment by acburdine** [comment]
@kirrg001 Before something like this can be implemented - I think knex-migrator needs to allow specifying a version of migrations to rollback to. Say you had this happen:

1. User is on 1.20.0
2. User upgrades to 1.22.0, which runs db migrations
3. User rolls back to 1.20.0, and migrations are rolled back, but knex-migrator rollback doesn't have the ability to specify 1.20.0 as the version, so their database is in an unknown state.

Once knex-migrator supports this I think it would be pretty simple to implement on the CLI side.

**Comment by kirrg001** [comment]
@acburdine Yeah agree. Knex migrator can currently only rollback the version you are currently on.

**Comment by kirrg001** [comment]
This issue needs to be solved, but knex-migrator doesn't have to be updated yet for Ghost 2.0. We just need to ensure that we trigger a db rollback at all.

But we should update knex-migrator's feature set to allow migrating to a specific version soon.

**Comment by kirrg001** [comment]
All tasks are done. Final QA will happen soon.
