### ISSUE TITLE
Check error codes instead of strings for knex-migrator

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#70]
Hey 👋

Just went through the new release changes and saw https://github.com/TryGhost/Ghost-CLI/commit/004169377d28fe550ddd4aa668ceb687fc652d83#diff-e4e7fada050c1319260e0dda7821fc5aR34

Knex-migrator returns error codes. I would like to suggest using them, they won't change. The string might change with a high chance.

DatabaseIsOK returns `err.code = DB_NOT_INITIALISED` in case of a non initialised database. Soon it will also return `DB_NEEDS_MIGRATION` if your database needs to run migrations.

**Comment by acburdine** [comment]
SGTM :+1:
