### ISSUE TITLE
Ghost can't always install and uninstall.

### ISSUE THREAD

**Issue by Mrcooder** [TryGhost/Ghost-CLI#701]
Hi there.

## This issue is a BUG report.
I had compeletely follow the docs of the website of official to execute commands step by step. But the follow errors is always appeard whether install ghost or uninstall it. Was i input the incorrect password for root?

WARNING: Running this command will delete all of your themes, images, data, any files related to this Ghost instance, and the contents of this folder!
There is no going back!
? Are you sure you want to do this? Yes
Running sudo command: systemctl is-active ghost_mrcodex-com
✖ Stopping Ghost
A ProcessError occurred.

Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_mrcodex-com

failed

Exit code: 3

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.1
    Ghost-CLI Version: 1.6.0
    Environment: production
    Command: 'ghost uninstall'

Additional log info available in: /home/blog/.ghost/logs/ghost-cli-debug-2018-04-11T06_02_41_753Z.log

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.

**Comment by AileenCGN** [comment]
Hey @Mrcooder 

> Additional log info available in: /home/blog/.ghost/logs/ghost-cli-debug-2018-04-11T06_02_41_753Z.log

Can you please provide the log file?

What does `ghost doctor` say?

Can you please also check, if this is related to #660 ?

**Comment by Mrcooder** [comment]
Thanks. @AileenCGN 

I'm afraid of no more information is useful in the log file. Here is the content of log file.

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.1
    Ghost-CLI Version: 1.6.0
    Environment: production
    Command: 'ghost uninstall'
Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_mrcodex-com

failed

Exit code: 3

--------------- stdout ---------------
failed

I have looked #660 through and don't think it's the same issue as me.

**Comment by AileenCGN** [comment]
> What does ghost doctor say?

@Mrcooder can you please run `ghost doctor`, and also `ghost run` and see if there's any useful output? `ghost log -f` might also give some more information.

**Comment by Mrcooder** [comment]
@AileenCGN  There is the output of `ghost doctor`

```
✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking if user is logged in with ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
Running sudo command: systemctl is-active ghost_mrcodex-com
? Password [hidden]
✖ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✖ Checking memory availability
One or more errors occurred.

1) ProcessError

Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_mrcodex-com
#node-sudo-passwd#
failed

Exit code: 3



2) SystemError

Message: Ghost recommends you have at least 150 MB of memory available for smooth operation. It looks like you have 93 MB available.

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.1
    Ghost-CLI Version: 1.6.0
    Environment: production
    Command: 'ghost doctor'

Additional log info available in: /home/blog/.ghost/logs/ghost-cli-debug-2018-04-11T08_53_52_325Z.log

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

And there is the output of `ghost run`:

```
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
Running sudo command: node current/index.js
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
[2018-04-11 08:56:05] ERROR

NAME: InternalServerError
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new GhostError (/var/www/blog/versions/1.22.1/core/server/lib/common/errors.js:9:26)
    at /var/www/blog/versions/1.22.1/index.js:37:15
    at tryCatcher (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

TypeError: Argument 0 must be a string
    at TypeError (native)
    at /var/www/blog/versions/1.22.1/node_modules/knex/lib/dialects/sqlite3/index.js:106:16
    at Promise._execute (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_SQLite3.acquireRawConnection (/var/www/blog/versions/1.22.1/node_modules/knex/lib/dialects/sqlite3/index.js:105:12)
    at create (/var/www/blog/versions/1.22.1/node_modules/knex/lib/client.js:269:23)
    at tryPromise (/var/www/blog/versions/1.22.1/node_modules/tarn/lib/Pool.js:366:22)
    at tryPromise (/var/www/blog/versions/1.22.1/node_modules/tarn/lib/utils.js:57:20)
    at Promise (/var/www/blog/versions/1.22.1/node_modules/tarn/lib/Pool.js:366:5)
    at Promise._execute (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/blog/versions/1.22.1/node_modules/bluebird/js/release/promise.js:79:10)
    at callbackOrPromise (/var/www/blog/versions/1.22.1/node_modules/tarn/lib/Pool.js:357:10)
    at Pool._create (/var/www/blog/versions/1.22.1/node_modules/tarn/lib/Pool.js:307:5)
    at Pool._doCreate (/var/www/blog/versions/1.22.1/node_modules/tarn/lib/Pool.js:275:32)
```

I'm appriciate you very much. 😃

**Comment by jordan-belfort** [comment]
Hello,
I have the same problem when trying to install/uninstall Ghost.

**Comment by kirrg001** [comment]
@Mrcooder 

> Message: Ghost recommends you have at least 150 MB of memory available for smooth operation. It looks like you have 93 MB available.

This should be fixed in the latest CLI release. Please upgrade your CLI :)

> TypeError: Argument 0 must be a string

This looks like a misconfiguration of your database.
Please share your `config.[env].json` with us here.

**Comment by kirrg001** [comment]
@jordan-belfort 

> I have the same problem when trying to install/uninstall Ghost.

Which same problem?

**Comment by Mrcooder** [comment]
@kirrg001 Thank you for your help. I had solved this problem by running ghost in docker. 😄

**Comment by thosakwe** [comment]
Getting the same error. Nearly created a new issue, but since i've found this, let me just add the information so it helps contributors/anyone who has this problem in the future:

## This issue is a

* Bug Report

Please fill out this template, deleting where appropriate:

### Summary

In short, I just upgraded Ghost from, I believe, v1.16.0.
I then ran `ghost restart`, but it seemed that some element of configuration was changed between 1.16.0 and 1.24.0, because the existing `systemd` service file attempted to run NPM scripts in my `/var/www/ghost` directory. However, the `package.json` is in `/var/www/ghost/current`, so this would always break.

So, I backed up my site (!!!), and then ran `ghost uninstall`, and then updated `ghost-cli`, and did a fresh `sudo ghost install`.  All *seemed* to be well after I `chown`-ed all the necessary directories to a regular user account, instead of `root`.

However, this was the point when I reached my bug. Explained below.

### Steps to Reproduce (for a bug report)

1. Run `ghost install` as root.
2. Receive warning message telling you to create a regular user account.
3. Create such an account, `chown -R <username>:<username> /var/www/ghost`, create `~<username>/.ghost`, copy ghost/config
4. `su -i <username>`
5. `ghost start`

Boom! Error:

```
One or more errors occurred.

1) ProcessError

Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_[REDACTED]-com

failed

Exit code: 3


Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.11.3
    Ghost-CLI Version: 1.8.1
    Environment: production
    Command: 'ghost doctor'

Additional log info available in: /home/[REDACTED]/.ghost/logs/ghost-cli-debug-2018-06-06T23_27_30_571Z.log

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

It seems that the given service is never started. So I assumed that I had messed up somewhere in the installation, and decided to reinstall.

However, whichever check is checking for the running ghost service, it also runs before uninstall, which means that if your installation is broken, *you cannot uninstall it*.

### Log file (for a bug report)

```
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.11.3
    Ghost-CLI Version: 1.8.1
    Environment: production
    Command: 'ghost doctor'
Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_[REDACTED]-com

failed

Exit code: 3

--------------- stdout ---------------
failed

```

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

```
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.11.3
    Ghost-CLI Version: 1.8.1
    Environment: production
    Command: 'ghost doctor'
```

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [*] Tried to find help in the forum & docs
- [*] Checked for existing issues
- [*] Attached log file
- [*] Provided technical details incl. operating system

**Comment by kirrg001** [comment]
@thosakwe Thanks for using the search 👍 

When you are logged in with your none-root user. What is the output of

> sudo systemctl is-active ghost_[REDACTED]-com

> ls -la /var/www/ghost

**Comment by thosakwe** [comment]
Sorry for the late response!

```
thosakwe@thosakwe-blog:~$ sudo systemctl is-active ghost_thosakwe-com
failed
thosakwe@thosakwe-blog:~$ ls -la /var/www/ghost
total 28
drwxr-xr-x 5 thosakwe thosakwe 4096 Jun  6 23:11 .
drwxrwxr-x 4 root     root     4096 Sep 25  2017 ..
-rw-r--r-- 1 thosakwe thosakwe  504 Jun  6 23:13 config.production.json
drwxr-xr-x 7 ghost    ghost    4096 Jun  6 23:10 content
lrwxrwxrwx 1 thosakwe thosakwe   30 Jun  6 23:10 current -> /var/www/ghost/versions/1.24.0
-rw-r--r-- 1 thosakwe thosakwe   85 Jun  6 23:11 .ghost-cli
drwxr-xr-x 3 thosakwe thosakwe 4096 Jun  6 23:11 system
drwxr-xr-x 3 thosakwe thosakwe 4096 Jun  6 23:10 versions
thosakwe@thosakwe-blog:~$ 
```

**Comment by thosakwe** [comment]
One more comment, haha.

So, I've done the following:

```bash
$ cd /var/www/ghost/current
$ knex-migrator init
$ knex-migrator migrate
$ sudo service ghost_thosakwe-com restart
```

I'm still getting the same migration error. Perhaps that might be better for a new issue.

**Comment by Mrcooder** [comment]
I have done this by running ghost in docker. 😄

**Comment by thosakwe** [comment]
I’m not currently using Docker, and don’t intend on adding another layer to my stack.

I was ultimately able to `ghost restart` after running the migrations manually, so I would assume that what @acburdine pointed out as the issue is what needs to be fixed.

Thanks for all the help! Ghost is great.

**Comment by PaszaVonPomiot** [comment]
## Fix
- Find service file `ls /lib/systemd/system/ghost_*`
- Add following line in [Service] section
`StartLimitBurst=0`
- restart service or restart server and ghost should be "unlocked"
- after you get it running remove added line from service file

**Comment by Mrcooder** [comment]
@PaszaVonPomiot Thank you for your help
