### ISSUE TITLE
Cannot access our newly created blog

### ISSUE THREAD

**Issue by jordan-belfort** [TryGhost/Ghost-CLI#705]
Hi everybody !

I just freshly installed the self-hosted Ghost with the CLI command and everything was fine untill I started the ghost server and tried to access to the blog with the URL I wrote during the installation but I don't get any response from the blog and the Chrome white page "The website isn't working"...
Can someone help me ?

Here is the config file in my ghost directory in "/var/www/ghost":
`{
  "url": "https://blog.test.com",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  },
  "database": {
    "client": "mysql",
    "connection": {
      "host": "localhost",
      "user": "ghost",
      "password": "test",
      "database": "ghost_prod"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/www/ghost/content"
  }
}`

Thanks !

**Comment by kevinansfield** [comment]
Hey @jordan-belfort  👋 Please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
