### ISSUE TITLE
Solaris/Illumos (sunos x64) broken in 1.7.x

### ISSUE THREAD

**Issue by hadret** [TryGhost/Ghost-CLI#706]
## This issue is a

* [X] Bug Report
* [ ] Feature Request

### Summary

**I understand this is not a recommended stack** -- that being said, `ghost-cli` and `ghost` itself did work perfectly fine on Solaris/Illumos (sunos x64) until the most recent changes. The problem lies in usage/new dependency on `systeminformation` that is not supporting `sunos`. This has not been a problem on the current `ghost-cli` version I'm running on this platform (1.5.1).

### Steps to Reproduce (for a bug report)

1. `npm install -g ghost-cli@latest` on Solaris/Illumos OS

This has been working perfectly fine until the most recent release of `ghost-cli` 1.7.x.

### Log file (for a bug report)

```
npm ERR! SunOS 5.11
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "-g" "ghost-cli@latest"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for systeminformation@3.37.8: wanted {"os":"darwin,linux,win32,freebsd,openbsd","arch":"any"} (current: {"os":"sunos","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux,win32,freebsd,openbsd
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   sunos
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin/npm-debug.log
```

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: SunOS 5.11
* Node Version: 6.12.2
* Ghost-CLI Version: 1.5.1

I created a bug report on the `systeminformation` side https://github.com/sebhildebrandt/systeminformation/issues/126. For the time being I was hoping though that this dependency could be dropped maybe?

**Comment by sebhildebrandt** [comment]
I will try to implement basic SunOS support for the `systeminformation` package. Hope I will be able to provide a first version next week.

**Comment by AileenCGN** [comment]
Closing, as `systeminformation` was updated with https://github.com/TryGhost/Ghost-CLI/commit/d43efd7dc85c1865f1e1b028b045b3894f402c63 and this issue should be solved with it.
