### ISSUE TITLE
Ghost and Ubuntu 14.04

### ISSUE THREAD

**Issue by yamsellem** [TryGhost/Ghost-CLI#707]
## This issue is a

* [x] Bug Report

### Summary

I'm trying to install ghost on Ubuntu 14.04 (_Ubuntu 16 is recommended, but not as compulsory_). I've already installed Ngninx previously, and want to use sqlite3 (_and no systemd_).

Is using Ubuntu 14.04 is not possible with ghost-cli?
Ghost doctor don't show any problem, and the error message don't make any sense to me, `The content folder is not owned by the current user.` because I've followed every steps of the manual.

### Steps to Reproduce (for a bug report)

```
sudo apt-get update
sudo apt-get upgrade

adduser root-ghost
usermod -aG sudo root-ghost
su - root-ghost

sudo npm i -g ghost-cli
sudo mkdir -p /var/www/ghost-fresh
sudo chown root-ghost:root-ghost ghost-fresh
sudo chmod 775 ghost-fresh/

ghost install --db=sqlite3
```

### Log file (for a bug report)

Install process logs:

```
✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking current folder permissions
System checks failed with message: 'Linux version is not Ubuntu 16'
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? Yes
ℹ Checking operating system compatibility [skipped]
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v1.22.3
✔ Finishing install process
? Enter your blog URL: http://localhost:2378
✔ Configuring Ghost
✔ Setting up instance
Running sudo command: chown -R ghost:ghost /var/www/ghost-fresh/content
✔ Setting up "ghost" system user
? Do you wish to set up Nginx? No
ℹ Setting up Nginx [skipped]
Task ssl depends on the 'nginx' stage, which was skipped.
ℹ Setting up SSL [skipped]
? Do you wish to set up Systemd? No
ℹ Setting up Systemd [skipped]
Running sudo command: /var/www/ghost-fresh/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost-fresh/current
✔ Running database migrations
? Do you want to start Ghost? Yes
Process manager 'systemd' will not run on this system, defaulting to 'local'
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✖ Starting Ghost
A SystemError occurred.

Message: The content folder is not owned by the current user.
Please ensure the content folder has correct permissions and try again.
```

Ghost doctor logs:

```
Process manager 'systemd' will not run on this system, defaulting to 'local'
✔ Checking system Node.js version
✔ Checking logged in user
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
System checks failed with message: 'Linux version is not Ubuntu 16'
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? Yes
ℹ Checking operating system compatibility [skipped]
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
```

Permissions (`ls -a`):

```
-rw-rw-r-- 1 root-ghost root-ghost  425 Apr 20 10:36 config.production.json
drwxrwxr-x 8 ghost      ghost      4096 Apr 20 10:35 content
lrwxrwxrwx 1 root-ghost root-ghost   36 Apr 20 10:35 current -> /var/www/ghost-fresh/versions/1.22.3
drwxrwxr-x 3 root-ghost root-ghost 4096 Apr 20 10:35 versions
```

### Technical details (for a bug report)

* OS: Ubuntu, v14.04
* Node Version: v6.14.1
* Ghost-CLI Version: 1.7.1
* Environment: production
* Command: 'ghost start'

## Bug submission checklist

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by yamsellem** [comment]
I've made my way through it with a [manual install](https://nehalist.io/installing-ghost-1-0-without-ghost-cli/). Everything work fine that way (_and it seems simpler — as a node developer_).

**Comment by ErisDS** [comment]
> I've made my way through it with a manual install. Everything work fine that way (and it seems simpler — from a node developer perspective).

FYI @yamsellem that linked article does about 5% of the things that ghost-cli does - that's why it seems simpler 😉  Ghost-CLI aims to get you to a state where `ghost update` will always work, and eventually can be entirely automated, as well as setting up nginx, systemd and SSL for you.

This also explains part of why 14.04 is not supported - it doesn't have systemd, which is what Ghost CLI uses to keep Ghost running.

All that being said - there definitely is something off with the error messaging here.

**Comment by acburdine** [comment]
The error messaging is correct. What is happening is this:

- Ghost-CLI creates the `ghost` linux user because the OS is linux, and chown's the content folder to the ghost user
- Systemd setup is skipped, local-process manager is used
- Local process manager is only designed to run as the current user (which is _not_ the ghost system user)
- it errors out because the content folder is not owned by the current user.

**Comment by acburdine** [comment]
There's probably an improvement that can be made here to either:
- skip the ghost system user setup if not systemd (or maybe add a process-manager class property to indicate whether or not the process manager should use the linux user?)
- add improvements to the local-process manager allowing it to use the ghost linux user to run if it's setup.

**Comment by yamsellem** [comment]
@EricDS I get the idea of a cli and automated updates. What I was saying is that configuring nginx & ssl is not a problem to me, so installing ghost without the cli wasn't that hard. 

You're saying that Ubuntu 14.04 is not supported meanwhile the docs says `recommanded` about 16.04 not `compulsory`.

May you imagine a compatible version of the cli for 14.04, even without some features?

**Comment by AileenCGN** [comment]
@yamsellem 

> You're saying that Ubuntu 14.04 is not supported meanwhile the docs says recommanded about 16.04 not compulsory.

We're explaining in our [README](https://github.com/TryGhost/Ghost-CLI#recommended-stack) why we can't support other stacks than the recommended one. It does not not mean that it's "compulsory". It just means, that we can't guarantee at all if it works on other stacks and we will not be able to support this as well. The community is always welcome to submit PRs for requested features.

I hope, you understand 😊

**Comment by ErisDS** [comment]
Ubuntu 14 is now EOL so I think we can close this.
