### ISSUE TITLE
Help needed for strange Exit code: 3 

### ISSUE THREAD

**Issue by squadramunter** [TryGhost/Ghost-CLI#709]
I've got some problems setting up ghost cli on my raspberry pi 3B. Is there a way to fix this issue?

Debug Information:
    OS: Raspbian, v8.0
    Node Version: v6.14.1
    Ghost-CLI Version: 1.7.1
    Environment: production
    Command: 'ghost setup'
Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_ghost-local

unknown

Exit code: 3

--------------- stdout ---------------
unknown

**Comment by kirrg001** [comment]
Hi @squadramunter!

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [forum](https://forum.ghost.org/) - https://forum.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
