### ISSUE TITLE
What to do if I already have letsencrypt in my machine and install ghost?

### ISSUE THREAD

**Issue by vincent-cm** [TryGhost/Ghost-CLI#710]
If it comes the prompt asking if SSL required?

**Comment by AileenCGN** [comment]
Hi @vincent-cm 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [forum](https://forum.ghost.org/) - https://forum.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
