### ISSUE TITLE
Setting up SSL fails on brand new install

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost-CLI#715]
## This issue is a

* [X] Bug Report
* [ ] Feature Request

### Summary

After setting up a brand new droplet on DO, following exactly the instructions on doc.ghost.org, the setup flow always fails when trying to setup the SSL cert.

**NOTE**: The setup **does not** fail on my older, existing droplet!

### Steps to Reproduce (for a bug report)

1. Set up a new Droplet on DO (1GB or 2GB)
2. Follow the instructions on https://docs.ghost.org/docs/install
3. Set up a new blog, replying 'yes' to everything
4. See it failing when fetching the SSL certificate

### Log file (for a bug report)

```
Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  /etc/letsencrypt/acme.sh --issue --home /etc/letsencrypt --domain cli.example.com --webroot /var/www/ghost/system/nginx-root --reloadcmd "nginx -s reload" --accountemail aileen@ghost.org
[Fri May  4 07:15:48 UTC 2018] cli.example.com:Verify error:Invalid response from http://cli.example.com/.well-known/acme-challenge/4Iig7VvVT2Smtoglw_AmPc2PJ94aNN2yvDzwGrBt9Og:
[Fri May  4 07:15:48 UTC 2018] Please add '--debug' or '--log' to check more details.
[Fri May  4 07:15:48 UTC 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

[Fri May  4 07:15:43 UTC 2018] Single domain='cli.example.com'
[Fri May  4 07:15:43 UTC 2018] Getting domain auth token for each domain
[Fri May  4 07:15:43 UTC 2018] Getting webroot for domain='cli.example.com'
[Fri May  4 07:15:43 UTC 2018] Getting new-authz for domain='cli.example.com'
[Fri May  4 07:15:44 UTC 2018] The new-authz request is ok.
[Fri May  4 07:15:44 UTC 2018] Verifying:cli.example.com

Exit code: 1

--------------- stdout ---------------
[Fri May  4 07:15:43 UTC 2018] Single domain='cli.example.com'
[Fri May  4 07:15:43 UTC 2018] Getting domain auth token for each domain
[Fri May  4 07:15:43 UTC 2018] Getting webroot for domain='cli.example.com'
[Fri May  4 07:15:43 UTC 2018] Getting new-authz for domain='cli.example.com'
[Fri May  4 07:15:44 UTC 2018] The new-authz request is ok.
[Fri May  4 07:15:44 UTC 2018] Verifying:cli.example.com


--------------- stderr ---------------
[Fri May  4 07:15:48 UTC 2018] cli.example.com:Verify error:Invalid response from http://cli.example.com/.well-known/acme-challenge/4Iig7VvVT2Smtoglw_AmPc2PJ94aNN2yvDzwGrBt9Og:
[Fri May  4 07:15:48 UTC 2018] Please add '--debug' or '--log' to check more details.
[Fri May  4 07:15:48 UTC 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

### Technical details (for a bug report)

- OS: Ubuntu, v16.04
- Node Version: v6.14.2
- Ghost-CLI Version: 1.7.2
-  Environment: production
-  Command: 'ghost install'

**Comment by AileenCGN** [comment]
Well, nvm me here... I forgot to point my DNS to the new droplet... I'll change this issue to be an enhancement for the error message...

**Comment by trahn** [comment]
> Well, nvm me here... I forgot to point my DNS to the new droplet... I'll add this to the issue for the error message improvements: #587

@AileenCGN That is what I just did... forgot to point my DNS when I did an URL change. I got some error and now can't seem to get my installation to work again. Can you maybe point me to what nginx and ssl files I should delete to run the `ghost setup nginx ssl` again? Also, I seem not to be able to restart nginx manually (using the DO image and ghost-mgr user). Hope you can help. :)
