### ISSUE TITLE
`ghost start` with non-default port links outputs incorrect link

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost-CLI#716]
## This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

When running `ghost start` with a local install that is configured to use a non-default port the "you can access your blog at" message displays the default port rather than the configured port.

### Steps to Reproduce (for a bug report)

1. `ghost install local`
2. `ghost stop`
3. Modify `config.development.json` and change the `url.port` to a different number, eg `2340`
4. `ghost start`
5. Note the log says `You can access your blog at http://localhost:2368/` despite the blog actually running on http://localhost:2340/

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: macOS High Sierra (10.13.4)
* Node Version: 8.10.0
* Ghost-CLI Version: 1.7.2
* Environment: development
* Command: `ghost start`

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [ ] Attached log file
- [x] Provided technical details incl. operating system

**Comment by AileenCGN** [comment]
Indeed, the rendered output is only looking on the `url` property in the config.
