### ISSUE TITLE
`ghost update` fails as some of my files have different permissions

### ISSUE THREAD

**Issue by YOnoda** [TryGhost/Ghost-CLI#718]
I found that after I upgraded to the version 1.5 or later, the system is no longer upgradable if I have some files on the directory that have wrong premissions (`ghost doctor` fails). But these files are irrelevant of the ghost (they are my own scripts) and I still want to upgrade it to the latest version. 

The `ghost update -f` command also failed. Is there any way to upgrade it? Or if not, any chance that it will change in a later version? Thanks

**Comment by AileenCGN** [comment]
Hey @YOnoda  👋 

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
