### ISSUE TITLE
ghost run fails complains about mysql connection with is not used.

### ISSUE THREAD

**Issue by origin1tech** [TryGhost/Ghost-CLI#720]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in our forum: https://forum.ghost.org 👫.

Docs: https://docs.ghost.org 📖.

Please be aware that the team behind the Ghost CLI only supports the recommended stack: https://github.com/TryGhost/Ghost-cli#recommended-stack.

## This issue is a

* [ x] Bug Report
* [ ] Feature Request

Please fill out this template, deleting where appropriate:

### Summary

When using "ghost run" and error is thrown. In my case ECONNREFUSED 127.0.0.1:3306. Obviously this is because there is not local mysql server on my system hence the error.

The problem is this error shouldn't be thrown, or at least I wouldn't expect it to, because I'm not using mysql but rather sqlite in my configuration.

When calling "ghost start" the issue does not exist but need to be able to debug.

### Steps to Reproduce (for a bug report)

    $ ghost run

### Log file (for a bug report)

![screen shot 2018-05-13 at 11 05 08 pm](https://user-images.githubusercontent.com/1781771/39980712-1cf1de52-5702-11e8-8d80-fbb14c73d00b.png)

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: macOS (High Sierra)
* Node Version: 6.10
* Ghost-CLI Version: 1.7.3
* Environment: development

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by AileenCGN** [comment]
@origin1tech

Seeing that you're using Ghost in development mode, you'd need to run `ghost run -D`, as otherwise it'll starts in production mode.

Nevertheless, this looks like something that can be improved. Thanks for the report!

**Comment by origin1tech** [comment]
Yeah found that, got local installs working fine, good there. 

thx again for catching that.
