### ISSUE TITLE
Ghost Upgrade/Install 1.23.0 Local Fails

### ISSUE THREAD

**Issue by dhstack** [TryGhost/Ghost-CLI#725]
Installation seems to finish, but ghost doesn't start. It stops when trying to load lodash.

I originally tried to update my local ghost installation, but got the same issue. After a few hours of troubleshooting decided I should post here.

### Summary

Trying to update ghost, but it's not working. Here's the output. And the log is below.

D:\Documents\ghost3>ghost install local
√ Checking system Node.js version
√ Checking current folder permissions
√ Checking memory availability
√ Checking for latest Ghost version
√ Setting up install directory
√ Downloading and installing Ghost v1.23.0
√ Finishing install process
√ Configuring Ghost
√ Setting up instance
× Running database migrations
A ProcessError occurred.

Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error

Debug Information:
    OS: Microsoft Windows, v10.0.17134
    Node Version: v8.11.2
    Ghost-CLI Version: 1.7.3
    Environment: development
    Command: 'ghost install local'

Additional log info available in: C:\Users\David\.ghost\logs\ghost-cli-debug-2018-05-23T00_06_12_015Z.log

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.

### Steps to Reproduce (for a bug report)

I already tried to upgrade/uninstall/reinstall npm, but that didn't work either.

### Log file (for a bug report)

```
Debug Information:
    OS: Microsoft Windows, v10.0.17134
    Node Version: v8.11.2
    Ghost-CLI Version: 1.7.3
    Environment: development
    Command: 'ghost install local'
Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error
--------------- stderr ---------------
D:\Documents\ghost3\versions\1.23.0\node_modules\lodash\flatten.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Documents\ghost3\versions\1.23.0\node_modules\lodash\_flatRest.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

### Technical details (for a bug report)

    OS: Microsoft Windows, v10.0.17134
    Node Version: v8.11.2
    Ghost-CLI Version: 1.7.3
    Environment: development
    Command: 'ghost install local'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
Can you try to clear your yarn cache (`ghost buster`) and force the update to run again (`ghost update -D --force`)?

As of now, this seems more like an isolated issue rather than a bug in the CLI, so it's better suited for the [forum](https://forum.ghost.org)

**Comment by dhstack** [comment]
@vikaspotluri123 Looked like that worked! Wish I knew about that `ghost buster` command...

Thanks for your fast response and help!
