### ISSUE TITLE
Duplicated log lines on `ghost log`

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#741]
## This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

`ghost log -f` shows every log entry twice.
This was also mentioned in the forum: https://forum.ghost.org/t/scheduled-posts-dont-publish/1179/28

### Steps to Reproduce (for a bug report)

I don't know if this always happens or in specific circumstances.

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Ubuntu 16
* Node Version: 6
* Ghost-CLI Version: 1.7.3
* Environment: prod
* Command: `ghost log -f`

**Comment by acburdine** [comment]
Closing in favor of https://github.com/TryGhost/Ghost/issues/9656
