### ISSUE TITLE
Content folder permissions

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#745]
### Summary

The files in the content folder of your blog installation have the following permissions:

- in production
- 644 for files
- owned by the Ghost user

The problem with these restrictions is that if i am logged in with my custom ubuntu user (which is the default case), i am not allowed to edit these files, because they are owned by the `ghost` user with 644 permissions. I have to change the permissions to e.g. `646` or i have to use `sudo` to edit the files.

This feels like we got the permissions wrong. The `content` folder is for **user data**. The challenge is to support both:

- that the `ghost` user needs to be able to write files in the content folder
- that the ubuntu user is able to edit the files

### Possible solution

Use a ghost group and change the permissions to 664.

This needs further research.

**Comment by kirrg001** [comment]
Another use case:

- you upload a theme
- you would like to change posts per page in the package.json of the theme
- read only file

**Comment by dsecareanu** [comment]
I know it is somewhat unrelated (or rather broader), but here's another use case:
- multiple websites on a server
- nginx user is www-data or nginx (no shell user) by default
- /srv/www or /var/www has folders with multiple user.group combinations (nginx, ubuntu, etc.)
- some best practices recommend using a /home/user folder approach

This sometimes causes file permission issues (took me a while to figure it out that nginx eventually can serve ubuntu.ubuntu files/folders (tried ubuntu.nginx and other user.group variations, coupled with the ghost.ghost permissions of the content folder).

So not sure what would be the best approach (as the issue with nginx or www-data is that they're non shell users), but I assume there are some cases of people hosting multiple websites on the same server and going through a similar setup as described above.

So I would assume that there should be a recommended approach and the user setup should make it easy to be handled (i.e. not require multiple users ownership of ghost files).

**Comment by kirrg001** [comment]
@acburdine Do you have any thoughts on this?

**Comment by kirrg001** [comment]
This might get less important for the CLI in the next time, if we can ship a simple UI to upload and reload the routes.yaml via the admin client.

**Comment by acburdine** [comment]
Yeah, a similar approach might actually be the best approach for the CLI. Maybe some sort of command `ghost content edit <file>` or something that would edit the file in your favorite editor, then save the file back as the ghost user, thus preventing any issues with file permissions.

It's a bit of a workaround to the actual problem, but it seems like a decently clean solution

**Comment by TonnyORG** [comment]
@kirrg001 don't you suppose to have sudo access with your own username? I mean from my perspective ghost-cli already uses sudo for several operations, that said getting used to use `sudo vi` is like what I'm doing now but would be nice to have a command like `ghost permissions` or something like that that you can run after finishing your editions, theme uploads, etc in your ghost installation folder and basically runs `chmod` and `chown` to change or fix permissions and folders as they needed  to be compatible with Ghost.

The main Q is, why Ghost has to run under ghost user?
Why couldn't it run under our own user? 
I think if we could get this solved, many problems will solve as well and more flexible the path and OS would be.

BTW @dsecareanu even when the Docs said the opposite, you can actually install ghost in your home folder without any issues. I have got that working right now (multiple ghost installations inside /home/myuser folder) on Ubuntu 18.04. So you don't have to deal with the user.group combinations for nginx and ubuntu on the /var folder.

**Comment by Leandros** [comment]
yes, please!
