### ISSUE TITLE
ghost start shouldn't enable the systemd service by default

### ISSUE THREAD

**Issue by hao-lee** [TryGhost/Ghost-CLI#747]
## This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

The [`ghost start` documentation](https://docs.ghost.org/docs/cli-start) provides an option `--enable` that can enable the systemd service, so I think the default behavior of `ghost start` shouldn't execute `systemctl enable <ghost-service-name>`. However, after running `ghost start xxx`, the corresponding systemd service is enabled.

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: N/A
* Node Version: N/A
* Ghost-CLI Version: 1.8.1
* Environment: N/A
* Command: N/A

## Bug submission checklist

- [ ] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [ ] Attached log file
- [ ] Provided technical details incl. operating system

**Comment by acburdine** [comment]
@hao-lee The reason it's the way it is in the code is that if you give yargs a boolean flag option it will automatically parse `--no-<that boolean option>` as the inverse of it. Can update the docs though.

**Comment by acburdine** [comment]
Docs have been updated.
