### ISSUE TITLE
Admin interface location incorrect

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost-CLI#748]
### Summary

When running ghost, if a subdirectory is configured but no explicit admin url is configured the CLI outputs the admin's location incorrectly.

### Steps to Reproduce (for a bug report)

1. Create a local install (`ghost install local`)
2. Configure the url to be a subdirectory (`config set url http://localhost:2369/test` - change depending on the port that the CLI gave you)
3. Start ghost (`ghost start`)

Ghost-CLI will now output info about the Ghost install:

```
❯ ghost start
Found a development config but not a production config, running in development mode instead
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Starting Ghost
You can access your publication at http://localhost:2369/test
Your admin interface is located at http://localhost:2369/ghost/
```

The admin URL here should be http://localhost:2369/test/ghost/

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: macOS High Sierra
* Node Version: 8.10.0
* Ghost-CLI Version: 1.8.1
* Environment: development / local

**Comment by acburdine** [comment]
Should be a fairly simple fix - we're using url.resolve [here](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/commands/start.js#L67) to build the admin url, and it looks like (according to the [node docs](https://nodejs.org/api/url.html#url_url_resolve_from_to)) that if there's not a trailing slash at the end of the `from` portion of the url (in this case meaning the configured url) it will remove that portion from the end url.

Quickest solution is to make sure in the CLI that the url getting passed to `url.resolve` has a trailing slash.
