### ISSUE TITLE
No command 'ghost' found

### ISSUE THREAD

**Issue by wikibady** [TryGhost/Ghost-CLI#757]
i use <code>sudo npm install -g ghost-cli</code> to install the cli as a global command,but when i try <code> ghost install</code>,it show a <code> No command 'ghost' found...</code>

**Comment by wikibady** [comment]
http://blog.webbb.be/command-not-found-node-npm/

**Comment by dikaio** [comment]
Also wanted to mention for those who are installing ghost via `yarn global add ghost-cli@latest` or `npm install ghost-cli@latest -g` **and** you've installed via [asdf](https://github.com/asdf-vm/asdf) you'll just need to reshim nodejs e.g. `asdf reshim nodejs` - Good Luck!

**Comment by agamm** [comment]
Add this to ~/.bashrc: `export PATH="$PATH:$(npm get prefix)/bin"`

**Comment by wikibady** [comment]
自动回复------
     您好，您的邮件我已收到。谢谢！
                                
 
 
 
                                    刘彬德

**Comment by RussQuan** [comment]
> export PATH="$PATH:$(npm get prefix)/bin"

it helps! thanks!

**Comment by wikibady** [comment]
自动回复------
     您好，您的邮件我已收到。谢谢！
                                
 
 
 
                                    刘彬德
