### ISSUE TITLE
CLI support for Ghost 2.0

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#759]
[Ghost 2.0 is coming.](https://github.com/TryGhost/Ghost/issues/9742) 🤠

We will release a new **minor** CLI version before we release Ghost 2.0. This new CLI version will add support to upgrade your blog to Ghost 2.0. Furthermore the new CLI version will add support to stay on Ghost 1.0.

### Install/Update a Ghost 2.0 blog

If you execute `ghost update` and your are on 1.0, you will update to the next major. If you are on the next major (Ghost 2.0) and you execute `ghost update` you will update to the next Ghost 2.x release.

If you execute `ghost install` you will install a Ghost 2.0 blog.

### Install/Update a Ghost 1.0 blog

The CLI will add a new flag `--v1`. This flag will tell the CLI to either install or update a Ghost 1.0 blog (`ghost install --v1` or `ghost update --v1`). 

e.g. People who are still on LTS need an option to install a Ghost 1.0, because we disallow the jump from LTS to 2.0. We will only support the latest (2.0) and the previous (1.0) version. This is a new general concept we came up with. The same rule applies to [GScan](https://github.com/TryGhost/gscan/issues/116).

e.g. If we release a new 1.0 release after the Ghost 2.0 release, you can upgrade your blog to the latest 1.0 release with `ghost update --v1`.

### Guide to upgrade to Ghost 2.0

The CLI will add a proper support for the migration to Ghost 2.0

- print link to a new migration guide, which explains how the migration works
- scan your theme with GScan
- output the report from GScan
- print a link to the new demo draft post we will ship next week (a post about how the [new editor König](https://github.com/TryGhost/Ghost/issues/9724) works)
- the ability to continue/abort the major migration
- if the user continues
  - the CLI will download/install Ghost 2.0
  - Ghost 2.0 will use the same blog config
  - CLI will stop the 1.0 blog
  - CLI will start the 2.0 blog
  - Ghost 2.0 will bring the blog automatically into maintenance mode
  - Ghost 2.0 will then run the migration scripts
  - if successful, blog is out of maintenance mode
    - we use a net server communication (which is optional and needs to be configured from the outer unit)
  - if an error occurs during migrations, knex-migrator will auto rollback, the CLI must react and symlink the previous 1.0 version and start the blog
    - we have to send a socket + child event to receive the proper error message
- if the user aborts
  - the user stays on Ghost 1.0, nothing happens

Ghost 2.0 will tag this new CLI release as [minimum cli engine version](https://github.com/TryGhost/Ghost/blob/1.24.9/package.json#L29) in the package.json. This will avoid that people with an older CLI version can update to Ghost 2.0. We want that they can enjoy our guidance to jump to the next major version.

### Knex-Migrator

Knex-Migrator will be the main instrument to jump from Ghost 1.0 to Ghost 2.0.
We will add migration scripts into Ghost 2.0, which will get executed when the Ghost 2.0 blog starts.

We will move the execution of Knex-Migrator from the CLI to Ghost core. The main reason is that we currently have three components which need to execute knex-migrator: the CLI, local development and Ghost(Pro). We think it makes sense to put it back into Ghost core. Therefor we will add a new condition into the CLI to only execute knex-migrator if the blog is on 1.0. We have to ensure that knex-migrator is still called for Ghost 1.0 blogs.

### `ghost update` should be smoother

This issue is tracked [here](TryGhost/Ghost-CLI#726). 

### In discussion

We might force the user to upgrade to the latest Ghost 1.0 version before they can jump to Ghost 2.0. The main reason is that we might remove the 1.0 migration scripts in 2.0. But this is still in discussion.

---

I thought it makes sense to raise this is as early as possible. If you have any questions or concerns, just leave a comment.

**Comment by vikaspotluri123** [comment]
Let me know if there's anything you would like for me to do! 😄

**Comment by kirrg001** [comment]
@vikaspotluri123 Thanks so much! 🙃

I will start with the implementation on Wednesday next week. First of all, if you want you could read the issue and check if we have forgotten anything e.g. problems we can run into, edge cases.

Furthermore, you could let me know till Wednesday which task you are interested and then we can talk about it :)

**Comment by vikaspotluri123** [comment]
I've been thinking about the `--v1` flag - imo it's kind of specific - When ghost n+1 releases, we will need to add the `--v{n}` flag. Since there's a lot of work required to release a semver major relase, this might be something to think about afterwards - maybe a  `--version {n}` flag 🤔

Other than that I can't think of anything, but I'll definitely post if I do!

**Comment by kirrg001** [comment]
When we release Ghost 3.0, we only have to change `--v1` to `--v2`. Could be one global configuration flag.

I agree the notation can be discussed. We already have a `--version` parameter in the CLI to install specific Ghost versions, but we still need a way to define e.g. `ghost update --v1`.

**Comment by vikaspotluri123** [comment]
That's right!

 - When 2.0 is released would 1.0 be considered LTS?
 - When 3.0 is released will it still be ~possible~ allowable to install 1.0?

**Comment by kirrg001** [comment]
> When 2.0 is released would 1.0 be considered LTS?

Yes, 1.0 will go into long term support yes.

> When 3.0 is released will it still be possible allowable to install 1.0?

Hmm i don't think so - not with the latest CLI version.

**Comment by vikaspotluri123** [comment]
So based on that, could we just use an `--lts` flag instead? 🤔

**Comment by acburdine** [comment]
> So based on that, could we just use an --lts flag instead? 🤔

+1 to that approach.

My thought is we could potentially make use of npm's dist-tags feature. In doing so, we could publish Ghost 2.0 prereleases (if we want to do that) to npm's `next` tag, and people could potentially install it using `ghost install --next` or `ghost update --next`. We could add a disclaimer or something in Ghost-CLI in the meantime so that when Ghost 2.0 _does_ get released, people would see something like this:

```
$ ghost update
Ghost 2.0 has been released! Please note that upgrading to Ghost 2.0 will put your blog in "maintenance mode" while migrations are being run. <insert docs link here>
Do you wish to upgrade to 2.0? (y/n)
```

Running `ghost update --next` at this point would skip the prompt. `ghost install` would install 2.0, and then you could run `ghost install --lts` or `ghost update --lts`, which could use npm's `lts` dist tag, meaning that LTS releases would be more distinct from mainline 2.0 releases.

Hopefully that makes sense 😅 I think it's an approach that will be more flexible and also be a bit more maintainable in the future.

**Comment by kirrg001** [comment]
> So based on that, could we just use an --lts flag instead?

Yeah maybe 👍 Will discuss && confirm asap.

> In doing so, we could publish Ghost 2.0 prereleases

I don't think it will happen this time. Not planned.

> make use of npm's dist-tags feature

This is in general a nice idea. I just wonder if you can use the `lts` tag for multiple Ghost versions.

**Comment by kirrg001** [comment]
> So based on that, could we just use an --lts flag instead?

We had a discussion about the idea. In general it's a nice idea and thanks @vikaspotluri123 for your input, but we all have concerns with using a generic flag.

- we can't guarantee that Ghost 0.11 is out of LTS when we ship Ghost 2.0
- that means there are times where we have to support two LTS versions
- we don't want to back ourself's into corners
- a generic flag might be harder to handle - we have to answer questions like
  - if you are on Ghost 1.0 and a security patch for Ghost 1.0 is available, but Ghost 3.0 is already out - will you allow to stay on Ghost 1.0 or does `ghost update --lts` force you to upgrade?
  - same like: if you are on Ghost 1.0 and Ghost 4.0 is already out, we currently don't allow to migrate from 1.0 to 4.0 directly
- in comparison: npm also makes use of versions e.g. `@latest-1` or `@latest-2`

It would have been nice to find a different solution, but for now we would like to stay explicit and use `--v1`.

**Comment by kirrg001** [comment]
@acburdine Is there any other minor release planned in the next three weeks?

**Comment by kirrg001** [comment]
> Not a pressing one, no - we can hold off on any minor releases until Ghost 2.0 support is fully implemented in the CLI

That would be cool. I think i'll base my pull requests against a 1.9 branch. I don't want to keep the pull requests open for the next 2 weeks. If we want to release 1.9, we can PR 1.9 against master.

**Comment by kirrg001** [comment]
FYI.

The goal is to have everything implemented by next Friday.

@acburdine wanted to work on the `--v1` flag logic. Please let me know till Tuesday if you are going to be able to add the logic for it :)

@vikaspotluri123 Things which would be helpful:

- test https://github.com/TryGhost/Ghost-CLI/pull/765 (i would like to merge this PR asap into the 1.9 branch) - i can share a 2.0 pre build with you for testing
- it would be nice if the migration to 2.0 fails, to bring back the 1.0 blog automatically
  - Ghost-CLI will receive an error, print the error
  - ask the user if he wants to bring back the previous version?
  - do symlink magic
  - start blog
  - i guess, this logic should for now only apply if you migrate to 2.0 (i don't want to mess or introduce new bugs for the 1.0 blogs)

Thanks for guys for any help 💛! Even if it's just reviewing or testing!

**Comment by vikaspotluri123** [comment]
> test #765 (i would like to merge this PR asap into the 1.9 branch) - i can share a 2.0 pre build with you for testing

Working on that right now! A pre-build would be appreciated 👍

**Comment by kirrg001** [comment]
> In discussion
> We might force the user to upgrade to the latest Ghost 1.0 version before they can jump to Ghost 2.0. The main reason is that we might remove the 1.0 migration scripts in 2.0. But this is still in discussion.

I think we have to do that. Actually i thought last week we could allow that, but....

Example case:
- you are on 1.17.0
- we allow you to upgrade to 2.0 directly
- the model layer has changed e.g. amp field was renamed to comment_id
- knex-migrator runs through all migration scripts between 1.18 and 2.0
- migration script 1.25 inserts a post using the model layer
- it will crash because it tries to insert a post with the field "comment_id", which doesn't exist yet

**Comment by kirrg001** [comment]
@vikaspotluri123 Thanks. I haven't tested your code snippet, but i think something like this could work 👍Maybe it's nice to use a flag e.g. `--confirm` for people who always want to confirm to rollback.

> // is this check really needed?
    if (previousVersion.indexOf('1' === 0)) {

I mean in theory it's not needed, because it would be nice to always ask the user if he wants to bring back the previous version?

**Comment by kirrg001** [comment]
@vikaspotluri123 Will you PR https://github.com/TryGhost/Ghost-CLI/issues/759#issuecomment-408619027? If yes, i need an estimation. Thanks 👋 :)

**Comment by vikaspotluri123** [comment]
I'll try to have something up in the next 6-8 hours!

**Comment by kirrg001** [comment]
Please raise all pull requests against the 1.9 branch. Thanks!

**Comment by kirrg001** [comment]
1.9 was released.
