### ISSUE TITLE
Add `yarn check` test to `ghost doctor`

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#760]
refs #726 

### Summary
https://yarnpkg.com/en/docs/cli/check#toc-yarn-check-verify-tree

This yarn command might be useful in verifying that all dependencies were successfully installed. Doesn't take too long to run, and might help catch random states where certain dependencies didn't get installed correctly for whatever reason.

**Comment by ErisDS** [comment]
Closing in favour of #1205 because `yarn check` doesn't work properly and is deprecated.
