### ISSUE TITLE
Fix issue with systemd "failed" state

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#761]
### Summary

Right now, Ghost-CLI only has 2 options when it comes to determining the status of a Ghost instance: "running" and "not running". This has become problematic in the past, because systemd (which is used by default in production on Ubuntu) has the concept of a third state: "failed". This state occurs whenever the Ghost instance failed to start for a certain reason (e.g. a bad configuration file). Because of this, we currently throw an error when systemd is in state: "failed". 

What I think we should do in the short term is fix the systemd process manager to output a more helpful error message (maybe auto-run `journalctl` to determine _why_ it's in a failed state?) and maybe in the future refactor that particular part of the process manager to be able to handle that 3rd state more cleanly.

**Comment by kirrg001** [comment]
Can't we just restart the blog with systemd if the status is failed? It will work in certain cases e.g. if you blog died after systemd has retried too often. But isn't it worth just trying to execute `system restart`? It can in worst case just fail again.

I agree a clear error message would be helpful as well 👍

**Comment by kirrg001** [comment]
This is something we have to fix for CLI 1.9, i was running into this error today a couple of times while simulating a broken blog.

**Comment by kirrg001** [comment]
```
.catch ((error) => {
  if (error.message.match(/failed/)) {
    return this.ui.sudo(`systemctl reset-failed ${this.systemdName}`)
      .then(() => {
        return Promise.resolve(false);
      });
   }
   .....
});
```

Something like this works nice. If you systemd process is in a "failed" state it means that Ghost has failed to start up and you have received the error already. You should be able to try again.

**Comment by acburdine** [comment]
@kirrg001 that sounds like a perfect solution - I’ll work on testing that out this weekend

**Comment by kirrg001** [comment]
@acburdine great 👍 :)

**Comment by kirrg001** [comment]
@acburdine There is another case.

If you run `ghost ls` if your systemd service is in the failed state.

**Comment by kirrg001** [comment]
I'll reopen this issue, because there are more cases. Will try to look into this tomorrow.
