### ISSUE TITLE
1.25.0 -> 1.25.2 failed

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost-CLI#766]
After running ghost update:

```
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
Running sudo command: /var/www/strefadysk/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/strefadysk/current
✖ Running database migrations
A ProcessError occurred.

Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error
Suggestion: ghost update --rollback

Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.11.3
    Ghost-CLI Version: 1.8.1
    Environment: production
    Command: 'ghost update'
```
```
Error: EACCES: permission denied, open '/var/www/strefadysk/versions/1.25.2/MigratorConfig.js'
```
this file has 640 permissions with proper ownership

**Comment by kirrg001** [comment]
Hey!

I can't reproduce this locally, nor on my production blog.

Please use the [forum](https://forum.ghost.org) for help.

If it turns out there is a bug in the CLI, we can always reopen this issue 👋

**Comment by PaszaVonPomiot** [comment]
For some reason running `ghost update` from my non-ghost user downloaded new version with wrong ownership. I think this should be handled by ghost-cli.

I fixed with:
`sudo chown ghost:ghost -R /var/www/strefadysk/versions/1.25.2/`

And manually finished installation:
`sudo -u ghost /var/www/strefadysk/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/strefadysk/current`

**Comment by acburdine** [comment]
@PaszaVonPomiot hmm - the versions folder _shouldn't_ be owned by the `ghost` user I think - it can cause issues since the `ghost` user is locked-down.

**Comment by PaszaVonPomiot** [comment]
@acburdine before I lanunched the update that failed my `ghost` user only owned `content` folder. Everything else was owned by non-ghost user that I use to run ghost-cli commands.
