### ISSUE TITLE
Protect against existing settings folder

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#776]
From https://forum.ghost.org/t/trying-to-upgrade-from-1-8-6/2318/13. Please read conversation.

I am not sure how this user came into the situation. Somehow he upgraded from an older Ghost version and Ghost-CLI complained that the `content/settings` folder exists already. I think we should just add a protection to our migration file, [see](https://github.com/TryGhost/Ghost-CLI/blob/1.8.1/lib/migrations.js).

Any help is welcome!

**Comment by vikaspotluri123** [comment]
PR incoming!

**Comment by kirrg001** [comment]
I think it doesn't really matter how the user came into the situation? Checking if the folder already exists is anyway needed (in case you create the folder manually). 

Thanks!
