### ISSUE TITLE
Possible memory leak (dev mode)

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#778]
I've installed a fresh CLI blog locally and did many post updates within 1-2minutes.
I saw that the memory went up quite fast (~200mb).

I've compared this without using the CLI and the memory was stable at around ~80mb 🤔 

Last week or so i've imported a quite large database into the CLI and the memory went over 1GB.
I've tried it without the CLI and memory was stable.

We need to investigate if this behaviour only happens in development mode.
Furthermore we should figure out what's going on.

## Steps to reproduce
- `ghost install local`
- create posts
- publish posts
- update posts
- get wild
- look at the memory usage

## Technical details

env: development
Ghost-CLI Version: latest
OS: mac os

**Comment by kirrg001** [comment]
It doesn't look like production is affected. It went up to max 140mb and jumped back to 100mb within ~1min.

**Comment by kirrg001** [comment]
> It doesn't look like production is affected. It went up to max 140mb and jumped back to 100mb within ~1min. And my test server is not super fast in general.

I am not so sure anymore, need to re-test.

**Comment by vikaspotluri123** [comment]
@kirrg001 if you give me a list of what you did, I can see if my test prod instance has similar issues. FWIW I have 3 instances running that don't get much traffic at ~ 115 MB each

**Comment by kirrg001** [comment]
@vikaspotluri123 You could see the memory difference if you import a larger database into the CLI.
If you then compare the memory usage with pure Ghost (running Ghost from the repository), you should see a big difference.

**Comment by kirrg001** [comment]
If i create a new example executable, i won't see any memory issues anymore.
That means the spawn execution is not the problem. 

```
#!/usr/bin/env node
'use strict';

const spawn = require('child_process').spawn;

const child = spawn('node', ['current/index.js'], {
    cwd: '/tmp/blog',
    stdio: [0, 1, 2, 'ipc']
});

child.on('error', (error) => {
    process.exit(1);
});

child.on('message', (message) => {
    if (message.started) {
        return;
    }

    if (message.error) {
        process.exit(1);
    }
});
```

`bin/test`

If i execute `ghost run -D` the problem occurs again. 
There must be something in the CLI, which causes the memory problem.

**Comment by kirrg001** [comment]
I've debugged some more this morning.

If i comment out [this line](https://github.com/TryGhost/Ghost-CLI/blob/1.8.1/lib/command.js#L135), the memory issue is gone 🤔

I have no idea why yet.

**Comment by acburdine** [comment]
We found what the issue was. Looks like setting `NODE_ENV=development` explicitly enables Bluebird's debug mode, which is what was using all the memory.

Closing this as any changes to fix this would need to happen in Ghost itself.
