### ISSUE TITLE
--no-prompt --force fails on unattended Ghost upgrades 1.x -> 2.x

### ISSUE THREAD

**Issue by msaladna** [TryGhost/Ghost-CLI#786]
### Summary
Presently it's impossible to perform an unattended Ghost v1.x -> 2.x upgrade using ghost-cli.

### Steps to Reproduce
` env NODE_ENV=production ghost update --local --no-prompt -f  `
✔ Checking system Node.js version
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking for available migrations
✔ Checking for latest Ghost version

Checking theme compatibility for Ghost 2.0.0

✔ Your theme is compatible.

Visit the demo post at http://ghost-testaaa.orgp/dc0038f7-f66b-4a1f-91ed-b98a4d338b52/ to see how your theme looks like in Ghost 2.0
You can also check theme compatibility at https://gscan.ghost.org

✖ Updating to a major version
✖ Update aborted. Your blog is still on 1.25.5.

**Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?**

--no-prompt should assume that Y is entered when appropriate. Running the process again without --no-prompt prompts to continue (default is Y), at which point the upgrade completes:

Checking theme compatibility for Ghost 2.0.0

✔ Your theme is compatible.

Visit the demo post at http://ghost-testaaa.orgp/dc0038f7-f66b-4a1f-91ed-b98a4d338b52/ to see how your theme looks like in Ghost 2.0
You can also check theme compatibility at https://gscan.ghost.org

? Are you sure you want to proceed with migrating to Ghost 2.0.0? Yes
✔ Updating to a major version
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Restarting Ghost
ℹ Removing old Ghost versions [skipped]

### Technical details

* OS: CentOS 7.5
* Node Version: v8.11.4
* Ghost-CLI Version: v1.9.0
* Environment: NODE_ENV=production

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [X] Tried to find help in the forum & docs
- [X] Checked for existing issues
- [-] Attached log file
- [X] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
Since this is a semver major update, the default answer is assumed to be `no, you don't want to upgrade`. Semver major updates need to be done manually since things might break; if you don't manually do it and something breaks, your publication might end up in a broken state.

**Comment by msaladna** [comment]
If it passes theme checks and there are no outstanding issues, and caveat emptor, then let the user proceed forward with an upgrade by providing a flag rather than blocking it or at least let --force mix with --no-prompt to override good judgment and automatically update.

**Comment by kirrg001** [comment]
IMO the major version jump to Ghost 2.0 might not be expected for some people. They are maybe used to run with `--no-prompt`, but suddenly it switches you to a new major version. And even if you theme is compatible, you might want to read through the changelog before migrating or look at the editor demo post. Just my opinion :)

**Comment by acburdine** [comment]
@msaladna Apologies for not responding to this issue sooner! I can't remember if we added the flag before or after this issue was reported, but there is an `--auto` flag now which I believe should fix this issue.

Going to close this as such, if the `--auto` flag doesn't fix your issue then we can reopen this 😄
