### ISSUE TITLE
Bootstrap port detection needs to be moved into the core

### ISSUE THREAD

**Issue by vikaspotluri123** [TryGhost/Ghost-CLI#787]
Currently, Process Manager extensions using the `ensureStart` method in CLI@1.8.x won't work with CLI@1.9.0 in Ghost 2.0. This is because the CLI uses socket creation instead of port polling for Ghost > 2.0.0.

The reason this is an issue is because port detection + config updates are done in the systemd extension, rather than in the core. We need to move this logic into the core, and if needed add logic to determine if a given process manager needs this functionality

**Comment by acburdine** [comment]
I think I can work this into the changes I'm making as part of #736
