### ISSUE TITLE
Ghost CLI doesn't see Ghost 2.0.1

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost-CLI#792]
### Summary

Ghost CLI doesn't see Ghost 2.0.1

By the way, everything works normally with Ghost 2.0.0 (See this build - https://travis-ci.org/firepress-org/ghostfire/jobs/418410618)

I'm sure it's a little glitch in the way version 2.0.1 was published on your side.

### Steps to Reproduce

Please see my Travis build.

### Log file error

https://travis-ci.org/firepress-org/ghostfire/jobs/418418495#L555

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: alpine
* Node Version: 8.11.4
* Ghost-CLI Version: 1.9.0
* Environment: ? alpine
* Command: warning ghost@2.0.1: The engine "cli" appears to be invalid.

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [ x] Tried to find help in the forum & docs
- [ x] Checked for existing issues
- [ x] Attached log file
- [ x] Provided technical details incl. operating system

Thank you!
Pascal

**Comment by vikaspotluri123** [comment]
The seems to be a regression w/ yarn, but it's definitely an issue.

This is the same thing as https://github.com/TryGhost/Ghost-CLI/issues/641#issuecomment-414431757 (although not a duplicate issue). Right now the solution is to stay on Ghost 2.0.0

**Comment by pascalandy** [comment]
Thanks to confirming this glitch :)
2.0.0 is running smoothly!

**Comment by pascalandy** [comment]
I confirm the bug is resolve using 2.0.2
Cheers!
