### ISSUE TITLE
Local update incorrectly reported port in use

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost-CLI#793]
### Summary

When performing a local zip update the CLI reported that the instance's port was in use when nothing was using it as far as I could see. Running `ghost start` after I got the error worked OK.

### Steps to Reproduce

1. `ghost update` with a local install

This might be intermittent, it's the first time I've run into it.

### Log file

Attached the output log, if there's another log somewhere I can attach please let me know 😄 

```
~/tmp/blog
❯ ghost update --zip ~/code/ghost/Ghost-Release/zips/Ghost-2.0.2.zip --force
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking for available migrations
✔ Checking for latest Ghost version
✔ Downloading and updating Ghost to v2.0.2
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
✔ Checking current folder permissions
✖ Validating config
✖ Restarting Ghost
✔ Removing old Ghost versions
One or more errors occurred.

1) Validating config

Error detected in the development configuration.

Message: Port '2370' is in use.
Configuration Key(s): server.port
Current Value(s): 2370

Help: Run `ghost config <key> <new value>` for each key to fix the issue.


Debug Information:
    OS: Mac OS X, v10.13.6
    Node Version: v8.10.0
    Ghost-CLI Version: 1.9.1
    Environment: development
    Command: 'ghost update --zip /Users/kevinansfield/code/ghost/Ghost-Release/zips/Ghost-2.0.2.zip --force'

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.

~/tmp/blog 25s
❯ ghost status
┌───────────────┬────────────────┬─────────┬─────────┬─────┬──────┬─────────────────┐
│ Name          │ Location       │ Version │ Status  │ URL │ Port │ Process Manager │
├───────────────┼────────────────┼─────────┼─────────┼─────┼──────┼─────────────────┤
│ ghost-local   │ ~/tmp/blog     │ 2.0.2   │ stopped │ n/a │ n/a  │ n/a             │
├───────────────┼────────────────┼─────────┼─────────┼─────┼──────┼─────────────────┤
│ ghost-local-1 │ ~/tmp/1231test │ 1.23.1  │ stopped │ n/a │ n/a  │ n/a             │
└───────────────┴────────────────┴─────────┴─────────┴─────┴──────┴─────────────────┘

~/tmp/blog
❯ lsof -nP -iTCP:2370 | grep LISTEN

~/tmp/blog
❯ sudo lsof -nP -iTCP:2370 | grep LISTEN
Password:


```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

OS: Mac OS X, v10.13.6
    Node Version: v8.10.0
    Ghost-CLI Version: 1.9.1
    Environment: development
    Command: 'ghost update --zip /Users/kevinansfield/code/ghost/Ghost-Release/zips/Ghost-2.0.2.zip --force'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by acburdine** [comment]
hmm - looking at the output it appears to be some sort of race condition.

Ghost-CLI stops the ghost instance, but I'm not sure if it waits until the process _actually_ exits. So if your ghost instance takes a minute to stop completely, you'll run into that problem.

I may look at improving the stop functionality (in the local process manager) to actually poll the process id and ensure it's stopped before moving on.

**Comment by joakimgrr** [comment]
Has there been any updates on this? I ran into the same issue with a clean AWS EC2 install yesterday. The reported port in use (by running "ghost ls") and the port configured to the nginx config are both X while the actual port that the node process is using is X+1. I can provide detailed info about the versions later.

**Comment by sampumon** [comment]
I have this happening also most every time I do a normal `ghost update`. Running `ghost start` right after works normally.

```
Debug Information:
    OS: Mac OS X, v10.14.6
    Node Version: v10.16.1
    Ghost-CLI Version: 1.12.0
    Environment: development
    Command: 'ghost update'
```

**Comment by kevinansfield** [comment]
I haven't run into this for a long time so I'm closing to clean up the issue list. Can be re-opened if it's a still a known issue or if it pops up again.
