### ISSUE TITLE
Add Node 10 support

### ISSUE THREAD

**Issue by glococo** [TryGhost/Ghost-CLI#799]
### Summary
I failed to install Ghost with Node 10

Supported: ^6.9.0 || ^8.9.0
Installed: 10.9.0

[ Ubuntu 18, node 10.9.0 ]

**Comment by acburdine** [comment]
@glococo Ghost (and therefore Ghost-CLI) only supports LTS versions of Node. See here: https://docs.ghost.org/docs/supported-node-versions
