### ISSUE TITLE
Introduce `--auto` flag for a simpler install

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#806]
We've been doing some user testing, and found that in certain contexts, the default behaviour of the CLI is asking the user to make too many decisions. The `--no-prompt` behaviour is better in most cases - it just does the sensible thing - but then you aren't prompted even for the most fundamental details.

The clear use case here is the Digital Ocean one-click installer. They configure all the hard stuff - mysql settings etc, but the _user_ needs to enter their desired domain and an email address for SSL.

We (@JohnONolan & me) have talked through the various subcommands of the install command and I think I have a solution that is straightforward, works for each individual subcommand and provides us with a bit more power/flexibility in the CLI to customise what a user sees.

The idea is to introduce a new `--auto` flag.

`ghost config --auto`

In `ghost config` the `--auto` flag switches to _only_ prompt if there isn't a non-default value already set. E.g. it should be possible to configure all the mysql details, and then call `ghost config` and only be prompted for a url.

⚠️Aside: I also think that `ghost config --url` should _only_ prompt for URL, rather than doing all prompts. Maybe this should be a separate issue, but I think there is some shared reworking of `ghost config` needed to solve both?

`ghost setup --auto`

For `ghost setup` the `--auto` flag switches to assuming that the user wants the standard setup, don't prompt for mysql user, nginx, ssl etc. This is almost identical to the `--no-prompt` behaviour of `ghost setup` (which is **amazing**). The only difference is that the prompt for the SSL email address needs to happen.

The `--auto` flag should also set `--start` to true.

⚠️Aside: Not sure if I'm misunderstanding, but there seems to be a weird flow whereby you are prompted if you want to create the `ghost` mysql user, but then the user is not root and so nothing actually happens?

`ghost install --auto --db=mysql ...`

For `ghost install` the `--auto` flag doesn't have any specific behaviour - it passes the flag to the subcommands.

With all of these changes in place, it is now possible for a tool like the one-click installer to generate an `install` command that is pre-filled with all the mysql config e.g. `ghost install --auto --db=mysql --dbhost=localhost --dbuser=ghost --dbpass=xxx --dbname=ghost_prod`, and the resulting behaviour will be that the user is only prompted for their url and their email address - two questions that most people are able to answer.

⚠️Aside: I _feel_ like there might be cause for running `ghost config` before `ghost install` 🤔I realise this is super crazy compared to the way the CLI is designed, just throwing it out there as food for thought, as it would be nice if the one-click installer was able to call `ghost config` with the mysql config, and then `ghost install --auto` would always `Just Work™️`.

**Comment by ErisDS** [comment]
Is there any part of this left to do? It's working well so far!

**Comment by acburdine** [comment]
Was leaving it open for the couple of asides you'd mentioned, but I can make a note to take care of one or both of them as part of the coming setup command refactor.
