### ISSUE TITLE
ghost update error

### ISSUE THREAD

**Issue by QingShui23** [TryGhost/Ghost-CLI#808]
run "ghost update" 

--------

npm ERR! Linux 4.4.0-91-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ghost-cli@latest"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/ghost-cli/node_modules/@sindresorhus/is
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access

npm ERR! enoent ENOENT: no such file or directory, access '/usr/lib/node_modules/ghost-cli/node_modules/@sindresorhus/is'
npm ERR! enoent ENOENT: no such file or directory, access '/usr/lib/node_modules/ghost-cli/node_modules/@sindresorhus/is'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/npm-debug.log

**Comment by ErisDS** [comment]
Please use the [forum](https://forum.ghost.org) for support. Bug reports should fill out the template.
