### ISSUE TITLE
Misleading error message on SSL configuration

### ISSUE THREAD

**Issue by FizzBuzz791** [TryGhost/Ghost-CLI#832]
Letsencrypt/acme.sh returns a timeout error, but Ghost-CLI "converts" that to a "Your domain name is not pointing to the correct IP address of your server". This is highly misleading as I can see that the A record is correct via dnschecker.org and a ping request to the domain name will resolve the IP correctly.

After some manual tests of the letsencrypt script, I figured out that the default firewall settings for AWS EC2 are to only allow SSH. This is why letsencrypt wasn't able to get anywhere.

Steps to reproduce:
1. Spin up a brand new server, I was using Ubuntu 18.04 LTS on a t2.micro with default settings, but any EC2 server should suffice.
2. Ensure the firewall is only configure with an SSH whitelist (again, this is default, so it should be fine).
3. Try to run through the ghost installation, get stuck on the SSH step.
4. Open HTTP and HTTPS via AWS console for the EC2 instance (must be 0.0.0.0/0 for the IP whitelist).
5. Try ghost installation again, works now.

Desired result:
Better error message. This was not a DNS resolution issue and simply passing through the letencrypt error message would have been far less misleading than using the current one.

**Comment by FizzBuzz791** [comment]
Adding a comment to keep this open as it's linked to an epic.

**Comment by ErisDS** [comment]
I’ve closed the epic, it too is stale and no longer going to be worked on.

If you’d like to work on this let us know, otherwise this issue is stale and can be closed.

**Comment by FizzBuzz791** [comment]
Ah OK, no worries, happy to close.
