### ISSUE TITLE
Migrate from minor Ghost version to minor Ghost version

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#839]
I'd like to raise this issue to reconsider making big jumps when updating the blog to the latest Ghost version.

## Problem

The Ghost team writes migration scripts with a specific code base.
If you migrate to the latest version of Ghost, and knex-migrator has to execute migrations from a previous Ghost version, these scripts will get executed in the new code base context. This can trouble hard e.g. take a look at [this bug report.](https://github.com/TryGhost/Ghost/issues/9983)

## Solution

Ghost-CLI could migrate to the next minor version, executes migrations and then looks for the next available minor version...and so on... There is no extra step the user has to take, it will just take a little longer. Ghost only adds migration scripts in minor or major Ghost versions.

**Comment by kirrg001** [comment]
@vikaspotluri123 ❤️

**Comment by kirrg001** [comment]
I think both is important - major + minor.
e.g. if minor 2.X manipulates posts, but the next minor changes something in the post model layer, minor 2.X might fail.

**Comment by vikaspotluri123** [comment]
So if I was migrating from 1.latest to 2.30, the CLI would install + migrate

2.0
2.1
2.2
2.3
2.4
...
2.30?

**Comment by kirrg001** [comment]
yes i think so 😁in worst case, you have to wait a little longer?
Not sure right now how else to solve this problem?

**Comment by vikaspotluri123** [comment]
Makes sense, just wanted to check 😄 

Do you see any issue with copying the `node_modules` from the previous version before running yarn? That should hopefully reduce the update time (for both generic updates as well as updates to older instances)

**Comment by kirrg001** [comment]
I think copying the node_modules should work. It's still the same OS and very similar to locally e.g. you pull master and run `yarn`?

**Comment by vikaspotluri123** [comment]
Yeah, that's what I was thinking 👍

**Comment by vikaspotluri123** [comment]
Here's the logic I'm working on implementing:

latest = current v1 (and v2 if necessary) version
current = installed + active version of Ghost
steps = what versions the CLI needs to install
to = user specified by user (e.g. `ghost update 1.2.3` => to = 1.2.3)
v1 = v1 flag was specified (`ghost update --v1`)

```yml
latest: 1.25.17
current: 1.22.3
steps: 1.23.0, 1.24.0, 1.25.0, 1.25.17

latest: 1.25.17, 2.1.3
current: 1.23.0
steps: 1.23.0, 1.24.0, 1.25.0, 1.25.17

latest: 1.25.17
current: null
to: null
steps: 1.25.17

latest: 1.25.17
current: null
to: 1.8.3
steps: 1.8.3

latest: 1.25.17
current: 1.2.3
to: 1.5.0
steps: 1.3.0, 1.4.0, 1.5.0

// Note: The steps for this case are only to maintain current behavior.
// When CLI is updated for 3.0, this logic can be updated with the 3.0steps
latest: 1.25.17, 2.3.4
current: 1.24.0
to: null
steps: error (you need to be on 1.latest to migrate to 2.x)
3.0steps: 1.24.0, 1.25.0, 1.25.17, [here be dragons], 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.4

latest: 1.25.17
to: 0.11.0
current: null
steps: error

latest: 1.25.17, 2.0.3
v1: true
current: 1.23.0
steps: 1.24.0, 1.25.0, 1.25.8

latest: 1.25.17
to: 1.25.30
steps: error

latest: 1.25.17
current: 1.25.8
steps: error

latest: 1.25.17, 2.3.4
current: 1.25.8
v1: true
steps: error

latest: 2.2.3
current: 2.0.0
steps: 2.1.0, 2.2.0, 2.2.3```

**Comment by vikaspotluri123** [comment]
> The same problem exists in Ruby on Rails and other db migration tools if you make use of the core models in migrations. In RoR it's best practice to create local model objects extending from the base model so that there's no chance you'll use methods that don't exist at the time the migration is run https://guides.rubyonrails.org/v3.2/migrations.html#using-models-in-your-migrations<br/>
> Is that something that's possible with knex-migrator/bookshelf? 

/cc @kevinansfield

**Comment by kirrg001** [comment]
**The disadvantage of this approach:**

We can no longer fix or revert an older migration file. We had the case a couple of weeks ago where we reverted a full migration script.

**Comment by acburdine** [comment]
Closing this - Ghost has separated migrations from the Bookshelf ORM codebase, which lessens/removes the need for this approach.

We can always reopen if at some point in the future we want to implement this.
