### ISSUE TITLE
Ghost-CLI creates nginx conf file with root pointing to non-existing directory.

### ISSUE THREAD

**Issue by flip111** [TryGhost/Ghost-CLI#843]
During installation of ghost:

```
[07:24:41] Setting up Nginx [started]
✔ Creating nginx config file at /var/www/ghost/system/files/mydomain.com.conf
+ sudo ln -sf /var/www/ghost/system/files/mydomain.com.conf /etc/nginx/sites-available/mydomain.com.conf
+ sudo ln -sf /etc/nginx/sites-available/mydomain.com.conf /etc/nginx/sites-enabled/mydomain.com.conf
+ sudo nginx -s reload
[07:24:41] Setting up Nginx [completed]
```

In the nginx conf file:
```
root /var/www/ghost/system/nginx-root;
```

This directory does not exist and there are no further instructions in either the conf file or during installation what to do with this.

**Comment by vikaspotluri123** [comment]
It's used by acme.sh to verify your domain which in turn is used to generate or renew an SSL certificate for your domain. Other requests get proxied to ghost

**Comment by MaskyS** [comment]
@flip111, https://github.com/Neilpang/acme.sh
