### ISSUE TITLE
Sharp doesn't find the libraries

### ISSUE THREAD

**Issue by MaluNoPeleke** [TryGhost/Ghost-CLI#844]
I am using Ghost 2.2.2 on a CentOS 6 system with node.js 8.12.0 and I have to manually update Ghost because my hoster doesn't the allow the usage of the cli.
Everything works except of the (optional) sharp installation.
I have manually installed libvips 8.7RC3 and added LD_LIBRARY_PATH (export LD_LIBRARY_PATH=/home/peleke/lib:$LD_LIBRARY_PATH) to that but I still get this error message:

```
> sharp@0.20.7 install /home/peleke/node_apps/ghost/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp Use with glibc version 2.12 requires manual installation of libvips >= 8.6.1
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install
make: Entering directory `/home/peleke/node_apps/ghost/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:22: fatal error: vips/vips8: No such file or directory
compilation terminated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory `/home/peleke/node_apps/ghost/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/package/host/localhost/nodejs-8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-696.18.7.el6.x86_64
gyp ERR! command "/package/host/localhost/nodejs-8.12.0/bin/node" "/package/host/localhost/nodejs-8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/peleke/node_apps/ghost/node_modules/sharp
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.20.7 (node_modules/sharp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.20.7 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by allouis** [comment]
The maintainer of sharp recommends upgrading to CentOS 7 if possible, as there are precompiled binaries available. See this relevant issue: https://github.com/lovell/sharp/issues/1300.

**Comment by MaluNoPeleke** [comment]
That is not an option for me.

**Comment by acburdine** [comment]
@MaluNoPeleke I'm not entirely sure what you want us to do 😅 

> because my hoster doesn't the allow the usage of the cli.

Since you're not using Ghost-CLI, there's not much we can really do here to fix the issue, short of dropping the dependency on sharp in Ghost itself, which I doubt is going to happen.

Going to close this issue as there's not anything we can do really. If you continue to have issues with sharp please open an issue there.

**Comment by ErisDS** [comment]
Let me also just point this out:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY

It's a warning, not an error. Without sharp installed Ghost falls back gracefully to its old behaviour of not optimising images. That's it. Ghost will still function in every other way.

Given that you're aware that you are using an OS that's clearly not recommended for use with Ghost, you should be expecting that the latest and greatest features won't always work for you or that you may need to work harder to get them to work.
