### ISSUE TITLE
Relax file permission requirements

### ISSUE THREAD

**Issue by Leandros** [TryGhost/Ghost-CLI#847]
### Summary

`ghost doctor` requires very rigorous file permissions, which are super annoying to comply every single time I want to use it. 
For example, while developing on a theme, any executable file (like a shell script) can not be kept in the repo, otherwise `ghost doctor` complains.
My specific use case involves keeping my theme inside a git repo, but `ghost-cli` complains about that:

```
Message: Your installation folder contains some directories or files with incorrect permissions:
- ./content/themes/steam-master/.git/objects/pack/pack-999553d2fca55687f0749dd2c0cbf84992fb1603.pack
- ./content/themes/steam-master/.git/objects/pack/pack-999553d2fca55687f0749dd2c0cbf84992fb1603.idx
- ./content/themes/steam-master/.git/hooks/post-update.sample
- ./content/themes/steam-master/.git/hooks/pre-rebase.sample
- ./content/themes/steam-master/.git/hooks/commit-msg.sample
- ./content/themes/steam-master/.git/hooks/pre-applypatch.sample
- ./content/themes/steam-master/.git/hooks/update.sample
- ./content/themes/steam-master/.git/hooks/pre-commit.sample
- ./content/themes/steam-master/.git/hooks/prepare-commit-msg.sample
- ./content/themes/steam-master/.git/hooks/applypatch-msg.sample
- ./content/themes/steam-master/.git/hooks/pre-receive.sample
- ./content/themes/steam-master/.git/hooks/pre-push.sample
- ./content/themes/steam-master/assets/css/generate.sh
```

### Steps to Reproduce

Change literally any file inside the ghost folder from 644 to anything else.

### Technical details

    OS: Debian, v9.5
    Node Version: v8.12.0
    Ghost-CLI Version: 1.9.6
    Environment: production
    Command: 'ghost doctor'

**Comment by vikaspotluri123** [comment]
Hey! This seems like a duplicate of #745 🙂

**Comment by Leandros** [comment]
Yes, looks like it. I was looking for a similar ticket, but couldn't find anything. Thanks, will close this one.
