### ISSUE TITLE
`ghost update --dry-run`

### ISSUE THREAD

**Issue by Leandros** [TryGhost/Ghost-CLI#848]
### Summary

I don't feel like running some random commands on my servers, without knowing what they execute exactly. Especially if they modify systemd.
It would be great if a `--dry-run` flag could be added which prints all the commands which will be executed.

**Comment by vikaspotluri123** [comment]
`ghost update` doesn't modify systemd per say, it only updates the state of your instance using systemctl (while the update is happening, your instance is shut down, and once the update is complete it's restarted with the new version).

Ghost update is mostly just a couple of `yarn` commands to get the latest versions of ghost and install the latest version if there is one available. Other than that it runs some cleanup after your instance is restarted to limit the number of installed versions you have

In case you weren't aware, every sudo command run by ghost is logged to the terminal like `+ {command}` in grey (if your terminal supports it)

**Comment by acburdine** [comment]
@Leandros Ghost-CLI is a mix of programmatic file access as well as actual "commands" that are run, which makes it rather difficult to generate, and then output, a list of commands to print.

As @vikaspotluri123 said, you can see all of the "sudo" commands that are run as they're being run. Additionally, you can pass the --verbose flag to see a lot more output from the CLI to tell you what it's running. The verbose flag will let you view (and potentially edit) any files that the CLI writes to protected directories (i.e. systemd or nginx config files) which should, I think, solve most of what you're wanting.
