### ISSUE TITLE
Check nginx install without dpkg

### ISSUE THREAD

**Issue by enguerran** [TryGhost/Ghost-CLI#853]
### Summary

Regarding https://github.com/TryGhost/Ghost-CLI/blob/master/extensions/nginx/index.js#L282
```js
    isSupported() {
        try {
            execa.shellSync('dpkg -l | grep nginx', {stdio: 'ignore'});
            return true;
        } catch (e) {
            return false;
        }
    }
```

We check Nginx by using a third-party command called `dpkg` that is available only on Debian-based distributions.
I use Arch linux and I have nginx installed. I can check it with 

```js
    isSupported() {
        try {
            execa.shellSync('nginx -v', {stdio: 'ignore'});
            return true;
        } catch (e) {
            return false;
        }
    }
```

Then the command `ghost setup nginx` can do everything it needs:

```
/v/w/ghost> ghost setup nginx
✔ Creating nginx config file at /var/www/ghost/system/files/servername.conf
+ sudo ln -sf /var/www/ghost/system/files/servername.conf /etc/nginx/sites-available/servername.conf
+ sudo ln -sf /etc/nginx/sites-available/servername.conf /etc/nginx/sites-enabled/servername.conf
+ sudo nginx -s reload
✔ Setting up Nginx
```

Can we not consider using `nginx -v` to check for the presence of nginx?

**Comment by enguerran** [comment]
After an update, I find this error on my Arch Linux server (which doesn't have dpkg -l to search if nginx is installed).

I thought that maybe one solution was to ask the user if we skip or not after `isSupported` returned `false`. Because in the end, in the following, we consider that `nginx` is in the `PATH` or provided via the environment variable.
https://github.com/TryGhost/Ghost-CLI/blob/master/extensions/nginx/index.js#L275

The solution may be something like this
https://github.com/TryGhost/Ghost-CLI/blob/94389d559700854fb4c1502643d76eafe48a61f2/lib/commands/doctor/checks/system-stack.js#L43-L62

I can write the code needed using inquirer if the proposotion is accepted.

**Comment by acburdine** [comment]
@enguerran I'm working on some improvements to these checks - should have something out soon.

**Comment by acburdine** [comment]
@enguerran I've refactored the stack check to use [systeminformation's](https://systeminformation.io) `services` utility to check if `nginx` is installed by iterating over the list of installed services, rather than distro-specific command like `dpkg`.

**Comment by enguerran** [comment]
Thank you very much @acburdine for following up on this modification request which is clearly not proprietary but which I am very pleased with!

**Comment by amo13** [comment]
Unfortunately, I am still having this issue on Archlinux with ghost-cli 1.17.3. Did anything in the detection mechanism change again?
