### ISSUE TITLE
Check for available update

### ISSUE THREAD

**Issue by aeonsablaze** [TryGhost/Ghost-CLI#876]
I would like to request the ability to check for a new version of ghost via ghost-cli without actually running the update. This could either be a separate command (i.e. 'ghost check-update') or a flag on the existing one (i.e. 'ghost update --check').

**Comment by acburdine** [comment]
@aeonsablaze that does sound like a good idea, will do some thinking here soon about what the command should be called but it should be pretty easy to implement.

**Comment by aeonsablaze** [comment]
Any update on when this feature might be available?

**Comment by acburdine** [comment]
Need to make a release here in in the next couple of days, will try and get this in as well 😄

**Comment by acburdine** [comment]
@aeonsablaze this was released in Ghost-CLI 1.10.1 - let me know if you find any issues with it 😄
