### ISSUE TITLE
Issue with Migration

### ISSUE THREAD

**Issue by PFre888437** [TryGhost/Ghost-CLI#877]
Greetings,
After trying to update ghost from 2.12 to 2.13 we are getting a failure with the database migration
Before upgrading we checked the migration lock and we noticed it was unlocked after trying to update it will be stuck restarting because of some failure during the migration process.
Our database is stored on google's Cloud SQL and unfortunately we have a very large database.
We noticed from googles end that before it aborts the connection it tries to load all the posts.
We think there may be a timeout perhaps that might be breaking the migration before it has completed thus leaving the migration lock on. 
Sorry for the bother and thanks for any help!

### Steps to Reproduce

1. ghost update

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Log file

Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.14.0
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost update 2.13.0'
Message: Migration lock was never released or currently a migration is running.
Help: If you are sure no migration is running, check your data and if your database is in a broken state, you could run `knex-migrator rollback`.
Suggestion: journalctl -u ghost_localhost -n 50
Stack: Error: Migration lock was never released or currently a migration is running.
    at Server.server.close (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:38:28)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1664:8)
    at _combinedTickCallback (internal/process/next_tick.js:136:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x ] Tried to find help in the forum & docs
- [x ] Checked for existing issues
- [ x] Attached log file
- [ x] Provided technical details incl. operating system

**Comment by kirrg001** [comment]
Hey @PFre888437   👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.
