### ISSUE TITLE
`version.match is not a function` upon ghost update --version

### ISSUE THREAD

**Issue by deisner** [TryGhost/Ghost-CLI#883]
### Summary

When I run `ghost update --version`, I get an error: `An error occurred.
Message: 'version.match is not a function'`. This happened both before and after upgrading Ghost to version 2.18.1.

### Steps to Reproduce

1. Login as `ghost-mgr` user.
2. `cd` to Ghost installation (`/var/www/ghost`).
3. Run `ghost update --version`

Here is a screenshot of the result (I've obscured my hostname):

![image](https://user-images.githubusercontent.com/742277/54468237-f5eea100-4760-11e9-8aaa-16bda1b7b26a.png)

### Log file

All errors end with "Additional log info available in: [filepath]".

Use the command `cat [filepath]` to read the log, then copy & paste the contents here:

```
$ cat ~/.ghost/logs/ghost-cli-debug-2019-03-16T00_24_13_439Z.log
Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.10.0
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost update --version'
An error occurred.
Message: 'version.match is not a function'

Stack: TypeError: version.match is not a function
    at resolveVersion (/usr/local/lib/node_modules/ghost-cli/lib/utils/resolve-version.js:20:28)
    at zip (/usr/local/lib/node_modules/ghost-cli/lib/commands/update.js:205:54)
    at UpdateCommand.version (/usr/local/lib/node_modules/ghost-cli/lib/commands/update.js:207:16)
    at ui.run (/usr/local/lib/node_modules/ghost-cli/lib/commands/update.js:123:46)
    at fn (/usr/local/lib/node_modules/ghost-cli/lib/ui/index.js:86:74)
    at UI.run (/usr/local/lib/node_modules/ghost-cli/lib/ui/index.js:95:16)
    at runCommand.then.then (/usr/local/lib/node_modules/ghost-cli/lib/commands/update.js:123:31)
    at <anonymous>
$
```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Ubuntu, v18.04
* Node Version: v8.10.0
* Ghost-CLI Version: 1.9.9
* Environment: production
* Command: 'ghost update --version'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by acburdine** [comment]
@deisner the reason this is occurring is due to how Ghost's argument parser is currently configured. `ghost update` is technically configured as `ghost update [version]` to allow you to specify a specific version to update your blog to. When you run `ghost update --version`, yargs (the args parser) treats it as a boolean value, instead of as a string, hence the `match is not a function` error.

What were you expecting the behavior to be when you ran `ghost update --version`?

**Comment by deisner** [comment]
Sorry for the delay, @acburdine. I was expecting to see the command display the version of Ghost I was running, as per https://docs.ghost.org/api/ghost-cli/update/:

> ![image](https://user-images.githubusercontent.com/742277/55085139-86d84d00-507c-11e9-9d44-8739bc5468f6.png)

**Comment by acburdine** [comment]
The docs that caused confusion (and thus this issue) have been updated, so I'm going to close this issue as it's really a limitation of the underlying args parser.

If it continues to be a source of confusion, we can look at reopening this/coming up with a more involved solution 😄
