### ISSUE TITLE
Ghost CLI not supporting node 10.15.3

### ISSUE THREAD

**Issue by dyyce** [TryGhost/Ghost-CLI#886]
Hi there,

I am trying to install ghost using
`ghost install local`

But I seem to get the following error everytime, even though I have the supported version installed.

```bash
You are running an outdated version of Ghost-CLI.
It is recommended that you upgrade before continuing.
Run `npm install -g ghost-cli@latest` to upgrade.

✖ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking memory availability
One or more errors occurred.

1) Checking system Node.js version

Message: The version of Node.js you are using is not supported.
Supported: ^6.9.0 || ^8.9.0
Installed: 10.15.3
See https://docs.ghost.org/v1/docs/supported-node-versions for more information

Debug Information:
    OS: Mac OS X, v10.14.4
    Node Version: v10.15.3
    Ghost-CLI Version: 1.8.1
    Environment: development
    Command: 'ghost install local'

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

Then I tried to switch to node `8.9.0` and ran `ghost install local`, but no success:

```bash
You are running an outdated version of Ghost-CLI.
It is recommended that you upgrade before continuing.
Run `npm install -g ghost-cli@latest` to upgrade.

✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v2.19.0
A SystemError occurred.

Message: Ghost v2.19.0 is not compatible with this version of the CLI.

Debug Information:
    OS: Mac OS X, v10.14.4
    Node Version: v8.9.0
    Ghost-CLI Version: 1.8.1
    Environment: development
    Command: 'ghost install local'

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

any idea what I am missing?

**Comment by dyyce** [comment]
OK I have found a way to make it work with node version `8.10.0`. But only with trial and error.

**Comment by kevinansfield** [comment]
@dyyce did you see this message at the top of your log output?

> You are running an outdated version of Ghost-CLI.
> It is recommended that you upgrade before continuing.

You should upgrade your global version of `ghost-cli` package, it has support for node 10

**Comment by dyyce** [comment]
> @dyyce did you see this message at the top of your log output?
> 
> > You are running an outdated version of Ghost-CLI.
> > It is recommended that you upgrade before continuing.

Yes it does show this message.
But it doesn't change anything after I run
`npm install -g ghost-cli@latest`

**Comment by kevinansfield** [comment]
If it's not changing anything then you likely have an issue with your node/nvm setup. Head by [our forum](https://forum.ghost.org) if you want any help resolving it
