### ISSUE TITLE
running ghost install with --no-prompt should not fail using a remote MySQL instance

### ISSUE THREAD

**Issue by devster31** [TryGhost/Ghost-CLI#891]
### Summary

The issue is related to #410. `--no-prompt` is usually used in automated installs, in which case it fails by default if a MySQL instance isn't present locally. I believe there should be either a specific flag to allow this behaviour or it should be allowed by default when using `--no-prompt`

### Steps to Reproduce

1. `ghost install --no-prompt`

### Log file

```sh
$ ghost install 2.20.0 --no-prompt --no-stack --no-setup --ip 0.0.0.0
✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking current folder permissions
ℹ Checking operating system compatibility [skipped]
Local MySQL install not found. You can ignore this if you are using a remote MySQL host.
Alternatively you could:
a) install MySQL locally
b) run `ghost install --db=sqlite3` to use sqlite
c) run `ghost install local` to get a development install using sqlite3.
✖ Checking for a MySQL installation
✔ Checking memory availability
One or more errors occurred.

1) Checking for a MySQL installation

Message: MySQL check failed.

Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.10.0
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost install 2.20.0 --no-prompt --no-stack --no-setup --ip 0.0.0.0'

Try running ghost doctor to check your system for known issues.

You can always refer to https://docs.ghost.org/api/ghost-cli/ for troubleshooting.
```

## Proposal
change this function
https://github.com/TryGhost/Ghost-CLI/blob/f06ca1a67e49a4d5a3e18cf95de42c1c436361b0/lib/commands/doctor/checks/mysql.js#L9-L35
like so:
```js
function mysqlCheck(ctx, task) {
    // On ubuntu, mysqld is in `/usr/sbin` but it's not automatically in the PATH of non-root users
    // So, we modify the path env var to make things work
    const options = ctx.system.platform.linux ? {env: {PATH: `/usr/sbin:${process.env.PATH}`}} : {};

    // default to true if --auto is used
    const def = ctx.argv.auto ? true : false

    // Technically this doesn't work on windows, but there's
    // not an easy way to do that anyways so ¯\_(ツ)_/¯
    return execa.shell('which mysqld', options).catch(() => {
        ctx.ui.log(`${chalk.yellow(`Local MySQL install not found. You can ignore this if you are using a remote MySQL host.
Alternatively you could:`)}
${chalk.blue('a)')} install MySQL locally
${chalk.blue('b)')} run ${chalk.cyan('`ghost install --db=sqlite3`')} to use sqlite
${chalk.blue('c)')} run ${chalk.cyan('`ghost install local`')} to get a development install using sqlite3.`);

        // uses default true value
        return ctx.ui.confirm(chalk.blue('Continue anyway?'), def).then((confirmed) => {
            if (confirmed) {
                task.skip('MySQL check skipped');
                return Promise.resolve();
            }

            return Promise.reject(new errors.SystemError({
                message: 'MySQL check failed.',
                task: taskTitle
            }));
        });
    });
}
```

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
Hey @devster31 👋 

> I believe there should be either a specific flag to allow this behaviour

What specific behavior are you referring to?

This error can be avoided by specifying the database-related options as outlined in the [docs](https://docs.ghost.org/api/ghost-cli/config/#options) - is there a reason you haven't specified those options via flags? If you set the remote host via flags, your issue won't occur 😉

**Comment by devster31** [comment]
My example is a docker image. I'd like a MySQL instance to run in a container and link it to a ghost container, which means the MySQL instance doesn't exist when installing `ghost` and will have variable parameters. The https://github.com/docker-library/ghost image forces `--db=sqlite3` so I'm slightly modifying it.
As I failed, repeatedly, to build using `grunt prod` as I ran out of memory and `ghost-cli` is the recommended way to deploy that's what I'm using.
The behaviour I'm referring to is the ability to skip the check without a prompt even when other db parameters aren't specified.

**Comment by acburdine** [comment]
@devster31 even though the official docker image specifies `--db=sqlite3`, you should be able to use environment variables to configure the docker image to use a remote mysql host.

Going to close this for now, as that check failure is intentional. If environment variables aren't solving your use-case specifically, then we can potentially re-open this and consider additional options.
