### ISSUE TITLE
ghost install local error

### ISSUE THREAD

**Issue by galibhasanov** [TryGhost/Ghost-CLI#921]
![dsBuffer bmp](https://user-images.githubusercontent.com/45079942/57020753-5cf5e580-6c3b-11e9-9b3f-60ed2f681f36.png)

**Comment by allouis** [comment]
Hey! This is a bug in the latest Ghost, not the cli. It's been fixed here: https://github.com/TryGhost/Ghost/pull/10722 and will be released next week :) Closing this now - sorry for the inconvenience
