### ISSUE TITLE
[nvm] Unable to upgrade to a newer version than 2.21.0

### ISSUE THREAD

**Issue by mockee** [TryGhost/Ghost-CLI#950]
### Summary

Learned by Ghost changelog, v2.21.1 added `members-theme-bindings.js`. The error that cannot be upgraded seems to be related to it. I tried to handle the file permissions issue but it didn't work. Reinstalling 2.21.0 in a new environment is fine, but subsequent versions will report the same error.

### Steps to Reproduce

- `ghost update`

### Log file

```
--------------- stdout ---------------
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ cpy node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


--------------- stderr ---------------
Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@2.23.4: The engine "cli" appears to be invalid.
warning "@tryghost/members-auth-pages > react-stripe-elements@2.0.3" has unmet peer dependency "react@^15.5.4 || ^16.0.0-0".
warning "@tryghost/members-auth-pages > react-stripe-elements@2.0.3" has unmet peer dependency "react-dom@^15.5.4 || ^16.0.0-0".
Cannot copy from `/versions/2.23.4/node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js` to `/versions/2.23.4/core/server/public/members-theme-bindings.js`: Cannot write to `/versions/2.23.4/core/server/public/members-theme-bindi
ngs.js`: EACCES: permission denied, open '/versions/2.23.4/core/server/public/members-theme-bindings.js'
error Command failed with exit code 1.

yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ cpy node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1

warning ghost@2.23.4: The engine "cli" appears to be invalid.
warning "@tryghost/members-auth-pages > react-stripe-elements@2.0.3" has unmet peer dependency "react@^15.5.4 || ^16.0.0-0".
warning "@tryghost/members-auth-pages > react-stripe-elements@2.0.3" has unmet peer dependency "react-dom@^15.5.4 || ^16.0.0-0".
Cannot copy from `/versions/2.23.4/node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js` to `/versions/2.23.4/core/server/public/members-theme-bindings.js`: Cannot write to `/versions/2.23.4/core/server/public/members-theme-bindi
ngs.js`: EACCES: permission denied, open '/versions/2.23.4/core/server/public/members-theme-bindings.js'
error Command failed with exit code 1.
```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Ubuntu, v16.04
* Node Version: v10.16.0
* Ghost-CLI Version: 1.11.0
* Environment: production
* Command: 'ghost update'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by surfer77** [comment]
getting the same on a new install on a DO ubuntu droplet

**Comment by Luen** [comment]
Same error.

**Comment by allouis** [comment]
@mockee Which user owns the directort you're installing into, and which user are you runnign the command as? Looks like it's a permissions issue, which is strange because it managed to install other files into that location.

@surfer77 That doesn't look like the same error, it looks like a warning you can safely ignore

@Luen That is a different error, which is being tracked here: https://github.com/TryGhost/Ghost/issues/10813

**Comment by mockee** [comment]
@allouis both the directory owner and command executor are `mockee`.

**Comment by mockee** [comment]
@allouis Probably because of `nvm`
```
» which ghost
/home/mockee/.nvm/versions/node/v10.16.0/bin/ghost

» npm root -g
/home/mockee/.nvm/versions/node/v10.16.0/lib/node_modules
```

> If nvm is installed locally in /root or /home then you’ll run into permission problems. Ghost requires a system wide installation. We recommend uninstalling nvm to avoid permission problems. A symlink from the local installation to usr/bin/node will not work.

But I need `nvm` at the moment, is there any other way to install the latest Ghost?

**Comment by mockee** [comment]
Successfully upgraded to v2.31.1 via `ghost update`.
