### ISSUE TITLE
node 8.9 unsupported, but not caught by version check.

### ISSUE THREAD

**Issue by dhrp** [TryGhost/Ghost-CLI#952]
### Issue Summary

Ghost install checks the node version as first step; Node 8.9 is marked valid, but installation then still fails because of incompatible version.

### To Reproduce

1. switch to node 8.9.x
2. run ghost install local
3. notice `✔ Checking system Node.js version` checks out ok
4. installation fails with `Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@2.23.4: The engine "cli" appears to be invalid. error eslint@5.12.1: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "8.9.4"
error Found incompatible module.`

I'm left with a partially installed folder.

Full output below.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

*Expected behavior:* Step 1 says I am on an incompatible version of node.

### Technical details:

*    OS: Mac OS X, v10.14.5
*    Node Version: v8.9.4
*    Ghost-CLI Version: 1.11.0
*    Environment: development
*   Command: 'ghost install local'

```
Oatcake:ghosttest thatcher$ ghost install local
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v2.23.4
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@2.23.4: The engine "cli" appears to be invalid.
error eslint@5.12.1: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "8.9.4"
error Found incompatible module.

yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1


Debug Information:
    OS: Mac OS X, v10.14.5
    Node Version: v8.9.4
    Ghost-CLI Version: 1.11.0
    Environment: development
    Command: 'ghost install local'
```

**Comment by acburdine** [comment]
@dhrp we bumped the minimum supported node version to 8.10, which fixes this issue for now. Theoretically this _shouldn't_ have happened since eslint is a dev dependency, so we'll continue to look into the underlying cause.
