### ISSUE TITLE
Ghost CLI and docker

### ISSUE THREAD

**Issue by Dragas** [TryGhost/Ghost-CLI#961]
Yo! I'm trying to run ghost in docker container, but the CLI responds with "cant run commands as root user". How come?

Steps to reproduce:

1. Build docker image with the following dockerfile as `ghost-cms:0.1` tag.
```
FROM node:10.16.0-jessie

RUN ["npm", "install", "ghost-cli", "-g"]

EXPOSE 80

VOLUME "/project"

WORKDIR "/project"
```

2. Run the following command
```
docker run -it ghost-cms:0.1 ghost install local
```

 Logs:

```
You can't run commands as the 'root' user.
Switch to your regular user, or create a new user with regular account privileges and use this user to run 'ghost install'.
For more information, see https://docs.ghost.org/install/ubuntu/#create-a-new-user-.
```

* OS: Macos 10.13.6
* Node Version: 10.16.0-jessie
* Ghost-CLI Version: 1.11.0
* Environment: Docker
* Command: install local

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by ErisDS** [comment]
Containerisation technologies like docker and system management tools like Ghost-CLI are pretty much fundamentally incompatible.

With docker you run each piece of the stack in a different, transient container. You configure volumes to represent all the persistent data, and then if you want to upgrade some piece of the stack - be that nginx, mysql or ghost itself, you blow that particular container away and build a new one. 

Ghost-CLI is designed to live alongside all the tech that it manages: mysql, nginx, systemd, ghost, and it handles updates to ghost by downloading new software, and symlinking to it, always leaving the option for a rollback.

I'm going to close this as what you're trying to do is absolutely not expected to work - and also provides no benefit. If you want to use docker to install Ghost you absolutely can, but use the pre-prepared image: https://hub.docker.com/_/ghost/ and skip the CLI 😬

**Comment by jakubgs** [comment]
Your [`Dockerfile`](https://github.com/docker-library/ghost/blob/master/3/alpine/Dockerfile#L57) does not specify a user by default, so how is that supposed to work with Ghost CLI?

I'm trying to upgrade to `3.11.0` but I'm getting:
```
You can't run commands as the 'root' user.
Switch to your regular user, or create a new user with regular account privileges and use this user to run 'ghost update'.
```
So which is it? Do you want people to run Ghost as `root` under Docker, since that's how you set up your `Dockerfile`, or do you not?

**Comment by ErisDS** [comment]
Refer to my last comment. Docker and Ghost-CLI are fundamentally incompatible - you can choose to use one or the other. 

Ghost CLI is an official Ghost project. Docker is a community project.

**Comment by jakubgs** [comment]
Fair enough.
