### ISSUE TITLE
sudo systemctl is-active ghost_undefined  , is the "undefined" normal ? 

### ISSUE THREAD

**Issue by allanlegalstart** [TryGhost/Ghost-CLI#970]
```
Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.16.0
    Ghost-CLI Version: 1.11.0
    Environment: production
    Command: 'ghost install --no-prompt'

```

I see in the debug that it put  `sudo systemctl is-active ghost_undefined`  which seem like a javascript variable that contained nothing , I don't know if it's a problem (at least when I wanted to generate two instance of ghost on the same machine, both had that same name )

**Comment by acburdine** [comment]
@allanlegalstart were you actually seeing any errors? there was a bug for a version or two of Ghost-CLI where the `undefined` would end up making its way into the name of the systemctl service 😕 

Better question - did you first setup your Ghost installation with v1.11.0, or did you create it with an earlier version of the CLI and then upgrade the CLI to v1.11?

**Comment by allan-simon** [comment]
first setup with 1.11.0, I don't think we were seeing any errors,  well we had errors, that in the end proved not related, but at that time I was wondering that if this weird undefined in the name could be related.
