### ISSUE TITLE
.ghost-cli file permission

### ISSUE THREAD

**Issue by sarojshrestha** [TryGhost/Ghost-CLI#994]
How to solve the following issue!

**Issue Summary:** 
1) Checking file permissions

Message: Your installation folder contains a directory or file with incorrect permissions:
- ./.ghost-cli
Run sudo find ./ ! -path "./versions/*" -type f -exec chmod 664 {} \; and try again.

xyz@aaa:/var/www/ghost$ ghost start
+ sudo systemctl is-active ghost_ghost-local
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
+ sudo systemctl is-active ghost_ghost-local
✔ Validating config
✔ Checking folder permissions
✖ Checking file permissions
✔ Checking memory availability
One or more errors occurred.

1) Checking file permissions

Message: Your installation folder contains a directory or file with incorrect permissions:
- ./.ghost-cli
Run sudo find ./ ! -path "./versions/*" -type f -exec chmod 664 {} \; and try again.

Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v10.16.2
    Ghost-CLI Version: 1.11.0
    Environment: production
    Command: 'ghost start'

**List Contests**
xyz@aaa:/var/www/ghost$ ls -al
total 28
drwxrwxr-x 5 xyz xyz 4096 Aug 14 07:24 .
drwxrwxrwx 4 root  root  4096 Aug 14 06:12 ..
-rwxrwxr-x 1 xyz xyz   85 Aug 14 06:15 .ghost-cli
-rw-rw-r-- 1 xyz xyz  563 Aug 14 09:34 config.production.json
drwxrwxr-x 8 xyz xyz 4096 Aug 14 06:12 content
lrwxrwxrwx 1 xyz xyz   30 Aug 14 06:13 current -> /var/www/ghost/versions/2.28.0
drwxrwxr-x 3 xyz xyz 4096 Aug 14 06:15 system
drwxrwxr-x 3 xyz xyz 4096 Aug 14 06:12 versions

**Comment by vikaspotluri123** [comment]
@sarojshrestha as the command output says:

> Run sudo find ./ ! -path "./versions/*" -type f -exec chmod 664 {} ; and try again

So to fix your issue, run `sudo find ./ ! -path "./versions/*" -type f -exec chmod 664 {} ;`


Your best bet for support is the [forum](https://forum.ghost.org), if you have any other questions, please post them there 😄

**Comment by timskap** [comment]
> So to fix your issue, run `sudo find ./ ! -path "./versions/*" -type f -e`

That's solution doesn't work for me. Still same problem
